### ISSUE TITLE
SEGA 32X Cheats for Database Addition

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#1001]
SEGA 32X Cheats are missing from the database.  Here are some adopted from gamehacking.org.

[SEGA - 32X - New Cheats.zip](https://github.com/libretro/libretro-database/files/4223195/SEGA.-.32X.-.New.Cheats.zip)

**Comment by RobLoach** [comment]
Thanks for making sure the filenames matched too :+1:
