### ISSUE TITLE
Updated Sega CD Cheats

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#1002]
Cheats for the Sega/Mega Drive CD are sparse, but here is and update that expands them.  Taken from gamehacking.org.  Tested on Genesis Plus GX and Picodrive cores.

[SEGA - CD - New Cheats.zip](https://github.com/libretro/libretro-database/files/4232692/SEGA.-.CD.-.New.Cheats.zip)

**Comment by RobLoach** [comment]
Thanks! Renamed them to match the databse names too :+1:
