### ISSUE TITLE
Sony - Playstation.dat and retroarch bug ? 

### ISSUE THREAD

**Issue by azoreseuropa** [libretro/libretro-database#1013]
> All Sony - Playstation.dat files are combined, so check all of them?
> 
> This one has the serials:
> https://github.com/libretro/libretro-database/blob/master/dat/Sony%20-%20PlayStation.dat

Something is not right about Rockman 5 .. Please continue to read, RobLoach.

I tried to rename it according to your .dat like this:

Rockman 5 - Blues no Wana! [Complete works] (Japan).bin
Rockman 5 - Blues no Wana! [Complete works] (Japan).cue

Nope. It didn't recognised at all. So I go ahead and rename it my way like this:

Rockman 5 - Blues no Wana! (Japan).bin
Rockman 5 - Blues no Wana! (Japan).cue 

And rescan it. **VOILA! It works.** Retroarch is able to read it .. finally!

Hmm..Error or bug or misspelling or something ? 

All Rockman 1-4 and 6 have to be rename and are WORKING fine:

Rockman 1 [Complete Works] (Japan)
Rockman 2 - Dr Wily no nazo [Complete Works] (Japan)
Rockman 3 - Dr Wily no saigo [Complete Works] (Japan)
Rockman 4 - Aratanaru Yabou!! [Complete Works] (Japan)
Rockman 6 - Shijou no Tatakai!! [Complete works] (Japan)

Only Rockman 5 cannot be named just like above according to your .dat

I will have to rename this instead as I tried the different way like this:

Rockman 5 - Blues no Wana! (Japan)

And guess what ? It works. Why? Did I found an error ?

Please verify ? 

EDIT: Resolve it. I got the different dump and its working properly with your .dat. Please closed it. Thanks.

**Comment by RobLoach** [comment]
Glad it's working now! :+1: 

I hope to clean up the DAT to use the serials directly from redump. Right now it uses PSXDataCenter, which is not the best. Redump is :ok_hand:

**Comment by azoreseuropa** [comment]
Thank you.
