### ISSUE TITLE
Frustration with File and box art

### ISSUE THREAD

**Issue by azoreseuropa** [libretro/libretro-database#1014]
I followed Bandai - WonderSwan.rdb

According to this:

Rockman & Forte - Mirai Kara no Chousensha (Japan).ws
Rockman & Forte - Mirai Kara no Chousensha (Japan).png

It still didn't recongised title screen and art box. This game is working but not title screen and art box. Other games with title screen and art boxes are being recognised. Not this. Help ?!

**Comment by RobLoach** [comment]
```
Rockman _ Forte - Mirai Kara no Chousensha (Japan).png
```

https://github.com/libretro-thumbnails/Bandai_-_WonderSwan/blob/master/Named_Boxarts/Rockman%20_%20Forte%20-%20Mirai%20Kara%20no%20Chousensha%20(Japan).png

**Comment by azoreseuropa** [comment]
> ```
> Rockman _ Forte - Mirai Kara no Chousensha (Japan).png
> ```
> 
> 
> https://github.com/libretro-thumbnails/Bandai_-_WonderSwan/blob/master/Named_Boxarts/Rockman%20_%20Forte%20-%20Mirai%20Kara%20no%20Chousensha%20(Japan).png
> 
> 
> https://github.com/libretro-thumbnails/libretro-thumbnails#usage
> 
> 
> > The following characters in playlist titles must be replaced with _ in the corresponding thumbnail filename:
> > &*/:`<>?|"
> 
> 
> > Frustration
> 
> 
> If you're getting frustrated, I'd recommend taking a break. It's not good to get upset at software as it'll just cause you stress. Take a break, drink some water, go for a walk, and come back later 😉

LOL! That's ok. I am not stress.. Just frustrated. 

Now, it's working properly. Is there a way you can fix it since I dont like "_".. I prefer "-" ? :)

**Comment by RobLoach** [comment]
Correct... & causes issue on some platforms :cry:

**Comment by azoreseuropa** [comment]
Thanks. All set. :)

**Comment by azoreseuropa** [comment]
Thanks. All set. :)

**Comment by azoreseuropa** [comment]
Found thumbnails and I only got numbers till letter M for artboxes. I need
from M to Z. I need to rename them. Help ?
