### ISSUE TITLE
how to use clipboard for copy paste cheat Manually

### ISSUE THREAD

**Issue by candrapersada** [libretro/libretro-database#1016]
how to use clipboard for copy paste cheat code from browser and text
![code](https://user-images.githubusercontent.com/36833664/75594850-d27d4d00-5abc-11ea-8f92-d1b01cbc6a9a.PNG)
![code2](https://user-images.githubusercontent.com/36833664/75595107-a8785a80-5abd-11ea-91b1-4aaca466d42b.PNG)

**Comment by RobLoach** [comment]
You could likely use a code file for this, until it's input completely. Until then, have a github issue.
