### ISSUE TITLE
Saturn REDUMP Database is old

### ISSUE THREAD

**Issue by Immersion95** [libretro/libretro-database#1024]
Hi,

The Saturn database is old, 2 versions of XMVSF were added on June, 2019 but it's missing from the current database.

NES database also has problems.

Thanks a lot !

**Comment by RobLoach** [comment]
Mind checking the new one?
https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sega%20-%20Saturn.dat

**Comment by Immersion95** [comment]
Hi, how to proceed ? Should I download it ?

**Comment by RobLoach** [comment]
Online Updater > Update Databases will do it.

pkos has been working on adding serial scanning for a few other systems.

**Comment by Immersion95** [comment]
I was asking because I already tried that and it's not working. NES & Saturn don't detect newer games.

**Comment by RobLoach** [comment]
NES could do with another export with the headers:
https://github.com/libretro/libretro-database/blob/master/dat/Nintendo%20-%20Nintendo%20Entertainment%20System.dat

If that's something you could take on that would be much appreciated.

Saturn scanning could do with some testing over at the new Pull Request at https://github.com/libretro/RetroArch/pull/10291

**Comment by Immersion95** [comment]
Hi, I learned how to do a Pull request so I wanted to update the current dats which are outdated.

As I understand, it creates a custom dat from different sources. What should I update for the Saturn & NES ?

There is the dat folder & the metadat folder. Which one ?

**Comment by Immersion95** [comment]
> Mind checking the new one?
> https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sega%20-%20Saturn.dat

I didn't answer then but the dat was still outdated at that time.
