### ISSUE TITLE
Final Fantasy 3 Crashes when loading Cheat File

### ISSUE THREAD

**Issue by TyrelCB** [libretro/libretro-database#1035]
Final Fantasy 3 crashes when loading the following cheat file:

- Final Fantasy III (USA).cht

```
Segmentation fault (core dumped)
```

**Comment by RobLoach** [comment]
What system?

**Comment by TyrelCB** [comment]
@RobLoach Was using Ubuntu18.4 with the Deb version of retroarch, not sure which version. Found a work around at that time and have since switched to Manjaro. So I can't provide any more details than that. At some point I might give this another shot.
