### ISSUE TITLE
m3u 'single' names

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#1038]
[I created a tool to create m3us](https://gist.github.com/i30817/ba37fbb2b3c6e34ff926ad833f465055).

Now i have a choice where i can either give the m3u for games with more than 1 cd a misleading name `Xenogears (Disc 1).m3u` or a shorter name but one that misses images in retroarch, even with the manual scanner: `Xenogears.m3u`.

I'm asking for everytime that there is a entry to multiple disc games in the database, there is also a entry for a 'm3u entry' that is the same as one of the discs, but with the name without the disc, specifically for the cases of multi-disc 'entry files'. One of which is m3u, and another pbp (in the future there might be more).

This is probably too much of a pain to do if it's not automated, but it shouldn't be too hard too iterate over all source dat files and find things with the pattern '(Disc 1)' and and extract a name without it and then symlink the image/metadata of disc 1 to that new entry. This would include hacks for if hacks ever get images/metadata visible in RA. The method segment names in the link above does this name extraction btw if you'd like to use bash.

**Comment by RobLoach** [comment]
Could you explain to me what you're trying to accomplish? Are you trying to load m3u file? What core? Read them into RDB files? Could you help me understand?

**Comment by hizzlekizzle** [comment]
I think he just wants a thumbnail symlink that has the extra multi-disc bits removed.

**Comment by i30817** [comment]
Exactly, though i added a 'compatible' option to the program and it doesn't appear to have helped in some cases like xenogears and arc the lad collection.

For instance arc the lad appears to be marked https://github.com/libretro-thumbnails/Sony_-_PlayStation/blob/master/Named_Boxarts/Arc%20the%20Lad%20Collection%20(USA)%20(Disc%201%20of%206).png

(Disc 1 of 6).

But redump has the cue as http://redump.org/disc/672/ :

Arc the Lad Collection - Arc the Lad (USA).cue

It appears many games have names that changed since they were added. Maybe redump changed its conventions?

It would be probably in your interest to make a script to check the filenames updated for your repository with the filenames on recent redump dats to check which of the 1rst are missing on the second.

**Comment by RobLoach** [comment]
We recently updated Redump, so it's likely that the thumbnails need updates. Feel free to submit any fixes you find.
