### ISSUE TITLE
ROM Hack / Homebrew Naming Convention

### ISSUE THREAD

**Issue by rouhannb** [libretro/libretro-database#1040]
Is there a proper naming convention for ROM hacks, homebrew, or anything else outside of the No‐Intro database? The dats here seem a bit inconsistent.

**Comment by RobLoach** [comment]
Would love help adopting no-intro on them!

**Comment by rouhannb** [comment]
I suppose I can probably help clean them up.

However, I’m not really sure what the naming scheme should be. Surprisingly, No‐Intro actually has [a model](https://datomatic.no-intro.org/?page=show_record&s=32&n=2384), which is to just follow the same scheme as for regular ROMs with a region of (World) and an (Unl) flag. But, what seems to be the most common scheme here is to use a [Hack by X] tag and no region for hacks and to use a [T-Lang by X] tag and the original region for translations, and—to me, this doesn’t seem like a good idea—to always omit the version. Do you have any preferences for which scheme should be used, and if it’s the latter scheme, should there be version information in the ROM name?

**Comment by RobLoach** [comment]
Perhap try to target the latest version, and omit it?
