### ISSUE TITLE
FBNeo .dat file rebuilds ROMs that don't work

### ISSUE THREAD

**Issue by lucasmr** [libretro/libretro-database#1046]
Okay, I'm using the tagged versions:
`retroarch-1.8.5`
`libretro-database-1.8.5`
`clrmamepro 4.036a`
`FBNeo commit 198ecc91182e72966ffac731a69248e4726a195a` (same day as RetroArch tag)

Loading up the `libretro-database/metadat/fbneo-split/FBNeo - Arcade Games.dat` into clrmamepro, the default method of rebuilding (the other options are not selectable) is `Non-Merged Sets`. Rebuilding my romset like that makes the roms NOT work when selecting the games with Load Content, but the scanning works and the playlist is built correctly. `Separate BIOS Sets` are grayed out as well.

The default .rdb for FBNeo is `libretro-database/rdb/FBNeo - Arcade Games.rdb`, so I'm sure it was built using the same .dat from the clrmamepro rebuild.

What is even more confusing is that I cannot select `Split Sets` in the rebuilder with this .dat. Remember that the current folder is `fbneo-split/`.

Trying to build a .rdb using the `c_converter` utility and the dat `FBNeo\dats\FinalBurn Neo (ClrMame Pro XML, Arcade only).dat` gives the following error message:
`libretro-database/metadat/fbneo-split/FBNeo_romcenter.dat:1:7: fatal error: Expected '(' found 'version='`
This .dat provided by FBNeo makes `Split Sets` correctly, are playable when choosing Load Content, but of course can't be added to the playlist because the .rdb build failed.

**Comment by dezraj** [comment]
I think I'm having a similar issue. I've updated my romsets using a very recent Arcade dat file (which can be found here https://github.com/libretro/FBNeo/tree/master/dats ) and the roms work perfectly in the standalone fbneo emulator. But when I try to generate a playlist in Retroarch, very few games populate in the list. Something is wrong either with this dat or Retroarch's database. :/

**Comment by hizzlekizzle** [comment]
Are your ROMs torrentzipped? I believe that's necessary for the scanner/databases to pick them up. If you've already verified them elsewhere (clrmampro or whatever), you can just do a manual scan and supply the appropriate DAT to get the "pretty" names.

**Comment by dezraj** [comment]
Thank you so much. That was the problem!

I thought Clrmamepro would torrentzip all my roms after fixing them but apparently it didn't. So I manually torrentzipped them with the torrentzip program and now they are detected by the Retroarch scanning.

It's interesting that this information is available nowhere in the internet except in this site:
https://docs.libretro.com/guides/arcade-getting-started/

I suppose it had to be in FBNeo's libretro page too because it does make all the difference.

Anyway, I hope the original poster can find a solution for his issue too.

**Comment by lucasmr** [comment]
Yes, thank you for the suggestion. Using torrentzip I was able to scan the roms after rebuilding with clrmamepro.

The only issue I think is that maybe the dat folder `fbneo-split` should just be named `fbneo`? It is a Non-Merged dat after all.

**Comment by lucasmr** [comment]
One detail: the dat provided by `libretro-database/metadat/fbneo-split/FBNeo - Arcade Games.dat` still produces ROMs that are not loadable by FBNeo, but scannable.

The correct dat to use it is `FBNeo\dats\FinalBurn Neo (ClrMame Pro XML, Arcade only).dat` from the FBNeo repository.
