### ISSUE TITLE
Checksum for SNK - Neo Geo CD (NeoCD), are they up to date?

### ISSUE THREAD

**Issue by Abdess** [libretro/libretro-database#1049]
Hi,

While trying to find these BIOS:

- neocd/neocd_f.rom (Front Loader BIOS)" (sha1): a5f4a7a627b3083c979f6ebe1fabc5d2df6d083b
- neocd/neocd_sf.rom (Front Loader BIOS (SMKDAN)) (sha1): c99c44a43bded1bff4570b30b74975601bd3f94e
- neocd/neocd_st.rom (Top Loader BIOS (SMKDAN)) (sha1): d463b3a322b9674f9e227a21e43898019ce0e642
- neocd/neocd_sz.rom (CDZ BIOS (SMKDAN)) (sha1): 41ca1c031b844a46387be783ac862c76e65afbb3

After looking on the [SMKDAN's](http://smkdan.eludevisibility.org/ngcd/) site, there are [BIOSes](http://smkdan.eludevisibility.org/ngcd2/) which seem to correspond, however, with a different checksum.

Is it possible that the checksum required by libRetro is not up to date?

Thanks,

**Comment by RobLoach** [comment]
It's possible they're out of date... Mind submitting a Pull Request with the update?

**Comment by Abdess** [comment]
Sorry I just noticed the answer.
@LodanZark solved it, thanks to him: https://github.com/libretro/libretro-database/pull/1098
