### ISSUE TITLE
Sync release tags with upstrem RetroArch

### ISSUE THREAD

**Issue by tim77** [libretro/libretro-database#1064]
Hello. Please try to tag version synchronously with upstream RetroArch. This helps a lot with packaging for Linux distribution.

RetroArch version: https://github.com/libretro/RetroArch/releases/tag/v1.8.8
libretro-database version: https://github.com/libretro/libretro-database/releases/tag/v1.8.7

**Comment by RobLoach** [comment]
Great! Didn't know the new release was tagged :rocket:

**Comment by tim77** [comment]
@RobLoach thank you.
