### ISSUE TITLE
Super Mario Advance 4 dumped from Wii U scans as rom hack

### ISSUE THREAD

**Issue by autofire372** [libretro/libretro-database#1073]
Scanning a dump of the Wii U VC version of SMA4 results in the GBA rom list claiming the presence of [this](https://www.romhacking.net/hacks/2714/) rom hack. According to No-Intro, the proper name of the dump is "Super Mario Advance 4 - Super Mario Bros. 3 (USA) (Rev 1) (Wii U Virtual Console)".

**Comment by RobLoach** [comment]
This?
https://github.com/libretro/libretro-database/blob/44cd26daa00e4164841775e342ed526be5573d90/metadat/hacks/Nintendo%20-%20Game%20Boy%20Advance.dat#L102-L105

**Comment by autofire372** [comment]
Yep. That seems to override the main GBA datfile, which lists the Wii U dump with the same file signatures.
