### ISSUE TITLE
Game Gear Ristar not in database + bad name

### ISSUE THREAD

**Issue by andiandi13** [libretro/libretro-database#1076]
In retroarch thumbnails, GG Ristar is named **_Ristar ~ Ristar - The Shooting Star (World)_**

While it should be named **_Ristar - The Shooting Star (World)_**

Here is the original name : 

Ristar the Shooting Star (リスター・ザ・シューティングスター, Risutā za Shūtingu Sutā).

Also, it seems that the game isn't in the database, so should be fixed.

Thank you.

**Comment by RobLoach** [comment]
Mind submitting the suggestion up to Datomatic/No-Intro?
https://datomatic.no-intro.org/?page=show_record&s=25&n=0311

Thanks a lot.
