### ISSUE TITLE
Different name of Crash Bandicoot - Warped (USA) vs thumbnails repo

### ISSUE THREAD

**Issue by GenericMadScientist** [libretro/libretro-database#1077]
The NTSC-U version of Crash Bandicoot 3 is named 'Crash Bandicoot - Warped (USA)' in the database, while the box art image in the thumbnails repo is 'Crash Bandicoot 3 - Warped (USA).png'. I suspect this name conflict is why RetroArch is not correctly downloading this thumbnail, and I was told to report it here.

**Comment by RobLoach** [comment]
Thanks! All thumbs are over at https://github.com/libretro-thumbnails ... Feel free to push up pull requests if you find any needed fixes!
