### ISSUE TITLE
DOS.dat won't load

### ISSUE THREAD

**Issue by DocMAX** [libretro/libretro-database#1087]
I can't do a manual scan on my Total DOS Collection with DOS.dat.
I'm getting "Failed to load Arcade DAT file (invalid format?)".

**Comment by RobLoach** [comment]
Manual Scan has two uses...

1. Quick scan to create a playlist
2. Arcade DAT support

When using a manual scan to make a playlist, you don't need to supply an Arcade DAT. You'd only supply an Arcade DAT file if you're scanning for MAME or FBAlpha.

**Comment by RobLoach** [comment]
For DOS, you should be able to use "Scan Directory".
