### ISSUE TITLE
Does the Fear Effect 2 (USA) cht file work?

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#1092]
This is one of those that is emulator handled (both beetle and duckstation have it, recently in the case of duckstation).

Anyway, the last two cheats, which are supposed to make ammo infinite do nothing obvious when emptying the game gun clip.

There is a optional joker code (recognizable by RCJK and ???? in the code). But trying to map select to it in all variants (FFFE for the 'reverse complementary joker', 0100 for normal joker, 0001 for reverse joker, FEFF for complementary joker), doesn't help the other ammo codes.

Is the presence of a joker code sometimes necessary for other codes to work? Just curious. I don't think it's the case here, though i tried.

**Comment by i30817** [comment]
@stenzek told me this was because these emulators don't actually support the 'game buster' variant of the cheats.

**Comment by RobLoach** [comment]
I don't know. Test it out and see if it's broken :shrug:
