### ISSUE TITLE
(System) Missing PSX Bios files

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#1094]
dc2b9bf8da62ec93e868cfd29f0d067d dtl-h1001.bin
da27e8b6dab242d8f91a9b25d80c63b8 dtl-h1101.bin
e2110b8a2b97a8e0b857a45d32f7e187 dtl-h1202.bin
924e392ed05558ffdb115408c263dccf dtlh3000.bin
e2110b8a2b97a8e0b857a45d32f7e187 dtlh3002.bin

**Comment by lasers** [comment]
Nothing came up in core info files for those bios.

**Comment by RobLoach** [comment]
They wouldn't be in the .info files. These have been documented elsewhere, and I'm not sure if they're actually the right ones. Needs investigation.
