### ISSUE TITLE
Naming Discrepancies

### ISSUE THREAD

**Issue by baxysquare** [libretro/libretro-database#1097]
I have a few quick questions about what to name a few icons for themes over on [retroarch-assets](https://github.com/libretro/retroarch-assets/).  I want to be sure we're consistent with the database team and figured the best way to do that was to open an issue.

1. **Is it "Xbox" or "XBOX"?** - With the Libretro Database, we have "[Microsoft - Xbox](https://db.libretro.com/Microsoft%20-%20Xbox/index-0.html)" but on No Intro has "Microsoft - XBOX 360" for Digital and Title Updates.  I know we generally try to be consistent with No-Intro, but it's not a hard and fast rule.  I was planning on re-naming them all to "Xbox" but I wanted to be sure before I move forward with that change.
2. **Should we go with iQue or IQue?** - Over on No-Intro, the iQue files have been set into their own database separate from N64.  But within the Libretro themes, all system/media icons start with a capital letter, while the OS/Application/UI icons are always lower case.  I know it's nit-picky and I have no idea if the iQue DAT will ever be adopted, but if/when it is, do we use No-Intro's naming (iQue - iQue) or do we stick to our rule (IQue - iQue)?

**Comment by RobLoach** [comment]
Good questions. You're right that we usually opt for No-Intro naming, but in this case, I think we could move with our own policy....

> Is it "Xbox" or "XBOX"?

I do see `Microsoft - Xbox` adopted across some of our realms. That might be best, as I do see `Xbox` used on the XBOX website.

> Should we go with iQue or IQue?

I think `iQue - iQue` makes sense. The wiki uses it as such... https://en.wikipedia.org/wiki/IQue

I'll have to update some scripts and stuff to fix up the standard. Thanks for bringing this up!

**Comment by RobLoach** [comment]
> Should we go with iQue or IQue?

Hold on, we could merge these into the N64 database... We won't have to add a new playlist system for this.

**Comment by baxysquare** [comment]
Sounds good.  This morning I issued a [Pull Request](https://github.com/libretro/retroarch-assets/pull/387) to change all the icons from "XBOX" to "Xbox."  As I noted, they can be renamed back the other way down the line, if need be.

In terms of the iQue database, you may as well merge them into the N64 database, as that makes more sense than separating them out.  The icon artwork has already been done for a while for Automatic, Systematic, Retroactive and Neoactive. Some of them were already easter eggs for the N64 and were named as such (Nintendo - Nintendo 64 iQue Player).  

When I saw No Intro had separated iQue into its own set, I renamed them "iQue - iQue" and then noticed they were showing up at the bottom with the UI icons because we generally keep them separate by making them all lower case.  At the time, I had no idea if the DB team would roll them with N64 or keep them separated like No-Intro.  If you're good with merging the databases, I'll get them renamed back to be easter eggs.
