### ISSUE TITLE
ScummVM search: Zak McKracken not recognized

### ISSUE THREAD

**Issue by jansalleine** [libretro/libretro-database#1102]
I followed this documentation to add ScummVM games to my Lakka install:
https://www.lakka.tv/doc/ScummVM/

Works fine with all titles that I own, but for some reason not with Zak McKracken.

Steps to reproduce:
- Buy Zak McKracken on GOG ;-)
- Copy the content of ~/GOG Games/Zak McKracken and the Alien Mindbenders/data/ to /storage/roms/ScummVM/zak/
- On Lakka: echo "zak" >> /storage/roms/ScummVM/zak/zak.scummvm
- Search Folder -> Zak McKracken will not show up in playlist.

I also tried copying ~/GOG Games/Zak McKracken and the Alien Mindbenders/data/FDD/ to /storage/roms/ScummVM/zak/. Won't be recognized too.

I also tried manually adding the zak.scummvm file to /storage/playlists/ScummVM.lpl with the correct crc32 hash. Didn't work.

Hardware: Raspberry Pie 4B 
Software: Lakka (official): 2.3.2 (RPi2.RPi4.arm), retroarch 1.8.4

**Comment by RobLoach** [comment]
Thanks! Moving this to the libretro-database repo :wink:

**Comment by RobLoach** [comment]
The database for scummvm is built via [libretro-database-scummvm](https://github.com/RobLoach/libretro-database-scummvm).

It finds unique files for each game. When it can't find a unique file, it lists it in [missing-games.txt](https://github.com/RobLoach/libretro-database-scummvm/blob/master/missing-games.txt).

Looks like it misses here....
```
[WARN] No unique rom: zak-fm
[WARN] No unique rom: zak-v2-gog
[WARN] No unique rom: zak-v2-it-1
```

Surprised there are no unique roms within those zak versions. We could add them into libretro-database-scummvm manually. I'll add it to my list. Thanks!

**Comment by RobLoach** [comment]
Alrighty, just updated the dat to add `.scummvm` files for all games that don't have unique roms associated with them.

You'll want to add a `zak-v2-gog.scummvm` file with the contents of `zak-v2-gog`. Then it should index the .scummvm file.

**Comment by jansalleine** [comment]
Nice, thank you!
In the meantime I managed to add it manually with setting crc32 to 0 in the vpl file, but good that it will be easier to add those now.

**Comment by RobLoach** [comment]
Going to close this for now. Thanks a lot! Let me know if it's not working for you.
