### ISSUE TITLE
Nintendo NES+SNES hacks

### ISSUE THREAD

**Issue by Europia79** [libretro/libretro-database#1103]
wow, the Nintendo NES + SNES dats look pretty skimpy.

Here are mine (using IUPAG nomenclature):

NES:  https://hastebin.com/ohoyigivir.sql (+641 hacks) https://pastebin.com/cseexB9R
http://rainbowcraft.sytes.net/download/Dats/metadat/hacks/Nintendo%20-%20Nintendo%20Entertainment%20System.dat

SNES:  https://hastebin.com/idawiwudux.sql (+415 hacks) https://pastebin.com/WMqVnANC
http://rainbowcraft.sytes.net/download/Dats/metadat/hacks/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.dat

EDIT:  Here's a more readable list format via `7z h "*"`:
NES:  https://pastebin.com/eWNmbdrK
SNES:  https://pastebin.com/PZzGXT0r

**Comment by RobLoach** [comment]
There are infinite hacks out there. Would be impossible for us to have them all in, and keep them updated. Soft-patching works here too, so you don't have to have the ROM indexed. Just stick the .ips file beside the original rom file.

Feel free to submit the most popular as a Pull Request, just cautious about adding all of them.

**Comment by Europia79** [comment]
Rob, I reviewed thousands of hacks and I only selected the very best, most polished ones...
...I didn't just add random garbage:  That's why NES only has 641 and SNES only has 415.

But this was submitted in Oct 2020 and is likely outdated... My new list will probably have a few additions (probably less than 10 each if i had to guess... I'll have to check).

**Comment by RobLoach** [comment]
Thanks so much! :rocket:
