### ISSUE TITLE
Add cheats

### ISSUE THREAD

**Issue by Rqynestross** [libretro/libretro-database#1125]
Can someone by chance go in and add cheat codes for skies of Arcadia for dream cast? I know there are codes out there as I have them on my actual dream cast GameShark.

**Comment by RobLoach** [comment]
You can add them! https://github.com/libretro/libretro-database/blob/master/cht/Sega%20-%20Dreamcast/Skies%20Of%20Arcadia.cht

**Comment by Rqynestross** [comment]
> You can add them! https://github.com/libretro/libretro-database/blob/master/cht/Sega%20-%20Dreamcast/Skies%20Of%20Arcadia.cht

I'm not exactly sure how to. I've only ever done it directly through gamesharks and the code format on here confuses me.

**Comment by RobLoach** [comment]
You can find the documentation over at https://docs.libretro.com/guides/cheat-codes/ . It'll need to memory dumping to find the right values.
