### ISSUE TITLE
Errors in Dats

### ISSUE THREAD

**Issue by romzboy** [libretro/libretro-database#1143]
https://github.com/libretro/libretro-database/blob/master/dat/Nintendo%20-%20GameCube.dat Name not found as frist object in (), on line 15
https://github.com/libretro/libretro-database/blob/master/dat/Nintendo%20-%20Nintendo%203DS.dat Name not found as frist object in (), on line 15
https://github.com/libretro/libretro-database/blob/master/dat/Nintendo%20-%20Wii%20U.dat Name not found as frist object in (), on line 16
https://github.com/libretro/libretro-database/blob/master/dat/Nintendo%20-%20Wii.dat Name not found as frist object in (), on line 14
https://github.com/libretro/libretro-database/blob/master/dat/Sony%20-%20PlayStation%203.dat Name not found as frist object in (), on line 14

**Comment by RobLoach** [comment]
This should be fixed. Thanks.
