### ISSUE TITLE
Updated NEC cheats

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#1167]
Since negativeExponent expanded on the cheat functionality for NEC consoles back in September last year, I went ahead and updated the cheats for the following systems to reflect the changes:

[NEC - PC Engine - TurboGrafx 16 - Cheats.zip](https://github.com/libretro/libretro-database/files/6628274/NEC.-.PC.Engine.-.TurboGrafx.16.-.Cheats.zip)
[NEC - PC Engine CD - TurboGrafx-CD - Cheats.zip](https://github.com/libretro/libretro-database/files/6628275/NEC.-.PC.Engine.CD.-.TurboGrafx-CD.-.Cheats.zip)
[NEC - PC Engine SuperGrafx - Cheats.zip](https://github.com/libretro/libretro-database/files/6628276/NEC.-.PC.Engine.SuperGrafx.-.Cheats.zip)

This doubles the available codes for TG16, quadruples the codes available for TG16CD, and allows functional codes for the PCE SGX.

All codes were taken from databases at gamehacking.org.  I did not create any of them, I simply put them into the new format introduced by negativeExponent, and all credit goes to the original authors on gamehacking.org.

Edit: Found a few mistakes in a couple .cht files and reuploaded the .zips.  @RobLoach , these should be ready for a PR.
Edit 2: Spelling.

**Comment by RobLoach** [comment]
Nicely done, @summonthethunder! I can turn this into a PR if you'd like.

**Comment by summonthethunder** [comment]
If everything is well with them, by all means, please merge them!

It's been awhile since I looked at them, but I did promise to update them if a way to expand the cheats was found, and negativeExponent delivered.

The PC Engine SuperGrafx cheats are new, I believe, and the others can replace the already existing codes.

I tested a handful of each of these on Beetle Fast and Beetle PCE and both work for single and multiline codes.

**Comment by summonthethunder** [comment]
Updated the .zips one more time to add a few games I missed and fix a few
more.
