### ISSUE TITLE
PC Engine CD ISO not recognized

### ISSUE THREAD

**Issue by leskenazi** [libretro/libretro-database#1172]
I have several PC Engine CD ISO (severals for Rondo of Blood and 1 for Spriggan), and the process to import them fails for all of them. Seems like the CRC is OK thought (for some of them at least).

Please see the attached Retroarch log.
[retroarch.log](https://github.com/libretro/libretro-database/files/6681883/retroarch.log)

[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Jun 13 2021
[INFO] Version: 1.9.5
[INFO] =================================================
[INFO] [Input]: Found input driver: "cocoa".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [GL]: Found GL context: cocoagl
[INFO] [GL]: Detecting screen resolution 960x720.
[INFO] [GL]: Vendor: Intel Inc., Renderer: Intel(R) Iris(TM) Graphics 6100.
[INFO] [GL]: Version: 2.1 INTEL-14.7.8.
[INFO] [GL]: Using resolution 1920x1440
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] Port 0: PLAYSTATION(R)3 Controller.
[INFO] [Input]: Found HID driver: "iohidmanager".
[INFO] [Joypad]: Found joypad driver: "hid".
[INFO] [Video]: Found display server: null
[INFO] [CoreAudio]: Using output sample rate of 48000.0 Hz
[INFO] [CoreAudio]: Using buffer size of 24576 bytes: (latency = 64 ms)
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: [/Users/Laurent/Library/Application Support/RetroArch/config/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/Users/Laurent/Library/Application Support/RetroArch/config/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/Users/Laurent/Library/Application Support/RetroArch/config/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/Users/Laurent/Library/Application Support/RetroArch/config/content_favorites.lpl].
[INFO] Port 1: PLAYSTATION(R)3 Controller.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 01).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 02).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 03).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 04).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 05).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 06).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 07).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 08).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 09).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 10).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 11).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 12).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 13).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 14).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 15).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 16).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 17).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 18).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 19).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 20).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 21).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 22).bin
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue'...
[INFO] Reading first data track...
[INFO] Could not find compatible system.
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue'...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue' primary track: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 02).bin
 (0, 24399648)
[INFO] Reading first data track...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue' crc: c681f9da
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo (JP)/Akumajou Dracula X - Chi no Rondo (JP).cue'...
[INFO] Reading first data track...
[INFO] Could not find compatible system.
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo (JP)/Akumajou Dracula X - Chi no Rondo (JP).cue'...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo (JP)/Akumajou Dracula X - Chi no Rondo (JP).cue' primary track: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo (JP)/Akumajou Dracula X - Chi no Rondo (JP).img
 (8620080, 24399648)
[INFO] Reading first data track...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo (JP)/Akumajou Dracula X - Chi no Rondo (JP).cue' crc: 42a597b1
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 01).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 02).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 03).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 04).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 05).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 06).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 07).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 08).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 09).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 10).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 11).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 12).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 13).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 14).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 15).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 16).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 17).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 18).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 19).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 20).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 21).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 22).bin
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue'...
[INFO] Reading first data track...
[INFO] Could not find compatible system.
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue'...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue' primary track: /Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 02).bin
 (0, 24399648)
[INFO] Reading first data track...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/Akumajou Dracula X - Chi no Rondo- ter/Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue' crc: c681f9da
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005]-bis/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005].ISO
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005]-bis/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005].cue'...
[INFO] Reading first data track...
[INFO] Could not find compatible system.
[INFO] Found disc label 'PRODUCER'
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005]-bis/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005].cue'...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005]-bis/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005].cue' primary track: /Volumes/soft/Game/Nec PC Engine CD/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005]-bis/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005].ISO
 (8620080, 23870448)
[INFO] Reading first data track...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005]-bis/AKUMAJOU_DRACULA_X_-_CHI_NO_RINNE_(NTSC-J)_[KMCD3005].cue' crc: 39528b57
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 01).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 02).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 03).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 04).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 05).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 06).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 07).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 08).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 09).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 10).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 11).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 12).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 13).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 14).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 15).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 16).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 17).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 18).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 19).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 20).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 21).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 22).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 23).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 24).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 25).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 26).bin
[INFO] Pruning file referenced by cue: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 27).bin
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan).cue'...
[INFO] Reading first data track...
[INFO] Could not find compatible system.
[INFO] Parsing CUE file '/Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan).cue'...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan).cue' primary track: /Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan) (Track 02).bin
 (0, 4969776)
[INFO] Reading first data track...
[INFO] CUE '/Volumes/soft/Game/Nec PC Engine CD/Seirei Senshi Spriggan (Japan)/Seirei Senshi Spriggan (Japan).cue' crc: 14db03f6
[INFO] [Config]: Saved new config to "/Users/Laurent/Library/Application Support/RetroArch/config/retroarch.cfg".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Average monitor Hz: 58.937938 Hz. (58.210 % frame time deviation, based on 2048 last samples).
[INFO] [Video]: Average monitor Hz: 58.937938 Hz. (58.210 % frame time deviation, based on 2048 last samples).

**Comment by RobLoach** [comment]
There have been updates to how PC Engine is scanned. Mind tyring it out in the next version of RA?

**Comment by RobLoach** [comment]
Serial scanning has been updated across a lot of CDs. Mind another test?
