### ISSUE TITLE
Incorrectly labeled entries in Sony - PlayStation.rdb

### ISSUE THREAD

**Issue by cbrumbau** [libretro/libretro-database#1226]
It appears that SCUS-94163, SCUS-94164, SCUS-94165, which should be Final Fantasy VII (USA) Disks 1, 2, 3 are labelled as:
Final Fantasy VII (USA) (Disc 3)/Final Fantasy VII (USA) (Disc 3).bin
Final Fantasy VII (USA) (Disc 2 of 3)/Final Fantasy VII (USA) (Disc 2 of 3).cue
Final Fantasy VII (USA) (Disc 3 of 3)/Final Fantasy VII (USA) (Disc 3 of 3).cue
with Disk 1 having all fields as Disk 3 and the latter two having incorrect naming, inconsistent descriptions to the rest of the database, incorrect rom names, and are lacking checksums.

Additionally SCUS-94451 has all fields incorrectly filled as Syphon Filter 2 (USA) (Disc 2) when it is in fact Disk 1.

**Comment by RobLoach** [comment]
Thanks! I believe a lot of the scanning of disc media will be fixed by the scanning update in the pipeline. Stay tuned.

**Comment by Ashlander0** [comment]
I was about to post this as well. Also noticed the standard version of Jet Moto 2 is incorrectly labelled as Jet Moto 2 - Championship Edition.

**Comment by RobLoach** [comment]
This should be fixed? Mind another test after doing an Update Database?

**Comment by jackcmedia** [comment]
I can reproduce the same behavior after updating Retroarch to the 1.10.3 release and updating the database files.

**Comment by jackcmedia** [comment]
Come to think of it, Redump doesn't handle all multidisc games in the same way. Case in point:

- [Parasite Eve (USA) (Disc 1)](http://redump.org/disc/116/) has Serial SLUS-00662 and no Internal Serial.
- [Parasite Eve (USA) (Disc 2)](http://redump.org/disc/117/) has Serial SLUS-00668 and no Internal Serial.

This is quite different from the way they handled FF7 (same Serial, different Internal Serial). With the source data already being handled inconsistently,

I guess game scanning should translate the Serials to a homogeneous scheme, as mentioned in RobLoach/libretro-dats#38.
