### ISSUE TITLE
Quake.dat: add PAK1.PAK and directory

### ISSUE THREAD

**Issue by satorope** [libretro/libretro-database#1238]
Insufficient PAK1.PAK for Quake.
Add directory to identify games.

**Comment by RobLoach** [comment]
R troarch doesn't use directories in the Rom path. But if you some testing on it, I'd love to hear your experience.

**Comment by satorope** [comment]
I'm sorry I didn't reply because I couldn't use Github.
The folder is only part of the ROM name, and even then the database seems to recognize the ROM hash correctly, so I can play the game.
