### ISSUE TITLE
CannonBall playlist creation broken

### ISSUE THREAD

**Issue by metchebe** [libretro/libretro-database#1243]
Playlist creation when scanning for CannonBall does not work after (presumably) the latest update:

https://github.com/libretro/libretro-database/commit/949d4aabf7567a4704297d7ba4e2ead8703b4fa3

It worked when the dat file referenced only one rom (epr-10187.88, which the core loads as content).

**Comment by metchebe** [comment]
Relevant pull request: https://github.com/libretro/libretro-database/pull/1186

This was merged without being tested (?). There was indeed an observation regarding this PR.

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/commit/d5ad7637f327bad39dc28d27c9476274c5996813
