### ISSUE TITLE
Nintendo DS Download Play Station?

### ISSUE THREAD

**Issue by ghost** [libretro/libretro-database#1264]
Hello there. I came across the Nintendo - Nintendo DS (Download Play).dat page and I am interested in trying out the content on a R4. Is it possible to download the files from here to a R4? I have two DS systems, a R4, and the original DS games that are compatible for the downloadable content. If this isn't allowed and the files are here just to examine, please disregard my question.

**Comment by Twilight-Dusk1991** [comment]
> These are just database files. There are no games here.

Explain what you mean?

**Comment by hizzlekizzle** [comment]
collections of hashes and serial numbers. These files are just for sorting and identifying the games you already have.

**Comment by Twilight-Dusk1991** [comment]
Ah, I see. Thank you for the information.
