### ISSUE TITLE
Where's the Sony Playstation 2 database?

### ISSUE THREAD

**Issue by sbritorodr** [libretro/libretro-database#1278]
In this repository, there's no Playstation 2 Database, however, in \RetroArch\database\rdb there's a Sony Playstation 2 rdb file.

How can I access the source code for this database? For some reason retroarch cannot automatically scan games

**Comment by RobLoach** [comment]
There's a RDB file, yeah. If it's not picking up the games, you could use the Manual Scan instead.

**Comment by sbritorodr** [comment]
But why doesn't auto scan work? The file size, md5, sha1 and title matches...

**Comment by RobLoach** [comment]
Disc media uses serial scanning. Sometimes RetroArch doesn't scan the serial correctl. Which title?

**Comment by sbritorodr** [comment]
Metal Gear Solid 3 - Snake Eater (SLES-82032)

**Comment by sbritorodr** [comment]
Okay, founded the database. It is under [`metadat/redump/Sony - PlayStation 2.dat`](url)
