### ISSUE TITLE
Pokemon cheats

### ISSUE THREAD

**Issue by Danny98112** [libretro/libretro-database#1303]
Heyyo Guys,
I have a problem with cheating with my miyoo mini... I tryed the cheats from libreto for pokemon Smaragd/Emerald and they all dont work. I dont know if im doing anything wrong :/ 
maybe someone of u could help me out.

**Comment by RobLoach** [comment]
It's possible the cheats need an update. Have a look at the file and compare them to ones you find online. It's also possible the core you're using doesn't support it. REad through https://docs.libretro.com/guides/cheat-codes/
