### ISSUE TITLE
smt 1 file download

### ISSUE THREAD

**Issue by kiasilverfatalis** [libretro/libretro-database#1307]
hey i saw your text file for this game's cheats, do you happen to have the .cht file anywhere, you can send to me? there doesn't seem to be an option to download yours. and i was wondering if you had one for if? one where there's all items, infinie hp/mp for all characters, demons, etc?

**Comment by RobLoach** [comment]
You could literally download it through the repo? Click the Code -> Download Zip button  :shrug:  ... If one does not exist, then it does not exist.
