### ISSUE TITLE
Sega - Mega Drive - Genesis DAT file won't open by Romcenter

### ISSUE THREAD

**Issue by FourEyedGeek** [libretro/libretro-database#1309]
Fails to create with unknown datafile format.

I have used an older version from a year ago and it works fine, and the recent Sega - Game Gear DAT file and it works fine too.

**Comment by RobLoach** [comment]
Is there an error log?

**Comment by FourEyedGeek** [comment]
Hello Rob,

I deleted the old log, fired up Romcenter and attempted to use that DAT file again, same error.

[cid:6dc1aeba-7d6f-42ca-b9cc-b49f9c71ffde]

To get to it in the log, you can search:
<log4j:event logger="Romcenter" level="ERROR" timestamp="1658118950438"

Good luck

Fabian

________________________________

**Comment by RobLoach** [comment]
You'll likely want to use the No-Intro/datomatic DATs instead of these ones. Going to close for now.
