### ISSUE TITLE
ROM scan not detecting NES ROMs.

### ISSUE THREAD

**Issue by txk2048** [libretro/libretro-database#1322]
When I scan my NES ROMs, two of my games are not automatically detected:

- Micro Mages Second Quest (itch.io release)
- Super Mario Bros (dumped from 3DS VC)

How should I add these to the recognised ROM database?

**Comment by RobLoach** [comment]
Feel free to add them over at https://github.com/libretro/libretro-database/blob/master/metadat/homebrew/Nintendo%20-%20Nintendo%20Entertainment%20System.dat .
