### ISSUE TITLE
Bust-A-Move (SNES) cheats not working

### ISSUE THREAD

**Issue by brunocar** [libretro/libretro-database#1341]
I've been trying to get the US version of this game to load cheats and they simply do not, i've tried all of the ones in the database, my rom is no-intro and everything, it just wont work.

**Comment by RobLoach** [comment]
The cheats could use an update

**Comment by brunocar** [comment]
Update? shouldnt they work as long as the hash matches?

**Comment by brunocar** [comment]
Update, as it turns out, its not a database issue, rather, the beetle supafaust core isnt able to load cheats.
