### ISSUE TITLE
System DAT is Missing PS2 / PCSX2 BIOS Files

### ISSUE THREAD

**Issue by emmercm** [libretro/libretro-database#1356]
System DAT: https://github.com/libretro/libretro-database/blob/6809e6aa4f4600fd91457cf5361d4543ccfae611/dat/System.dat

PCSX2 BIOS files: https://docs.libretro.com/library/pcsx2/#bios

**Comment by RobLoach** [comment]
Great idea! Would you mind adding the entries? I won't be able to dump them.

**Comment by emmercm** [comment]
I can take a stab!
