### ISSUE TITLE
Unquoted backslashes in dat files

### ISSUE THREAD

**Issue by cyco** [libretro/libretro-database#1371]
I couldn't find a formal specification for `.dat` files, but I find it a bit odd that literal backslashes in quoted strings are not escaped.
Right now there is some ambiguity as to how to interpret `\n` for example, sometimes it indicates a newline character (eg https://github.com/libretro/libretro-database/blob/master/metadat/magazine/edge_review/Nintendo%20-%20Nintendo%2064.dat#L8) and sometimes it should be interpreted literally as `\` `n` (eg https://github.com/libretro/libretro-database/blob/master/metadat/no-intro/Tiger%20-%20Gizmondo.dat#L170).

Could some one clarify this for me?

**Comment by RobLoach** [comment]
I removed that Edge Review one, and gizmondo not even used https://github.com/libretro/libretro-database/pull/1374

**Comment by RobLoach** [comment]
Thanks. Know any others?

**Comment by cyco** [comment]
No, I think others are fine. I was still hoping for some clarification on the format, but that will do for now. Thanks for your help!
