### ISSUE TITLE
Games missing previe images

### ISSUE THREAD

**Issue by fekir** [libretro/libretro-database#1402]
I have multiple games that are recognized by retroarch, but for which retroarch does not find a title, and/or snap, and/or boxart image.

This happens for multiple platforms (all game boy variants, wii, nes, scummvm, ...)

Where can I upload those missing images so that they are available to everyone using retroarch?

**Comment by RobLoach** [comment]
Thanks! Happy to have more people involved in the thumbs. The main repo and docs are over at https://github.com/libretro-thumbnails/libretro-thumbnails 

They're split into individual repos at https://github.com/libretro-thumbnails . There's constant updates, so feel free to check it out and see what you can fill in. It's updated on the server every thursday.

**Comment by fekir** [comment]
Oh, thank you

I thougth the thumbnails came primaly from external entities, like the databases for recognizing the rom files

**Comment by RobLoach** [comment]
It's all a bunch of contributors that make it happen :wink:
