### ISSUE TITLE
libretro-database/cht /Sony - PlayStation/

### ISSUE THREAD

**Issue by ZweiBR** [libretro/libretro-database#1404]
https://github.com/libretro/libretro-database/tree/master/cht/Sony%20-%20PlayStation

ends in the letter M

Parasite Eve is missing

**Comment by RobLoach** [comment]
If you donwload the repository with git or with a .zip, you'll get them. I see 1950 files.

**Comment by ZweiBR** [comment]
> If you donwload the repository with git or with a .zip, you'll get them. I see 1950 files.

which way ?
link

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/archive/refs/heads/master.zip

**Comment by ZweiBR** [comment]
> https://github.com/libretro/libretro-database/archive/refs/heads/master.zip

thanks
