### ISSUE TITLE
Star Fox for the SNES is being detected as Star Fox 2

### ISSUE THREAD

**Issue by Mitchfynde** [libretro/libretro-database#1451]
If you look at the code for "Nintendo - Super Nintendo Entertainment System.dat" at line 123 and line 136 you'll see they are both marked as Star Fox 2. The code at line 123 should be Star Fox 1. 136 is still correct though.

![image](https://github.com/libretro/libretro-database/assets/69119725/c9071276-2935-4533-ad73-3cc98f236ca4)

**Comment by RobLoach** [comment]
Great catch!

**Comment by Mitchfynde** [comment]
> Great catch!

Maybe the only time being a fan of the first Star Fox has ever been useful!
