### ISSUE TITLE
Possibly wrong checksum for nmk004.bin

### ISSUE THREAD

**Issue by heldderarbeit** [libretro/libretro-database#1466]
I downloaded `FinalBurn Neo (ClrMame Pro XML, Arcade only).dat` from https://github.com/libretro/libretro-database/blob/master/metadat/fbneo-split/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat and loaded it into ClrMamePro.

When I run the Scanner Tool, I get the following error:

```
NMK004 Internal ROM [system: NMK004 Internal ROM - folder: nmk004 - size: 8kb]
missing biosset: NMK004 Internal ROM
missing BIOS rom: nmk004.bin [size: 8192] [CRC32: 8ae61a09]
```

And several other errors on Roms which need this bios. But NMK004 is allegedly the only missing set from my collection.

My nmk004.bin has the checksum `b2ef2640`, not `8ae61a09`. And there doesn't seem to be an upload to the internet of that file with the checksum `8ae61a09,` leading me to believe that the checksum might be wrong in the first place.

If you go to the following links, all of these uploads have the checksum `b2ef2640`:

https://archive.org/download/MAME0.193RomCollectionByGhostware/nmk004.zip/
https://archive.org/download/mame-0.221-roms-merged/nmk004.zip/
https://www.planetemu.net/rom/fb-alpha/nmk004-2
https://www.retrostic.com/roms/mame/nmk004-43859/download

Feel free to delete these links if there's legal issues, it's just for illustration purposes.

I think this website http://daifukkat.su/blog/archives/2014/09/13/nmk004_rom_dumping_part_5_the_release/ has the original dump of NMK004. If you download http://daifukkat.su/files/nmk004.zip and check the crc32, it too does say `b2ef2640`:

```
cksum nmk004.bin
$ 3002017344 8192 nmk004.bin
printf "%x\n" 3002017344
$ b2ef2640
```

There's also another thing. If you compare the DAT files for `FinalBurn Neo (ClrMame Pro XML, Arcade only)` and https://github.com/AntoPISA/MAME_Dats/blob/main/ARCADE_xml/arcade.xml for a game which needs `nmk004.bin `like `bioship`:

```
<machine name="bioship" sourcefile="nmk/nmk16.cpp">
		<description>Bio-ship Paladin</description>
		<year>1990</year>
		<manufacturer>UPL (American Sammy license)</manufacturer>
		<rom name="2.ic14" size="131072" crc="acf56afb" sha1="0e8ec494ab406cfee24cf586059878332265de75" region="maincpu" offset="0"/>
		<rom name="1.ic15" size="131072" crc="820ef303" sha1="d2ef29557b05abf8ae79a2c7ce0d15a91b36eeff" region="maincpu" offset="1"/>
		<rom name="7" size="65536" crc="2f3f5a10" sha1="c1006eb755eec75f69dc7972d78d0c59088eb140" region="fgtile" offset="0"/>
		<rom name="sbs-g_01.ic9" size="524288" crc="21302e78" sha1="a17939c0529c8e9ec2a4edd5e6be4bcb67f86787" region="bgtile" offset="0"/>
		<rom name="sbs-g_03.ic194" size="524288" crc="60e00d7b" sha1="36fd02a7842ce1e79b8c4cfbe9c97052bef4aa62" region="sprites" offset="0"/>
		<rom name="sbs-g_02.ic4" size="524288" crc="f31eb668" sha1="67d6d56ea203edfbae4db658399bf61f14134206" region="gfx4" offset="0"/>
		<rom name="8.ic27" size="65536" crc="75a46fea" sha1="3d78cfc482b42779bb5aedb722c4a39cbc71bd10" region="tilerom" offset="0"/>
		<rom name="9.ic26" size="65536" crc="d91448ee" sha1="7f84ca3605edcab4bf226dab8dd7218cd5c3e5a4" region="tilerom" offset="1"/>
		<rom name="6.ic120" size="65536" crc="5f39a980" sha1="2a440f86685249f9c317634cad8cdedc8a8f1491" region="audiocpu" offset="0"/>
		<rom name="sbs-g_04.ic139" size="524288" crc="7c74cc4e" sha1="92097b372eacabdb9e8e261b0bc4223821ff9273" region="oki1" offset="0"/>
		<rom name="sbs-g_05.ic160" size="524288" crc="f0a782e3" sha1="d572226b8e597f1c34d246cb284e047a6e2d9290" region="oki2" offset="0"/>
		<rom name="82s135.ic94" size="256" crc="98ed1c97" sha1="f125ad05c3cbd1b1ab356161f9b1d814781d4c3b" region="proms" offset="0"/>
		<rom name="82s129.ic69" size="256" crc="cfdbb86c" sha1="588822f6308a860937349c9106c2b4b1a75823ec" region="proms" offset="100"/>
		<rom name="82s123.ic154" size="32" crc="0f789fc7" sha1="31936c21720802da20e39b4cb030e448353e7f19" region="proms" offset="200"/>
		…
```
		
```
<game name="bioship" romof="nmk004" sourcefile="pst90s/d_nmk16.cpp">
		<description>Bio-ship Paladin</description>
		<year>1990</year>
		<manufacturer>UPL (American Sammy license)</manufacturer>
		<rom name="2.ic14" size="131072" crc="acf56afb"/>
		<rom name="1.ic15" size="131072" crc="820ef303"/>
		<rom name="6.ic120" size="65536" crc="5f39a980"/>
		<rom name="7" size="65536" crc="2f3f5a10"/>
		<rom name="sbs-g_01.ic9" size="524288" crc="21302e78"/>
		<rom name="sbs-g_03.ic194" size="524288" crc="60e00d7b"/>
		<rom name="sbs-g_02.ic4" size="524288" crc="f31eb668"/>
		<rom name="8.ic27" size="65536" crc="75a46fea"/>
		<rom name="9.ic26" size="65536" crc="d91448ee"/>
		<rom name="sbs-g_04.ic139" size="524288" crc="7c74cc4e"/>
		<rom name="sbs-g_05.ic160" size="524288" crc="f0a782e3"/>
		<rom name="82s135.ic94" size="256" crc="98ed1c97"/>
		<rom name="82s129.ic69" size="256" crc="cfdbb86c"/>
		<rom name="82s123.ic154" size="32" crc="0f789fc7"/>
		<rom name="nmk004.bin" merge="nmk004.bin" size="8192" crc="8ae61a09"/>
		<video type="raster" orientation="horizontal" width="256" height="224" aspectx="4" aspecty="3"/>
		<driver status="good"/>
	</game>
```
	
You can see that both of the entries share 14 roms with the exact same checksum. But `bioship` from the FBNeo Dat needs an additional rom `nmk004.bin` which doesn't seem to be necessary in https://www.progettosnaps.net/dats/MAME/packs/MAME_Dats_267.7z. And in Retroarch MAME2003Plus boots up `bioship` just fine, whereas FBNeo running on the same file complains about the missing `nmk004.bin`.  This seems to be the case for every game which "needs" this bios, like `blkheart`.

**Comment by RobLoach** [comment]
These dat files get out of date pretty quickly. Could likely do with an update from the upstream. @alfrix and @harveyhu2012 , what do you think?

**Comment by alfrix** [comment]
it's been a while since I've done anything with retroarch, it seems that the dat you are linking is outdated, fbneo dats are located at:
https://github.com/libretro/FBNeo/tree/master/dats

**Comment by heldderarbeit** [comment]
It seems like I linked the wrong dataset in the beginning of my post.

The behaviour I described occurs with the 12.3 MB DAT updated 2 days ago, downloaded from https://github.com/libretro/FBNeo/blob/master/dats/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat. This is where `nmk004.bin` = `8ae61a09`.

If I download the 10.1 MB DAT from https://github.com/libretro/libretro-database/blob/master/metadat/fbneo-split/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat, I don't have this problem. But then again, that file is 2 years old…
Here is `nmk004.bin` = `83b6f611`. If you search for that checksum on the internet, you can find references to several ROM sites. If you search for the checksum `8ae61a09`on the other hand, you find nothing except from this thread, lol.

Seems like this change only was introduced a few days ago on 8th July: https://github.com/libretro/FBNeo/commit/b63598f8120f280db24c3af5433274c6a2eb6d91

So seems like the new dump with the checksum `8ae61a09` has not yet surfaced on the internet?

**Comment by alfrix** [comment]
> It seems like I linked the wrong dataset in the beginning of my post.
> 
> The behaviour I described occurs with the 12.3 MB DAT updated 2 days ago, downloaded from https://github.com/libretro/FBNeo/blob/master/dats/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat. This is where `nmk004.bin` = `8ae61a09`.
> 
> If I download the 10.1 MB DAT from https://github.com/libretro/libretro-database/blob/master/metadat/fbneo-split/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat, I don't have this problem. But then again, that file is 2 years old… Here is `nmk004.bin` = `83b6f611`. If you search for that checksum on the internet, you can find references to several ROM sites. If you search for the checksum `8ae61a09`on the other hand, you find nothing except from this thread, lol.
> 
> Seems like this change only was introduced a few days ago on 8th July: [libretro/FBNeo@b63598f](https://github.com/libretro/FBNeo/commit/b63598f8120f280db24c3af5433274c6a2eb6d91)
> 
> So seems like the new dump with the checksum `8ae61a09` has not yet surfaced on the internet?

fbnarcade-fullnonmerged/arcade (updated 7 of july)

 > 8ae61a09  nmk004.bin

so it's ok, close this.
