### ISSUE TITLE
retroarch vita core problem FinalBurn Neo

### ISSUE THREAD

**Issue by allkhan** [libretro/libretro-database#1481]
from release 1.16.0  to the current  1.19.1 , stable  and nightly, when using the FinalBurn Neo core on psvita will crash , retroarch closes  .deleting RetroArch-salamander.cfg  retroarch can be accessed again, but to use the FinalBurn Neo core will crash again.  
I stayed in the release 1.15.0 to be able to use FinalBurn Neo core

**Comment by RobLoach** [comment]
Would you be able to get the logs?

**Comment by allkhan** [comment]
> Would you be able to get the logs?
![2024-08-31-202024](https://github.com/user-attachments/assets/ed9bdeb8-2616-420f-839f-61ba958d07a4)

**Comment by allkhan** [comment]
> Would you be able to get the logs?

https://drive.google.com/file/d/1zD_RlibWcnLfGS9BLMn62nzoXK-BJlRY/view?usp=drive_link

**Comment by RobLoach** [comment]
Sounds like an issue with FinalBurn Neo. May want to create the issue over there https://github.com/finalburnneo/FBNeo
