### ISSUE TITLE
Help Needed!!!

### ISSUE THREAD

**Issue by Impulse706** [libretro/libretro-database#1486]
I have some Gamecube games, and PS2 games. I really want to run them using retroarch. I look for the cores and can't find them. I don't understand how to use all of this raw code, and where to download the cores. I am using the Nintendo Switch version of retroarch, and It also won't see my .CXI files!!! Any help would be highly appreciated. Thank you.

**Comment by Conan179** [comment]
Retroarch on Nintendo switch dosnt run ps2 or gc games.

**Comment by Impulse706** [comment]
ohhhhh. Great.... Would you happen to know any Emulator that Does on switch? Thanks.

**Comment by RobLoach** [comment]
There are a few options out there. The first Google result I found was https://emulation.gametechwiki.com/index.php/Emulators_on_Switch
