### ISSUE TITLE
[HELP] Sony Playstation DAT file for PBP file

### ISSUE THREAD

**Issue by lollo78** [libretro/libretro-database#164]
@Kivutar and @RobLoach 
Hi guys I created a new separate Sony Playstation .dat for PBP file created with PSX2PSP http://appnee.com/psx2psp/.
Twinaphex advice me to ask you about this, to learn the way of "metadat".
What this means exactly? :D

**Comment by RobLoach** [comment]
Stick the .dat file in the `metadat/goodtools`, rebuild the database with https://github.com/libretro/RetroArch/tree/master/libretro-db#compiling-the-database . replace the rdb files.

Does the .dat file exist somewhere else? Would be good to bring it in if it's maintained somewhere else.

**Comment by lollo78** [comment]
I'm not sure if I understand correctly. The GoodTools that i know is this:
mega:///#!OYlHBQhA!snrSepY-add2_WZ36-vOtKz8YrNxaP1HH5a-hhEMvrQ
:D 

I created the PBP database scanning my games. 
You can see the dat file it in attached (I done also the .rdb, but for now I send you only the dat). 
[Sony - PlayStation (PBP).dat.zip](https://github.com/libretro/libretro-database/files/311026/Sony.-.PlayStation.PBP.dat.zip)

What is this metodat approach and what are exactly the tools that I should use?
I'm confused ;)

**Comment by RobLoach** [comment]
Just stick the DAT in the goodtools folder, or any other folder there, and recompile the database. It'll merge all the DATs in the rdb.

**Comment by lollo78** [comment]
So with this tip I can merge my (PBP).dat into the actual SonyPlaystation.dat of the libretro-database?
So I'll use only one dat?
If I undestand well... WOW it's so nice! This could be the best way to merge PBP games into the official Playstation DAT.

**Comment by RobLoach** [comment]
What is the PBP?

**Comment by lollo78** [comment]
PBP is a file extention created with PSX2PSP http://appnee.com/psx2psp/.
It's used to save disk space and to merge more PSX ISO (for the games with Disc 1, Disc 2...) in one file only.

**Comment by lollo78** [comment]
FK!!!! 
I read better and now I understand.

Just to know...
how metadat handles conflicts?
Whats happens in Retroarch scanning if my.dat (inside /metadat/goodtools folder) use same CRC of the original .dat file (inside /dat folder) but different name?

**Comment by Kivutar** [comment]
Then the name in the metadat override the name in the dat

**Comment by lollo78** [comment]
Here I am :D 
Guys, I done my test and I need again your help.

If I compile the rdb using only my Sony Playstation .dat (see the zip above), that use CRC info instead of Serial, I can scan my games collection in PBP extention, but all the procedure is very slow for only 27 games.

If I use the metadat way the rdb files generated doesn't work. After the scanning, no playlist is created. 

Maybe PSX scanning not use CRC but only Serial code? 

How can I solve?

**Comment by RobLoach** [comment]
I'd be interested in the [Redump](http://redump.org/) ones. PBP CRCs won't be consistent, or guaranteed to match.

**Comment by lollo78** [comment]
yeah, PBP CRCs could be different from an user to another. 
If I create a PBP starting from an ISO or a BIN file (of the same game) the resultant CRC doesn't match. 
But consider that PBP is very userful to save disk space and reduce the number of discs per game.
PBP is supported in pcsx_rearmed and now also in beetle-psx-libretro: adding this scan opportunity could be very appreciated.

**Comment by RobLoach** [comment]
The [#2033 Alternative Scanning Method](https://github.com/libretro/RetroArch/issues/2033) would be a good one to have.

**Comment by lollo78** [comment]
about the Alternative Scanning Method: there is a beta/alpha implementation?

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/pull/251

**Comment by RobLoach** [comment]
For now, I'm going to close this one. With the Alternative Scanning Method, and the discussions of switching to Redump for Playstation, there's a lot of other things to consider. If you put together a standard docuemtnation method for making PBPs, along with a DAT, we could add it.
