### ISSUE TITLE
NES repeated data

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-database#17]
There's repeated data to NES database, name, description, analog supported and rumble supported appears twice.

Start Content is in the middle of the information.

![retroarch - bug 2](https://cloud.githubusercontent.com/assets/5431285/8510025/ee530d92-22a1-11e5-8ea0-b93f31d7791d.png)

**Comment by RobLoach** [comment]
This is fixed in 1.3.0.

**Comment by RobLoach** [comment]
Posted my findings here: https://github.com/libretro/RetroArch/issues/1921#issuecomment-164139099

**Comment by Kivutar** [comment]
Looks like this bug is fixed?

![capture du 2016-04-15 00-43-26](https://cloud.githubusercontent.com/assets/442722/14537865/201e40da-02a3-11e6-8d1f-61ec64609e99.png)

**Comment by RobLoach** [comment]
Going to close this. Feel free to create a new one if issue persists.

**Comment by orbea** [comment]
@RobLoach This seems more broken now than it was before...

**Comment by RobLoach** [comment]
@orbea Mind posting a screenshot of what you're running into?

**Comment by orbea** [comment]
@RobLoach 

![1](https://i.imgur.com/LCkrRz6.png)

So far I've tried removing my databases and downloading them again and removing my nes playlist and rescanning without any change. Its not just one game either...

**Comment by RobLoach** [comment]
Perhaps the menu is showing information, from the database, about the entry selected by the playlist entry name, rather than the CRC32 value in your file system.
