### ISSUE TITLE
follow the Stella emulator in preferring ROM Hunter's Atari 2600 set

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#223]
I would like to suggest that RetroArch designate the Atarimania ROM Hunter v11 set (torrentzipped) as the officially supported Atari 2600 ROM set.

1) From my perspective, this set is the closest to a No-Intro database that exists or may come to exist in the future. "ROM Hunter" themselves is involved in the No-Intro group from what I can tell.
2) This set is the officially supported set of the Stella emulator. The Stella folks use it for their own ROM database already. These ROMs work well with the Stella libretro core now and should continue to in the future.
3) The ROM Hunter set is widely available on the web from sites that are reputable and public, as well as being available from the major ROM torrent tracker.

I compiled a Lakka playlist for these ROMs in order to test them on the most recent two builds of Lakka, where they seem to work great: https://drive.google.com/open?id=0B4gWQ8g8Bzq3dHBrcXRHUDBrU3M

I also created a DIR2DAT in ClrMamePro: https://drive.google.com/open?id=0B4gWQ8g8Bzq3NnRrSW5xbk14eUE

**Comment by RobLoach** [comment]
As an alternative, we can merge the Atarimania set along-side No-Intro's.

**Comment by markwkidd** [comment]
@RobLoach there is not a No-Intro Atari 2600 set.

I read somewhere that there are some CRCs in the database for Atari 2600 but, at least to me, they're not being used and they're inferior to the official Stella set (Atarimania)

**Comment by RobLoach** [comment]
I meant merge Atarimania in with the Good2600, which we're using now.

1. Move `dat/Atari - 2600.dat` to `metadat/goodtools/Atari - 2600.dat`
2. Add Atarimania's DAT to `dat/Atari - 2600.dat`

**Comment by markwkidd** [comment]
Sorry I did misread you earlier. If it's possible for the Good2600 and the Atarimani set to coexist in the database that does seem like a good outcome.

**Comment by RobLoach** [comment]
Do you have Atarimania's .dat file around? We could add it in.

**Comment by markwkidd** [comment]
Would this work?

[Atari 2600 - Rom Hunter V11 TorrentZipped Original ROMs.zip](https://github.com/libretro/libretro-database/files/400677/Atari.2600.-.Rom.Hunter.V11.TorrentZipped.Original.ROMs.zip)

**Comment by markwkidd** [comment]
Cool! 

At my next opportunity I'll look into what it will take to rename the Stella official snapshots to fit RetroArch thumbnail convention in order to start building up a thumbnail set.
