### ISSUE TITLE
NEC - PC Engine CD RetroArch XMB Support

### ISSUE THREAD

**Issue by shinra358** [libretro/libretro-database#234]
PC Engine CD games don't show up in the RetroArch XMB when scanned for. I would like to request this. There's no dat for it in the thumbnails folder.

**Comment by RobLoach** [comment]
Which Core does this use?

**Comment by shinra358** [comment]
Right now I'm using mednafen_pce_fast_libretro for this.

**Comment by RobLoach** [comment]
Does it work by loading Redump's .cue files?

**Comment by shinra358** [comment]
The games work in the xmb and with loading the cues manually. There are just no graphics or xmb icons showing up for them (just black squares). Haven't tried loading redump's particular cue sheets.

**Comment by RobLoach** [comment]
Working with [Redump](http://redump.org/)'s NEC PC Engine CD - TurboGrafx-CD? Just confirming.

**Comment by RobLoach** [comment]
Added Redump. Do you know where another DAT for PC Engine CD/Turbografx-CD is? Looks like there are a few missing (`Loom (USA)`, etc).

**Comment by cudencuden** [comment]
downloaded NEC - PC Engine CD / TurboGrafx-CD 20160731 15-07-53 from redump..only Loom (Japan) version 3 is listed

**Comment by shinra358** [comment]
Here is one but I don't have an account to see if that is the USA version or not:
http://romshepherd.com/index.php?topic=1906.0

**Comment by xTMODx** [comment]
just checked a few sets and found it on the trurip dat
http://database.trurip.org/index.php?page=mnu-Database-DAT-List

**Comment by RobLoach** [comment]
Should be in the latest databases. May need to update your libretro info files too. Mind testing?

**Comment by shinra358** [comment]
Whatever NEC - PC-FX folder is, that doesn't have a dat. Also, the pc engine cd folder has the supergraphx dat instead of a pc engine cd dat.

I've scanned for games and the games don't come up for pc engine cd.

**Comment by RobLoach** [comment]
Found that Trurip overrides some of the CRCs. Made an issue: https://github.com/RobLoach/libretro-nec-pc-engine-cd-turbografx-cd/issues/1 .

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/commit/88382f2d70e53b3a15c7f79414809ca66d2d1c61 should fix this.

**Comment by RobLoach** [comment]
The RDBs are in now, closing this. Feel free to create a new one if it's still problematic. Should work with CUE files from TOSEC, Redump or Trurip.
