### ISSUE TITLE
GoodTools

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#243]
Add the GoodTools DATs. Need to convert from the Tools, to a DAT. Anyone willing to do that?

**Comment by zandrorev** [comment]
From the license.txt:

>   You are NOT authorized to reverse engineer or otherwise extract the
>   database of names included inside the GoodTools. This includes 
>   generating databases for other renaming programs.

I suggest you look into the MAME Software Lists (formerly managed under the MESS banner), as there is significant crossover in provided game information, it's more fleshed out meta-wise, and they had the GoodTools author's support in developing some of their dats.  But do check their license for potential usage restrictions.

**Comment by RobLoach** [comment]
Agreed. GoodTools is quite old, and we don't want to go against the license.
