### ISSUE TITLE
Sony - PlayStation DAT

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#249]
@Kivutar at https://github.com/libretro/Lakka/issues/456 requested having PlayStation use [Redump](http://redump.org/). Rebuilt [Sony - PlayStation.dat](https://github.com/libretro/libretro-database/files/425093/Sony.-.PlayStation.dat.txt) with redump, [TOSEC](http://www.tosecdev.org/), and [trurip](http://trurip.org/) over at [libretro-dats](https://github.com/robloach/libretro-dats).

Get the following error, due to metadata missing CRC keys:
```
=== Building Sony - PlayStation ===
Parsing dat file '/home/rob/Documents/libretro-super/retroarch/media/libretrodb/dat/Sony - PlayStation.dat'...
Parsing dat file '/home/rob/Documents/libretro-super/retroarch/media/libretrodb/metadat/analog/Sony - PlayStation.dat'...
missing match key 'rom.crc' in one of the entries
```

We could either remove all the serial-dependent metadata, or somehow add the CRCs to them somehow. Thoughts?

@Kivutar said...

> I'd say we remove the metadata, and we base all on the new dat.

Here's the complete DAT: [Sony - PlayStation.dat](https://github.com/libretro/libretro-database/files/425093/Sony.-.PlayStation.dat.txt)

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/pull/251

**Comment by azoreseuropa** [comment]
Does Sony _ Playstation.dat changed ? I noticed here and other Sony - Playstation.dat are different now. I am confused which one ?

**Comment by RobLoach** [comment]
They're all combined into the RDB file when building.

**Comment by azoreseuropa** [comment]
> They're all combined into the RDB file when building.

Okay.. then I not used this file here ? Which is the correct one so I can check ?

**Comment by RobLoach** [comment]
All Sony - Playstation.dat files are combined, so check all of them?

This one has the serials:
https://github.com/libretro/libretro-database/blob/master/dat/Sony%20-%20PlayStation.dat

**Comment by azoreseuropa** [comment]
Thanks

**Comment by azoreseuropa** [comment]
> All Sony - Playstation.dat files are combined, so check all of them?
> 
> This one has the serials:
> https://github.com/libretro/libretro-database/blob/master/dat/Sony%20-%20PlayStation.dat

I found an odd about this .dat. I rename according to .dat for Rockman 5 PSX for both bin and cue and inside cue to rename it as well. Scan it and it doesn't work. Rockman 5 doesn't appeared but.....

I decide to rename it to
Rockman 5 - Blues no Wana! (Japan).bin andRockman 5 - Blues no Wana! (Japan).cue and inside the .cue as well. And rescan it. **VOILA! It works.** 

Error or bug or something ? 

All Rockman 1-4 and 6 are working fine using the end starting with [Complete Works] (Japan) according to your dat to match and Rockman 5 which I rename it my own way works only starting with (Japan) but not working with end starting with [Complete Works] (Japan) at all. 

Why ?

Please verify ?
