### ISSUE TITLE
[GBA] Watch out with quotation marks inside description

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-database#257]
I was getting the message "missing match key 'rom.crc' in one of the entries", the issue was in this entry:

```
game (
	name "Mega Man Battle Network 3 - Blue Version (USA) (Virtual Console)"
	description "Mega Man Battle Network 3 - Blue Version (USA) (Virtual Console) (From Wii U DL "Mega Man Battle Network 3 - Blue Version (USA) (GBA) (Virtual Console)")"
	rom ( name "Mega Man Battle Network 3 - Blue Version (USA) (Virtual Console).gba" size 8388608 crc EDD7106E md5 41FABD164C0E4102C0187329E9F52C5C sha1 6E30310F3994803E56170F6D67C5F154A5D91CCB )
)
```

There are 2 quotation marks (") inside the description, it seems it bugs c_converter. Changed them with ('), it's building the rdb fine now

See 207aaf8

**Comment by sergiobenrocha2** [comment]
@RobLoach in the case you update this dat in the future. I reported at dat-o-matic.

**Comment by RobLoach** [comment]
@sergiobenrocha2 :dancers: :dancer: :dancers:

**Comment by RobLoach** [comment]
Latest DAToMatic fixes this.

**Comment by RobLoach** [comment]
Nice investigation work! :+1:
