### ISSUE TITLE
Rename "Panasonic - 3DO" to either "3DO" or "3DO - 3DO"

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#258]
The new 3DO database (awesome!) is named "Panasonic - 3DO." While Panasonic is one of the companies who did buy a license to produce 3DO consoles, it was not a Panasonic platform and they were not the only company to produce 3DOs.

In order to follow the pattern set by other systems' databases, I suggest renaming this to "3DO". That naming scheme would match the ScummVM and Uzebox databases.

**Comment by RobLoach** [comment]
`The 3DO Company - 3DO`

**Comment by markwkidd** [comment]
Arg. I got it wrong.

**Comment by RobLoach** [comment]
@markwkidd That okay wth you? We've put together a PR for it.

**Comment by markwkidd** [comment]
Definitely, thank you.
