### ISSUE TITLE
general strategy for rom db

### ISSUE THREAD

**Issue by Kallin** [libretro/libretro-database#263]
I've been thinking about getting involved in libretro development, and one piece that interest me in particular is the management of the rom DB. I haven't been able to find anything discussing the approach that is being used to build out the DB, but looking at some commits it seems that it's pretty much a continuous process of adding new entires to the dat files. Is that a valid observation?

I've been trying to dig and see what exists as far as open APIs/DBs of all ROMs along with crcs/shas etc. and there isn't much. If such a service existed, it would seem ideal to simply consume that service. 

I wonder if there is any value in creating a stand-alone project to accomplish that, or to work with something like thegamesdb.net to enhance their db with fields needed for something like libretro. 

Just curious what people's thoughts were here on this subject. A canonical listing of all roms ever released, consumable by machine, would be fantastic!

**Comment by RobLoach** [comment]
I had put together a small project that merges the [TOSEC](http://tosecdev.org), [Redump](http://http://redump.org/), and [Trurip](http://trurip.org/) DATs:
https://github.com/robloach/libretro-dats

Would like it to grow to help facilitate maintaining libretro-database. [No-Intro's Datomatic](http://datomatic.no-intro.org/) is the other source that's used.

**Comment by RobLoach** [comment]
Going to close this for now. Feel free to create another issue, or comment if you have any questions.
