### ISSUE TITLE
Playlist Sega CD, Saturn and Dreamcast...

### ISSUE THREAD

**Issue by alexb3d** [libretro/libretro-database#272]
Hello RobLoach
I would like to help create the playlist Sega CD, Saturn and Dreamcast.
How can I help you?
- Darkwater is a good set for Sega CD and Saturn.
- Most TOSEC (CUE+ISO+MP3) isos are not compatible with beetle-saturn.

**Comment by RobLoach** [comment]
> Darkwater is a good set for Sega CD and Saturn.

Do you have a DAT for it?

> Most TOSEC (CUE+ISO+MP3) isos are not compatible with beetle-saturn

Saturn emulation is surprisingly behind. Should we remove TOSEC from the DAT?

**Comment by AlexB3D** [comment]
> Do you have a DAT for it?

Yes, they are here: https://yadi.sk/d/_Kp8yfMlv68CS
(In pleasuredome.org.uk you get everything).

> Saturn emulation is surprisingly behind.

Mednafen/Beetle Saturn is incredible. Pixel perfect emulator. I tested 105 games and everyone runs perfect. Identical to the console. Except two, Virtua Fighter and Virtua Fighter Remix.
Here the list of games I've tried: http://libretro.com/forums/showthread.php?t=5817&page=8&p=47089#post47089

> Should we remove TOSEC from the DAT?

TOSEC is disorganized, has erroneous names, formats are CUE+ISO+WAV/MP3. It is not compatible with Beetle, nor Yabause... I think it's better to remove it.

**Comment by RobLoach** [comment]
> Yes, they are here: https://yadi.sk/d/_Kp8yfMlv68CS

Are they available from a public source? Is there a license behind the DAT data? Can we distribute it? Essentially the steps would be...

1. Add them to a place where the .zip can be automatically downloaded
2. Add the Makefile script to download/unzip it in https://github.com/robloach/libretro-dats
3. Add the Darkwater DAT files to [dats.json](https://github.com/RobLoach/libretro-dats/blob/master/dats.json)
4. Re-build the new Saturn DAT
5. Push a PR to libretro-database

**Comment by cudencuden** [comment]
that darkwater set is from 2011... where as redump is way more recent

**Comment by AlexB3D** [comment]
> Are they available from a public source?

The official site has not. www.darkwater.info
As cudencuden says, it is from 2011, is obsolete. Best ignore.

He had proposed Darkwater because it has isos that Redump not have. But Trueiso if available.
Among Redump and Truerip have all ISOs Sega Saturn and Sega-CD.

Now...
How the playlist is updated RetroArch?
I have installed RetroArch Testing on Ubuntu LTS

**Comment by RobLoach** [comment]
Added the Saturn DAT, do you have any other DATs from Darkwater?

**Comment by alexb3d** [comment]
Ok :) 
Only those. The other projects do not get anything, seem abandoned.

**Comment by markwkidd** [comment]
What format of Mega CD / Sega CD ROMs did the database wind up supporting?

**Comment by RobLoach** [comment]
I believe having the Serial scanning in place skips the CRC Check.

**Comment by markwkidd** [comment]
Hmm. I'm not having any luck generating a playlist from a set of Redump-verified Sega CD ROMs.

I'm not clear on how serial scanning works, perhaps.

I am starting with a set that organizes the ROMs as individual folders, each of which contains a .cue and one or more .bin files. No result.

I tried zipping one of these folders and scanning that zip. No result.

I saw some reports on the forum that it might work to zip only the .cue file. No result.

When I open up the .cue files I see that they all begin with this line: `CATALOG 0000000000000`

Is that the serial number?

**Comment by alexb3d** [comment]
markwkidd See message 4 of RobLoach.
"5. Push a PR to libretro-database"

I do not know what is "PR" :(

**Comment by RobLoach** [comment]
> I do not know what is "PR" :(

[Pull Request](https://help.github.com/articles/about-pull-requests/) :wink:

**Comment by alexb3d** [comment]
> I'm not having any luck generating a playlist from a set of Redump-verified Sega CD ROMs.

Ok :) What is the repo indicated to do the PR? or, It is done?

ps: I'm a little lost, excuse my (google) English.

**Comment by markwkidd** [comment]
So it seems like right now the scanner does not support Redump Sega CD ROMs. (I've tried scanning with a 12/09 Lakka nightly and a 12/17 Windows nightly by the way)

@RobLoach do you think this means that Redump ROMs are not working with the playlist scanner in general, or is there a chance that it is only affecting Sega CD dumps? This is the only set of ROMs I have worked with so far that is sourced from optical media but within the next week or so I should have access to some Redump Turbografx CD ROMs to test as well.

In terms of how this might have changed, the only thing I have found referring to changes in RA serial scanning is that there were some changes committed as a result of the discussion in this issue (scroll down to the last few posts): https://github.com/libretro/Lakka/issues/390

**Comment by gretel** [comment]
any update on this? i love `sega cd`.

**Comment by gretel** [comment]
@alexb3d did it get fixed? or why the close?

**Comment by alexb3d** [comment]
> @alexb3d did it get fixed? or why the close?
Sorry I did not answer, it is a message from 2016, I thought you had already found out.
The sets are up to date, but it may be better to add the lists with the option "Import Content / Scan File"
It is accurate and much faster.

[libretro youtube](https://www.youtube.com/watch?v=BWgUui57CRk)

**Comment by gretel** [comment]
> Sorry I did not answer, it is a message from 2016, I thought you had already found out.
> The sets are up to date, but it may be better to add the lists with the option "Import Content / Scan File"
> It is accurate and much faster.
> 
> [libretro youtube](https://www.youtube.com/watch?v=BWgUui57CRk)

cool thanks, will do.

**Comment by alexb3d** [comment]
> cool thanks, will do.

I told you Scan File, no, I was wrong.
It is "Manual Scan". You see it in the video from minute 3:46
