### ISSUE TITLE
Remove BIOS from DAT files?

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#28]
Not having the BIOS files in the No-Intro dats would mean it wouldn't list them as playable. Might improve the UI a bit, since there is no instance where a user would "play" a BIOS file.

Datomatic can build the DAT without the BIOS for us.

**Comment by RobLoach** [comment]
Naw.

**Comment by sergiobenrocha2** [comment]
Is it not easier to tell people to have a different folder for BIOS?

**Comment by RobLoach** [comment]
They are out of the day files now. Added a libretro bios dat specifically to just check them.
