### ISSUE TITLE
Playstation to PlayStation?

### ISSUE THREAD

**Issue by lasers** [libretro/libretro-database#289]
I set up core overrides for my bios to stay organized. I added some more bios, rebuilt, and extracted. I looked into this when I couldn't load the game. Should Playstation be PlayStation?
```
game (
        name "Sony - Playstation"
        description "Sony - Playstation"
)
```
For what it's worth, the cheat directories aren't named accurately either.

**Comment by RobLoach** [comment]
Good catch.
