### ISSUE TITLE
Different directory structure for cheats?

### ISSUE THREAD

**Issue by lasers** [libretro/libretro-database#292]
**Current cheat directories**
Nothing wrong with that. 
```
cheats
├── Game Boy
│   ├── Game Genie
│   ├── GameShark
│   └── Xploder
├── Game Boy Advance
│   └── CodeBreaker
├── Games
├── Genesis
│   └── Pro Action Replay
├── Nintendo Entertainment System
│   ├── Game Genie
│   └── Pro Action Replay
├── PlayStation
│   ├── Game Busters
│   ├── GameShark
│   └── Xploder
├── Sega Game Gear
│   ├── Game Genie
│   └── Pro Action Replay
├── Sega Master System
│   └── Pro Action Replay
├── Sega Saturn
│   └── GameShark
└── Super Nintendo
    ├── Game Genie
    └── Pro Action Replay
```
**My proposal**
Mirror the structure from database.

```
cheats
├── Games
├── Nintendo - Game Boy
│   ├── Game Genie
│   ├── GameShark
│   └── Xploder
├── Nintendo - Game Boy Advance
│   └── CodeBreaker
├── Nintendo - Nintendo Entertainment System
│   ├── Game Genie
│   └── Pro Action Replay
├── Nintendo - Super Nintendo Entertainment System
│   ├── Game Genie
│   └── Pro Action Replay
├── Sega - Game Gear
│   ├── Game Genie
│   └── Pro Action Replay
├── Sega - Master System - Mark III
│   └── Pro Action Replay
├── Sega - Mega Drive - Genesis
│   └── Pro Action Replay
├── Sega - Saturn
│   └── GameShark
└── Sony - PlayStation
    ├── Game Busters
    ├── GameShark
    └── Xploder
```

**My bestest proposal**

Mirror the structure from database.
Fix possible gotchas.
Merge cheat directories for easier navigation/browsing.
- Mixed roms uses (Region) in their files ; cheat files can use (Brand) in their files.
- Avoid wasting time searching for cheats that does not exist.
- Avoid wasting time searching for cheats in wrong folder/brand/device.
- Easier comparing viable cheats between brand/device for a same game.
- Easier finding...  when searching.
- Easier listing... despite odd filenames due to...

  _... different numbering style, different naming style, different lettercase..._
  _... too many spaces, dashes, or words..._
  _... lack of spaces, dashes, or words..._
  _... etc..._
- If merged, multiple (multi and single) directories would be eliminated. This would mean no navigating furthur than a game system.

**Rough example**

```
- Tetris (Game Genie).cht
- Tetris 2 (Game Genie).cht
- Tetris 3 (GameShark).cht
- Tetris II (CodeExampler).cht
- Tetris III (CodeExampler).cht
- Tetris The 3rd Edition (CodeExampler).cht
- Tetris Tournament Edition (GameShark).cht
- TetrisforRetroArch (Game Genie).cht
```
**A gist of real example** 
https://gist.github.com/lasers/04374a96492f39dadcb3633f5fe6998e

**Possible Gotcha**
Game Busters to Game Buster? http://gamehacking.org/wiki/Game_Buster
Pro Action Replay to Action Replay? https://en.wikipedia.org/wiki/Action_Replay
Code Breaker to Codebreaker? (not sure) https://en.wikipedia.org/wiki/Code_Breaker

**Comment by RobLoach** [comment]
Feel free to submit a Pull Request to make this change. Seems like it would clean it up a bit.

**Comment by lasers** [comment]
https://github.com/libretro/libretro-database/pull/294
