### ISSUE TITLE
Incorrect filenames in cheats files, 2nd double

### ISSUE THREAD

**Issue by ofry** [libretro/libretro-database#311]
This issue related to #308 and PR #309 

When I trying to update cheats via Online Updater,

this task fails on extraction step.

RetroArch [ERROR] :: Failed to deflate C:\retroarch\cheats\Sega - Mega Drive - G
enesis/Tiny Toon Adventures - Acme All-Stars (USA< Europe, Korea) (Action Replay
).cht.

**Comment by lasers** [comment]
Nice catching my shift-typo.  `(USA< Europe, Korea)` should be `(USA, Europe, Korea)`.
