### ISSUE TITLE
RetroCheat -- A dedicated cheat database.

### ISSUE THREAD

**Issue by lasers** [libretro/libretro-database#320]
Here's a thought. Put together a dedicated cheat database/website and call it RetroCheat.

I would like for everybody to start considering cheat codes not necessarily as scarce information and for the community to come up with a system to deal with cheat codes in the same way we do with the the game roms right now.

The community could start with poking around, testing stuffs, and enjoy  themselves playing something different... along with verification, readonly permissions, documentations for online/offline options, compressed fullset archives, and an option to view/change/download cheats in or to their preferred languages, and more bullshit coming off my head and whatever else you can think of... for our future gamers, our old gamers, and for everybody out there.

Do we have a good cheat database somewhere? Lot of cheat websites sucks right now and we shouldn't have to hunt around, scrap websites, and whatnot just to get a fullset cheats for a system. Is there even any fullset cheats? We can slowly make one ourselves if it does not exist. We don't have to be the best one as some new group may make a better one.

Also, it only takes one typo to compromise a cheat code. :sob: 

| system | support | scrape | sort | star |
| --- | --- | --- | --- | --- |
| Atari - 2600 | &#x1F34A; | &#x1F345; |  |  |
| Atari - 5200 | &#x1F34A; | &#x1F345; |  |  |
| Atari - 7800 | &#x1F34A; | &#x1F345; |  |  |
| Atari - Jaguar | &#x1F34A; | &#x1F345; |  |  |
| Atari - Lynx | &#x1F34A; | &#x1F345; |  |  |
| Bandai - WonderSwan Color | &#x1F34A; | &#x1F345; |  |  |
| Bandai - WonderSwan | &#x1F34A; | &#x1F345; |  |  |
| Cave Story | &#x1F34A; | &#x1F345; |  |  |
| DOOM | &#x1F34A; | &#x1F345; |  |  |
| FB Alpha - Arcade Games | &#x1F34A; | &#x1F345; |  |  |
| Game and Watch | &#x1F34A; | &#x1F345; |  |  |
| GCE - Vectrex | &#x1F34A; | &#x1F345; |  |  |
| Lutro | &#x1F34A; | &#x1F345; |  |  |
| Magnavox - Odyssey2 | &#x1F34A; | &#x1F345; |  |  |
| MAME2003 | &#x1F34A; | &#x1F345; |  |  |
| MAME | &#x1F34A; | &#x1F345; |  |  |
| Microsoft - MSX | &#x1F34A; | &#x1F345; |  |  |
| Microsoft - MSX2 | &#x1F34A; | &#x1F345; |  |  |
| NEC - PC Engine - TurboGrafx 16 | &#x1F34A; | &#x1F345; |  |  |
| NEC - PC Engine CD - TurboGrafx-CD | &#x1F34A; | &#x1F345; |  |  |
| NEC - PC Engine SuperGrafx | &#x1F34A; | &#x1F345; |  |  |
| NEC - PC-FX | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Famicom Disk System | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Game Boy Advance (e-Cards) | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Game Boy Advance | &#x1F34F; | &#x1F34F; | &#x1F34F; |  |
| Nintendo - Game Boy Color | &#x1F34F; | &#x1F34F; | &#x1F34F; |  |
| Nintendo - Game Boy | &#x1F34F; | &#x1F34F; | &#x1F34F; |  |
| Nintendo - GameCube | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Nintendo 64DD | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Nintendo 64 | &#x1F34F; | &#x1F345; |  |  |
| Nintendo - Nintendo DS (Download Play) (BETA) | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Nintendo DS Decrypted | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Nintendo Entertainment System | &#x1F34F; | &#x1F34F; |  |  |
| Nintendo - Sufami Turbo | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Super Nintendo Entertainment System | &#x1F34F; | &#x1F34F; | &#x1F34F; |  |
| Nintendo - Virtual Boy | &#x1F34A; | &#x1F345; |  |  |
| Nintendo - Wii | &#x1F34A; | &#x1F345; |  |  |
| Quake1 | &#x1F34A; | &#x1F345; |  |  |
| RPG Maker 2000 | &#x1F34A; | &#x1F345; |  |  |
| RPG Maker 2003 | &#x1F34A; | &#x1F345; |  |  |
| ScummVM | &#x1F34A; | &#x1F345; |  |  |
| Sega - 32X | &#x1F34A; | &#x1F345; |  |  |
| Sega - Dreamcast | &#x1F34F; | &#x1F345; |  |  |
| Sega - Game Gear | &#x1F34F; | &#x1F34F; | &#x1F34F; |  |
| Sega - Master System - Mark III | &#x1F34F; | &#x1F34F; | &#x1F34F; |  |
| Sega - Mega Drive - Genesis | &#x1F34F; | &#x1F34F; | &#x1F34F; |  |
| Sega - Mega-CD - Sega CD | &#x1F34A; | &#x1F345; |  |  |
| Sega - NAOMI | &#x1F34A; | &#x1F345; |  |  |
| Sega - PICO | &#x1F34A; | &#x1F345; |  |  |
| Sega - Saturn | &#x1F34F; | &#x1F345; |  |  |
| Sega - SG-1000 | &#x1F34A; | &#x1F345; |  |  |
| Sinclair - ZX 81 | &#x1F34A; | &#x1F345; |  |  |
| Sinclair - ZX Spectrum +3 | &#x1F34A; | &#x1F345; |  |  |
| Sinclair - ZX Spectrum | &#x1F34A; | &#x1F345; |  |  |
| SNK - Neo Geo Pocket Color | &#x1F34A; | &#x1F345; |  |  |
| SNK - Neo Geo Pocket | &#x1F34A; | &#x1F345; |  |  |
| Sony - PlayStation Portable | &#x1F34F; | &#x1F345; |  |  |
| Sony - PlayStation | &#x1F34A; | &#x1F345; |  |  |
| The 3DO Company - 3DO | &#x1F34A; | &#x1F345; |  |  |
| Uzebox | &#x1F34A; | &#x1F345; |  |  |

| maybe | no | yes | star |
| --- | --- | --- | --- |
| &#x1F34A; | &#x1F345; | &#x1F34F; | &#x1F31F; |

This might be better suitable for wiki? Also, can somebody start scrapping something? 😃

**Comment by fr500** [comment]
It should be like RetroAchievements, and it should have a function to download the cheats from the site on the fly.

I think it's a good idea. But no scraping. The current cheat database is a mess because it was a scrapped set and it blows. 

It should work like achievements, ie. each entry in the database should have the ROM CRC it's intended for.

Maybe you can talk to the RetroAchievements people to try to setup a similar site, then @leiradel to add support to the frontend.

**Comment by lasers** [comment]
I renamed everything according to No-Intro naming conviction... except for `Sony - PlayStation`. The scrapper script somebody made strips lot of characters making it hard for me to decides sometimes as it definitely ate extra characters in some files. I tried my best cleaning up the mess. It definitely was a mess.

That's a pretty good idea to send codes on the fly to the users. They shouldn't have to do anything other than enabling `Achievements --> Verify unknown cheat codes` option.

We should scrap everything first before we can send some untested codes on the fly to the users... so they can verify stuffs? I think most codes would work... but if a cheat website were to shut down without a warning or to let users have a copy, then we'll have hard time. I want to try and scrap as much as possible, then deal with the aftermath.

From what I'm told, RetroArch isn't affiliated with RetroAchievements. I can try and ask them about this.

**Comment by fr500** [comment]
Well you mentioned setting up a site, that's why I mentioned them, I think copying their site and API would be a straightforward way to achieve this.

**Comment by lasers** [comment]
Yes. RetroArch also have a site, an emulator site along, buildbot, and many other things. Do you know if they have a Github page? It seems empty / abandoned. What's the history behind that? Are they now working behind closed git repositories? I'm just trying to avoid using RetroAchievement chat forum.

**Comment by leiradel** [comment]
@lasers no, the website owner, Scott, is just busy with other stuff, so work on emulators has stopped. He also wants to start to use RetroArch and its cores officially, but for that I have to iron out the remaining bugs with achievements, and implement a few features to make it really usable.

**Comment by lasers** [comment]
No reply from Scott for days. This chart is more suitable for wiki. Closing.
