### ISSUE TITLE
[FB Alpha] Update to 0.2.97.39 and TorrentZip

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-database#329]
this database(and probably others) really needs to be updated. its still based on 0.2.97.38 (torrentzipped) and the core for windows has already been updated to 0.2.97.39 meaning my updated cps2 roms cannot be imported to playlist which the reason why i like to use retroarch. 

also just for fun i made mame.78 neogeo romsets verified with clrmame-torrentzipped and crc never matches the ones in mame2003.rdb list aside from one rom, shocktra.zip and placed it FB Alpha - Arcade Games. i was in the impression that one purpose of rdb is for playlist names.

either the rdb should be updated to reflect core versions used in repository, or probably new a different method of scrapping zipped romsets in RA since it takes a long time scanning each file in the zip anyways when its rdb is only checking for the zips crc.

**Comment by markwkidd** [comment]
Related? https://github.com/libretro/libretro-database/issues/248

**Comment by cudencuden** [comment]
@RobLoach , @markwkidd , attached is the xml you would need..although it is FB Alpha 0.2.97.39 split

**Comment by RobLoach** [comment]
Is the FBA Core capable of running the rom file, or does it take the .zip file as its arguments? I don't know how it's set up, nor do I own any of the cartridges.

**Comment by retro-wertz** [comment]
fba core is same with mame cores in handling roms, need them as split zip set if you want to see/play all clones, else you play whatever filename the zip is(assuming correct crc and full set with parent files)

**Comment by markwkidd** [comment]
The ROMs don't have to be split, they can also be Non-Nerged. As long as they're not Merged.

For the historical MAME cores at least, I'm a staunch advocate of Non-Merged ROMs but these FBA sets still seem to be mostly in split format...

**Comment by retro-wertz** [comment]
ok.. so is the rdb will be based  on non-merged too?

**Comment by cudencuden** [comment]
@retro-wertz may be you can provide the xml/dat file for mame 0.78

**Comment by markwkidd** [comment]
If it's useful I can provide a non-merged MAME 0.78 XML dat. I have started a Dir2Dat on the Non-Merged "Reference Set" that ought to be finished within an hour or so. I'll post in this thread once it is, unless someone beats me to it. :)

**Comment by markwkidd** [comment]
Here is a Dir2Dat file for MAME 0.78 Non-Merged. This Dir2Dat has the BIOS files removed according to my understanding of libretro-database policy. I could also produce a version which includes the BIOS entries:

[MAME 0.78 Non-Merged with CHDs - No BIOS.txt ](https://github.com/libretro/libretro-database/files/491641/MAME.0.78.Non-Merged.with.CHDs.-.No.BIOS.txt) (change extension to .dat)

**Comment by retro-wertz** [comment]
so how are zip-based rom finalized? torrentzipped? torrent7z? in order to match the required crc with other rom-set users?

**Comment by markwkidd** [comment]
The crcs are based on a non merged, torrent zipper set and they include the CHD files for titles as appropriate.

If you search for mame 2003 reference set  (or just MAME 078 ROMs) you should find some info about the set. It's also the recommended MAME 2003 rom set for RetroPie.

**Comment by cudencuden** [comment]
fba should be based on split torrentzipped.... i think it's the most circulated version

**Comment by retro-wertz** [comment]
non-merged? looking at the repository, dat for mame and fba are full split-sets(and it requires to have sha-1 at least for rdb creation and to be valid i think).

**Comment by retro-wertz** [comment]
https://github.com/libretro/libretro-database/commit/b13a522bce9424b4f75d15ab86d1a1faef4cb279

**Mismatched CRC:**
-dmnfrnt.zip	size	22900742	crc	9b0e56c6	md5	4a8f9d5cadab666db0700b7929a4b689	sha1	70409eb10b047eef756481ef525def791faaecba
-dmnfrntpcb.zip	size	5905678	crc	62d32872	md5	3d17553bbc8b6c84f4d4975d051056f9	sha1	09eca590afdd000f86dd7dd87acad6e669980d71
-svg.zip	size	26395224	crc	229f5a7b	md5	febc81d81ef480cf83510c23c2ccdf8f	sha1	90038593555412b40cd790e67e73eff376f81ea7
-svgpcb.zip	size	6252676	crc	682e2d3a	md5	28ef0fc419aaf2b1948b4828abe2fb4c	sha1	b97e7082b7e736102d9aa0a75ba62e626ac30fde

**Missing ROM:(these were manually added to source a few commits back):**
dangar.zip	size	167002	crc	73dba0d7	md5	fc130a4c79b1e00527ce4021750b0775	sha1	ca49c2cd498a59ede92642711200d09b80f08721
dangara.zip	size	85289	crc	1ed61fa6	md5	b2849c1a1923474512b9611b896cbba1	sha1	a07583a8c3d0104637e3ba8c4fc276d9848d4f6f
dangarb.zip	size	105047	crc	3c52d9b8	md5	504ff2081150fc73876d548d43cbf429	sha1	1f91fa78fd78024a0b9d6cebc41df7938045c45d
dangarbt.zip	size	166126	crc	33a8123f	md5	3a580aa08cf6e93cc72ad8875542bd9e	sha1	8cc2624d8d14a5ea3d9a5b4bc2189099411d1540
galivan.zip	size	157876	crc	b09de5dd	md5	cfbf8c0e86f0c899ea8e52c82b08bb9d	sha1	6df2de8c2225245bdda8894adfd22225ec16c30a
galivan2.zip	size	29296	crc	b4bf7839	md5	34483c1504d7eecd8dbc202491723362	sha1	95bb2691c9f70748eb47b49ab07cdc5c0e775870
galivan3.zip	size	29294	crc	c07528ac	md5	d364bf7450d375a04b1b42349befb762	sha1	d9a26d32bac0f232ad8161af8298058234052899
ninjemak.zip	size	219787	crc	a6d62528	md5	00ec58d18b5efc4bc2335f6932f531e1	sha1	cbe53ea7f93e5ff597b56ec55880730bad91fc33
youma.zip	size	55977	crc	3242fc02	md5	cb1ae450e09b5b7098889298e3faac59	sha1	b3c6bae860444649328efbc3e6d4ed726e3c5a93
youma2.zip	size	89267	crc	9e33a65c	md5	ace295b2624b4894dbb73cceefa8778e	sha1	4756de8ad5b3c17ffb25a846f5f0c7872d9f7d42
youmab.zip	size	231884	crc	6ca9d3f2	md5	563c776e12b94f65cc14c681b61776b9	sha1	966e4451e7342d8633e65713770ab7b83c970749
youmab2.zip	size	231559	crc	65445f7c	md5	1b51e1805dc153662e0c99b229072ab5	sha1	57cd9a79cd69f4a9efe9ae2ceb89ef4bbbe567ce

**Comment by Tatsuya79** [comment]
Scanning a 0.2.97.39 split set I'm missing most cps2 games too with current database.
Got 3828 matches for 4361 zip scanned.

**Comment by RobLoach** [comment]
How were these ZIPs created? What is the DAT based off of? While I can run the games, I can't scan them. Could we adopt TorrentZip for compression?
