### ISSUE TITLE
Nintendo - Game & Watch

### ISSUE THREAD

**Issue by lasers** [libretro/libretro-database#330]
I first came here to mention `Playstation to PlayStation?` issue. Now, I'm sharing my finding that `Game and Watch` is just accurate as `Playstation`. If we wanted `Sony - PlayStation`, then we might want `Nintendo - Game & Watch` too.

Was it intentional to use `and` instead of `&` because it wasn't possible to do that before and was done intentionally to support all platforms/filesystems? 

I am asking about this now because RetroArch recently implemented character-skipping for the thumbnails. I wonder if the team would like to support database too even if it's only one system right now?  And whole bunch of cheats?

_Note:_ It might be terrible idea to use it on cheats, but not `Nintendo - Game & Watch`.

**Comment by RobLoach** [comment]
We just switched `&` characters to `_` in the thumbnails. Could we leave the `and` to keep cross-platform filenames working? `Game _ Watch` doesn't look as appealing.

**Comment by lasers** [comment]
Well... If you looked into it, you'll find that it's a brand name and not two different things. They named it that way for everything and even made a guy too. `Mr. Game & Watch`.
https://en.wikipedia.org/wiki/Game_&_Watch
http://www.mariowiki.com/Game_&_Watch

RetroArch does not make games so you guys don't have any saying in `&` filenames... but RetroArch do offer playlists, thumbnails, assets, cheats, etc.. so you guys do have saying in this one... That's why I asked... to try and make it more accurate whilst stay friendly with all platforms. I agree that `Game _ Watch.*` looks ugly. It's just for this one. As ugly as it may be.

I was pondering about cheat codes. If there are some platforms that might skip some 186 cheat codes because of `&` alone, then RetroArch might want to rename those to `_` too? I don't know what `&` won't work with. 

Wii? Nintendo 3DS? PS3? Maybe Xbox360? The `&` works fine here for Vita.

**Comment by lasers** [comment]
@RobLoach Have you looked into this yet? Thoughts?

**Comment by RobLoach** [comment]
The database name for [gw_libretro.nfo](https://github.com/libretro/libretro-super/blob/master/dist/info/gw_libretro.info) is "Game and Watch". The display name is "Game & Watch"... What's wrong with this?

You're suggesting we switch to "Game _ Watch" for the database name?

**Comment by lasers** [comment]
I think the correct name is 'Nintendo - Game & Watch', but that '&' will mess with lot of things. I'm suggesting that we rename it to `Nintendo - Game _ Watch` and have RetroArch replace that with a correct character just like thumbnails.

I don't know wherer `Game and Watch` came from... I'm pretty sure `Game and Watch` and `Nintendo - Game and Watch` (in assets) was just duplicates.

**Comment by RobLoach** [comment]
Would a good compromise be `Nintendo - Game and Watch`?

**Comment by lasers** [comment]
Yes. I can go with that. I don't know what your side was? To answer your question about display name, it will display "Game & Watch" for the core and "Game and Watch" for the playlist.

Everytime I scroll by "Game and Watch" (playlist), I internally recognize that the name is not accurate, feels like I'm just glancing at a knockoff name, is missing a name of manufacturer (as well as the '&' too). I don't load GW core much to see that display list. I could always remove the playlist, but that wouldn't help the libretro team at all with the bugs. :-)

I prefer "Nintendo - Game & Watch", but "Nintendo - Game and Watch" will be fine.

**Comment by lasers** [comment]
So I compared `Game and Watch.dat` or soon to be `Nintendo - Game and Watch.dat` with https://en.wikipedia.org/wiki/List_of_Game_&_Watch_games

_Note:_ This list is not perfect.

* 56 games total.
* 18 Nintendo games total.
* 38 Non-Nintendo games total.

<details>
<summary>List of 'Nintendo - Game and Watch' games</summary>

```
miss ---- "Ball (Nintendo)"
miss ---- "Flagman (Nintendo"
miss ---- "Helmet (Nintendo)"
miss ---- "Lion (Nintendo)"
desc "Parachute (Nintendo, Wide Screen)"
miss ---- "Octopus (Nintendo)"
miss ---- "Popeye (Nintendo)"
miss ---- "Chef (Nintendo)"
desc "Mickey Mouse (Nintendo, Panorama Screen)"
desc "Egg (Nintendo, Wide Screen)"
desc "Turtle Bridge (Nintendo, Wide Screen)"
miss ---- "Fire Attack (Nintendo)"
desc "Snoopy Tennis (Nintendo, Wide Screen)"
miss ---- "Oil Panic (Nintendo)"
desc "Donkey Kong (Nintendo, Multi Screen)"
desc "Donkey Kong Jr. (Nintendo, Panorama Screen)"
miss ---- "Mickey & Donald (Nintendo)"
miss ---- "Green House (Nintendo)"
desc "Donkey Kong II (Nintendo, Multi Screen)"
desc "Mario Bros. (Nintendo, Multi Screen)"
miss ---- "Mario's Cement Factory (Nintendo)"
desc "Snoopy (Nintendo, Table Top)"
miss ---- "Rain Shower (Nintendo)"
desc "Lifeboat (Nintendo, Multi Screen)"
desc "Mario's Bombs Away (Nintendo, Panorama Screen)"
miss ---- "Pinball (Nintendo)"
miss ---- "Spitball Sparky (Nintendo)"
miss ---- "Crab Grab (Nintendo)"
miss ---- "Boxing (Nintendo)"
miss ---- "Donkey Kong 3 (Nintendo)"
desc "Donkey Kong Circus (Nintendo, Panorama Screen)"
miss ---- "Donkey Kong Hockey (Nintendo)"
miss ---- "Black Jack (Nintendo)"
miss ---- "Tropical Fish (Nintendo)"
miss ---- "Squish (Nintendo)"
miss ---- "Super Mario Bros. (Nintendo)"
miss ---- "Climber (Nintendo)"
miss ---- "Balloon Fight (Nintendo)"
miss ---- "Bomb Sweeper (Nintendo)"
miss ---- "Safebuster (Nintendo)"
miss ---- "Gold Cliff (Nintendo)"
miss ---- "Zelda (Nintendo)"

Extras, I think. (Diff manufactuers and/or wrong titles)

desc "Mickey Mouse (Nintendo, Wide Screen)"
desc "Snoopy (Nintendo, Panorama Screen)"
desc "Donkey Kong Jr. (Nintendo, Table Top)"
desc "Donkey Kong Jr. (Coleco)"
```
</details>
<details>
<summary>List of Non-'Nintendo - Game and Watch' games.</summary>

```
desc "Armor Battle (Mattel Electronics)"
desc "Banana (VTech, Time & Fun)"
desc "Baseball (VTech, Explorer Time & Fun)" <---- Nintendo's Ball ?
desc "Bomb Fight (VTech, Mini Time & Fun)"  <---- Nintendo's Balloon Fight ?
desc "Caccia al Ladro (VTech, Mini Time & Fun)"
desc "Cessate il Fuoco (VTech, Mini Time & Fun)"
desc "Chicky Woggy (VTech, Arcade Time & Fun)"
desc "Chicky Woggy (VTech, Electronic Tini-Arcade)"
desc "Condor (VTech, Time & Fun)"
desc "Crazy Chewy (VTech, Electronic Tini-Arcade)"
desc "Defendo (VTech, Explorer Time & Fun)"
desc "Dungeons & Dragons Computer Fantasy Game (Mattel Electronics, Arcade Action Series)"
desc "Engine Room (VTech, Explorer Time & Fun)"
desc "Escape (VTech, Time & Fun)"
desc "Explorers of Space (Elektronika)"
desc "Fowling (Elektronika)"
desc "Frog Boaster (Elektronika)"
desc "Galaxy II (Epoch)"
desc "Grab Man (unknown manufacturer, Game & Time)" <---- Nintendo's Crab Grab ?
desc "Hippo Teeth (VTech, Mini Time & Fun)"
desc "Hippo Teeth (VTech, Sporty Time & Fun)"
desc "Hot Line (VTech, Mini Time & Fun)"
desc "Hot Line (VTech, Sporty Time & Fun)"
desc "Las Vegas (Bandai, LCD Game Digital)"
desc "Monkey (VTech, Time & Fun)"
desc "Monkey Jump (VTech, Arcade Time & Fun)"
desc "Motor Cross (Queentex)"
desc "Pac Man (Tomytronic)"
desc "Pancake (VTech, Time & Fun)"
desc "Pirate (VTech, Time & Fun)"
desc "Roller Coaster (VTech, Explorer Time & Fun)"
desc "Safari (VTech, Time & Fun)"
desc "Sleep Walker (VTech, Time & Fun)"
desc "Sub Chase (Mattel Electronics)"
desc "Tennis Menace (VTech, Sporty Time & Fun)"
desc "Towering Rescue (Gakken, LCD Card Game)"
desc "Tron (Tomytronic)"
desc "Wild Man Jump (VTech, Electronic Tini-Arcade)"
```
</details>
.



If there are manufacturers totally unrelated to Nintendo that made their own LCD games, we could make an entry for them too (if the number of games are large enough).

There are lot of missing games from Nintendo, Non-Nintendo, and some other manufacturers too like `45. Penguin Land (Bandai Electronics, LCD Double Play)` from leiradel's link: http://www.madrigaldesign.it/sim/download.php for one.

Since I don't know where RetroArch got `Game and Watch.dat` from, it's hard to go on... I can at least say it's really not `Nintendo - Game and Watch` list at all... It's just a big `Game and Watch` dumpster fire right now. :fire:

**Comment by lasers** [comment]
@leiradel: I found the README. You're the author. Could you look into that madrigal link and see if there are any updates and/or games to be made so I can work with the latest?

I'm putting together _New!_ `Nintendo - Game and Watch.dat` [lasers/libretro-database/ngw.dat](https://github.com/lasers/libretro-database/blob/rename-gw/dat/Nintendo%20-%20Game%20and%20Watch%20(New).dat)

Without checking/counting the games, some of them might be coming from VTech so we could make a new database `VTech - Time & Fun`.

**Comment by RobLoach** [comment]
@lasers Why split the DAT? It's fine just as one.

**Comment by leiradel** [comment]
I thought it was one database port core?

Anyway, I work closely with MADrigal to convert and update his games to the gw core, meaning that all games should be up to date.

**Comment by lasers** [comment]
Leaving them together is akin to leave NES, Famicon Disk together.
Leave them together is akin to leave SNES, Sufami Turbo, Satellaview together.
Leave them... Ok, ok, ok. 

The only reason we have everything G&W (and not G&W) together in that DAT right now because the person behind that link put everything together for his simulator software.

I don't have problem with leaving everything together as I only played two GW games so far. This is for accurate / consistency. The accurate G&W list is 61 games or less... if somebody can find them all. We only have 18 in this merged dat. The rest is not Nintendo.

The other way is to put the name of manufacturers in game titles too along with a type of device. Works for you? The current dat is not accurate and is outdated as it only have 56 games total.
* First...`Nintendo - Game & Watch`
* Second... `VTech - Time & Fun`

... I'm finding more in our current dat ...
* `Unknown, Game & Time`
* `VTech, Arcade Time & Fun`
* `VTech, Sporty Time & Fun`
* `VTech, Time & Fun`
* `VTech, Explorer Time & Fun`
* `VTech, Mini Time & Fun`
* `Mattel Electronics, Arcade Action Series`

So I thought it might be good to make `VTech - Time & Fun`... I need to check first if they're systems or just series. There also are more that's not on this dat... like `Brandi`.

**Comment by lasers** [comment]
@leiradel I'm not seeing `45. Penguin Land (Bandai Electronics, LCD Double Play)` in the dat so I know not to check everything anymore and to ask you about that.

**Comment by leiradel** [comment]
> Leaving them together is akin to leave NES, Famicon Disk together.

I wasn't demanding anything, it was a genuine question.

> The only reason we have everything G&W (and not G&W) together in that DAT right now because the person behind that link put everything together for his simulator software.

He doesn't say all those games are Game & Watch, I think he call them *handhelds*.

> I don't have problem with leaving everything together as I only played two GW games so far. This is for accurate / consistency.

I like accuracy, and am **not** really worried if we'll end up with one or multiple databases.

> We only have 18 in this merged dat.

That's because I had only 18 games converted when I created the database. I remember having some issues with it so it ended up abandoned...

> EDIT: If we want to use something neutral... `Handheld Electronic Game` ?
> We can keep them together and rename it to Handheld Electronic Game according to https://en.wikipedia.org/wiki/Handheld_electronic_game?

I think that's the correct way to move forward.

**Comment by lasers** [comment]
@leiradel Everything I typed out was a response to @RobLoach's question. I pressed "Comment" 15 seconds after your comment. Sorry.

I don't know who named it Game & Watch, but after looking through lists, dats, etc... It's best not to go with any `Game & Watch` version... so it's good that we get into this. Get this over with, etc. 

>That's because I had only 18 games converted when I created the database. I remember having some issues with it so it ended up abandoned...

I compared the database again. Here's the list in case you want to try again.
* (12) Donkey Angler (Gakken, LCD Card Game)
* (45) Penguin Land (Bandai Electronics, LCD Double Play)
* (55) Tom & Jerry Popper (Gakken, LCD Card Game)

So we'll turn this `Nintendo - Game & Watch` dumpster fire (on accord of too many non-Nintendo games in first place) into `Handheld Electronic Game` (generic handheld playlist)?

That sounds good. We need an approval from somebody?

**Comment by leiradel** [comment]
> @leiradel Everything I typed out was a response to @RobLoach's question. I pressed "Comment" 15 seconds after your comment. Sorry.

No hard feelings, I just wanted to make that clear.

> I don't know who named it Game & Watch, but after looking through lists, dats, etc... It's best not to go with any Game & Watch version... so it's good that we get into this. Get this over with, etc.

It was me that created the core and named it Game & Watch :(

> I compared the database again. Here's the list in case you want to try again.

Sorry but, try what?

> That sounds good. We need an approval from somebody?

Not from me for sure, thanks for taking care of this.

**Comment by lasers** [comment]
> Sorry but, try what?

Convert the missing games.

> Not from me for sure, thanks for taking care of this.

Not a problem.

(To team): Can I get an approval from somebody on this? Handheld Electronic Game?

**Comment by leiradel** [comment]
> Convert the missing games.

I don't *try* to convert games, I *convert* them when the source code is available, which is not the case for the ones marked with S3.

**Comment by lasers** [comment]
If we're using Handheld Electronic Game, then we might want to consider adding `s` at the end... `Handheld Electronic Games` in the same way one would with `Videos` or `Games`.

I didn't put any manufacturer name on this... If we do, then we should leave that filename alone (no `s`), it could be something like...
`Various - Handheld Electronic Game`
`Multi - Handheld Electronic Game`
`Multiple - Handheld Electronic Game`
`(Your Idea Goes Here) - Handheld Electronic Game`
or just... `Handheld Electronic Games`.

I know this sounds stupid. I'll tell you why.

I'm looking at individual games right now. I would like to consider merging them all into one `Games` playlist too... so one game does not represent/take up a tab each anymore... and to opt for one tab instead.

This could mean we lost the custom artworks which I want to see if we can put that inside the list too with some code changes... then who know? Could it be possible to make `Named_Icons` for custom and/or merged gamed in the future? :-)

This should be for individual games. I have hard time deciding what to do with Doom... 85 games in the dat... it's likely to be only few games at most... but with Quake 1.dat, it's only 3 games in the dat.

- 2048 (None)
- DOOM (85)
- Dinothawr (1)
- Cave Story (2)
- Quake 1 (3)

```
Games
- 2048 (En)
- DOOM ?
- DOOM ?
- DOOM ?
- DOOM ?
- DOOM ?
- Dinothawr (En)
- Doukutsu Monogatari (Ja)
- Cave Story (En)
- Quake (v1.06)
- Quake Mission Pack 1: Scourge of Armagon
- Quake Mission Pack 2: Dissolution of Eternity
- New Port Game Goes Here In Future
- New Port Game Goes Here In Future
- New Port Game Goes Here In Future
- New Port Game Goes Here In Future
- New Port Game Goes Here In Future
```

P.S. Make a dummy playlist for 2048? To load 2048 right away in the playlist.
