### ISSUE TITLE
Update BIOS

### ISSUE THREAD

**Issue by lasers** [libretro/libretro-database#336]
Sega - Saturn
* Different file / hash.
* https://wiki.libretro.com/index.php?title=Beetle/Mednafen_Saturn

The 3DO Company - 3DO
* Excessive BIOS files ; Wiki says 4DO requires one.
* https://wiki.libretro.com/index.php?title=4DO

NEC - PC-FX
* Excessive BIOS file ; Wiki says Mednafen/Beetle PC-FX requires one.
* https://wiki.libretro.com/index.php?title=Beetle/Mednafen_PCFX

There be more. Do we want to keep it minimal or just throw everything we find in a list?

**Comment by RobLoach** [comment]
The one missing is...

Sega - Saturn - sega_100a.bin (MD5 sum: f273555d7d91e8a5a6bfd9bcf066331c)

Not sure where the extra ones came from. May have found them in different cores for the same systems, or within the source code?

**Comment by RobLoach** [comment]
Can't find `f273555d7d91e8a5a6bfd9bcf066331c` anywhere. Know the CRC/SHA1 values for it?

**Comment by lasers** [comment]
It's probably bad.

**Comment by lasers** [comment]
I found some more for Saturn. https://github.com/libretro/mame2014-libretro/blob/master/src/mess/drivers/saturn.c#L846

`sega_100a.bin crc f90f0089 sha1 3bb41feb82838ab9a35601ac666de5aacfd17a58`

We should remove likely a bad dump from this page.
https://wiki.libretro.com/index.php?title=Beetle/Mednafen_Saturn

And if you go in libretro-super, grep `ROMX_LOAD` to find that MAME loads so many roms. Does that mean this list is about to get big now? Mindblown.
