### ISSUE TITLE
PCFX bios 

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-database#345]
the pcfx.bios in database and info is an older one, it does not work and will just show black screen when used. the correct pcfx bios as recommended by mednafen has the following details:

 File: pcfx.bios (PC-FX BIOS version 1.00)
size: 1.00 MB (1,048,576 bytes)
CRC-32: 76ffb97a
   MD4: 89d5b457d3cd355f6e9fbdf5f72f027d
   MD5: 08e36edbea28a017f79f8d4f7ff9b6d7
 SHA-1: 1a77fd83e337f906aecab27a1604db064cf10074

**Comment by RobLoach** [comment]
Thanks @retro-wertz! Mind submitting a PR witht he fix? Would really appreciate it :+1:

**Comment by lasers** [comment]
I'm already on it.

**Comment by lasers** [comment]
Just a note. I'll add `fx-scsi.rom` eventually, but I can't find `pcfxga.rom`. It may not be supported anymore? Search results turned up nothing for me... Irrelevant file? 

https://github.com/libretro/mame2014-libretro/blob/master/src/mess/drivers/pcfx.c#L509
https://github.com/libretro/mame2014-libretro/blob/master/src/mess/drivers/pcfx.c#L515

**Comment by retro-wertz** [comment]
as per mednafen documentation, scsi is a developer feature atm. i do not see anywhere that it uses the scsi rom file anywhere, even if enabling "pcfx.fxscsi=1"--not sure.
