### ISSUE TITLE
Quake1

### ISSUE THREAD

**Issue by lasers** [libretro/libretro-database#356]
I'm unable to generate `Quake1` playlist. Quake1.rdb seems outdated too.

**Comment by RobLoach** [comment]
It's building okay here....

```
=== Building Quake1 ===
Parsing dat file 'retroarch/media/libretrodb/dat/Quake1.dat'...
```

**Comment by lasers** [comment]
Sorry. I didn't mean that one. I'm referring to `Quake1` playlist on RetroArch by scanning `Quake1` game from Content Downloader . Crc 74e3b084.

size, crc, md5, sha1 all matched.

**Comment by lasers** [comment]
Confirmed PR https://github.com/libretro/libretro-database/pull/357 indeed will help. Thanks. :-)
