### ISSUE TITLE
Gamecube IPL BIOSes all have dummy checksums and sizes

### ISSUE THREAD

**Issue by Whovian9369** [libretro/libretro-database#372]
In both the merged and un-merged DATs, The Gamecube section lists dummy CRC32, MD5s, and Sizes. In the Set Name on the unmerged DAT, it appears that they're all part of some "Adler32" dump set?

`game (`
`	name "Nintendo - GameCube (incomplete) - Using Adler32. USA 1FCE3FD6, USA_v1_1 4D5935D1, JAP 87424396, PAL A0EA7341"`
`	rom ( name "IPL.bin (USA 1.0)" size 1 crc 1000000 md5 10000000000000000000000000000000 )`
`	rom ( name "IPL.bin (USA 1.1)" size 2 crc 2000000 md5 20000000000000000000000000000000 )`
`	rom ( name "IPL.bin (JAP 1.0)" size 3 crc 3000000 md5 30000000000000000000000000000000 )`
`	rom ( name "IPL.bin (PAL 1.0)" size 4 crc 4000000 md5 40000000000000000000000000000000 )`
`)`

There is not really a good way for me to find the details of this, partially being because Redump.org is currently down. 

Thanks for your time.

------------------------------

Edit: According to [this post on the Dolphin forums](https://forums.dolphin-emu.org/Thread-unknown-hash-on-ipl-bin?pid=385344#pid385344) - The hashes for "IPL.bin (USA 1.0)" are as follows:

CRC32: 6D740AE7
MD5: FAE2B558FFC344467170520D62177E5C
SHA-1: 015808F637A984ACDE6A06EFA7546E278293C6EE

Edit: According to [this post on the Dolphin forums](https://forums.dolphin-emu.org/Thread-unknown-hash-on-ipl-bin?pid=385334#pid385334) - The hashes for "IPL.bin (USA 1.1)" are as follows:

CRC32: D5E6FEEA
MD5: 019E39822A9CA3029124F74DD4D55AC4
SHA-1: 239EACD86527FF9A75AEB7282DA65797BAEEF010

Edit: It APPEARS that, as far as [THIS post](https://forums.dolphin-emu.org/Thread-unknown-hash-on-ipl-bin?pid=385399#pid385399) says - There's a USA 1.2 firmware with the following checksums (In hex?):

 Adler32 0xDF6CF65B
CRC32 0x86573808
MD5 0xB17148254A5799684C7D783206504926
SHA1 0xEF9194AB4804AA0AA8540D846CAF291B28331165

Edit: According to [a comment on a Dolphin bug report,](https://bugs.dolphin-emu.org/issues/8936#note-4) there are two JPN dumps with the following checksums:

DOL-001 (Japan)
Adler32: B2FCDB25
CRC32: 6DAC1F2A
MD5: FC924A7C879B661ABC37CEC4F018FDF3
SHA-1: A1837968288253ED541F2B11440B68F5A9B33875

DOL-101 (Japan)
Adler32: 46E899DB
CRC32: D235E3F9
MD5: 81DF278301DC7BDF57BB760D7393AB4D
SHA-1: 96F69A21645DE73A5BA61E57951EF303D55788C5

**Comment by lasers** [comment]
I think this is an optional file that they offer you to load if the checkbox is on. It may be there for startup screen/menu/nostalgia.

We want `IPL.bin`. It may not be possible to add GameCube bios to this dat because of name collision... Just like old `Quake1.dat` where I wasn't able to scan a single game due to duplicate entries.

*Option:*
We could make them accurate then turn them into comments for information purposes only. We could put the md5 hashes in `dist/info/dolphin*.info` for information purposes too... Or to mention that Dolphin optionally can use `IPL.bin` bios.

*Option:*
If all filenames are literally same size, we could do something like...
`rom ( name "IPL.bin" size  1024 )`. I don't think Dolphin checks anything more than just `IPL.bin` or `ipl.bin` (?). No hashes, crc32, or anything like that, just `IPL.bin`. Not sure about `ipl.bin`. 

*Option:*
Remove all. Wait for libretro-dolphin to happen first as it may not use `IPL.bin` at all. Too early to tell anything. I was just adding potential missing bios from everywhere.

Up to you guys.

**Comment by Whovian9369** [comment]
From a Gamecube BIOS dat provided previously via Redump.org and I had saved for some reason:

`clrmamepro (`
`name "Nintendo GameCube - BIOS Images"`
`description "Nintendo GameCube - BIOS Images (7) (v2011-06-07)"`
`category Console`
`version 2011-06-07`
`author "ElBarto, Jackal | redump.org"`
`)`

`game (`
`name "gc-ntsc-10"`
`description "DOL-001(USA) / DOL-001(JPN) / SL-GC10 (NTSC Revision 1.0)"`
`rom ( name gc-ntsc-10.bin size 2097152 crc 6dac1f2a md5 fc924a7c879b661abc37cec4f018fdf3 sha1 a1837968288253ed541f2b11440b68f5a9b33875 )`
`)`

`game (`
`name "gc-pal-10"`
`description "DOL-001(EUR) / DOT-001P (PAL Revision 1.0)"`
`rom ( name gc-pal-10.bin size 2097152 crc 4f319f43 md5 0cdda509e2da83c85bfe423dd87346cc sha1 f27c63e5394e2fd1606f70df004c4fc2d6027700 )`
`)`

`game (`
`name "gc-pal-12"`
`description "DOL-101(EUR) (PAL Revision 1.2)"`
`rom ( name gc-pal-12.bin size 2097152 crc ad1b7f16 md5 db92574caab77a7ec99d4605fd6f2450 sha1 80b8744ff5e43585392f55546bd03a673d11ef5f )`
`)`

`game (`
`name "gc-dvd-20010608"`
`description "DVD Drive (Version 2001/06/08)"`
`rom ( name gc-dvd-20010608.bin size 131072 crc c047465a md5 561532ad496f644897952d2cef5bb431 sha1 27872c201e87b06a19bf85d36c796ef383f8d52d )`
`)`

`game (`
`name "gc-dvd-20010831"`
`description "DVD Drive (Version 2001/08/31)"`
`rom ( name gc-dvd-20010831.bin size 131072 crc 54c7d10e md5 b953eb1a8fc9922b3f7051c1cdc451f1 sha1 ae7233cae8f94749796e0b740d6021e3b00a8926 )`
`)`

`game (`
`name "gc-dvd-20020402"`
`description "DVD Drive (Version 2002/04/02)"`
`rom ( name gc-dvd-20020402.bin size 131072 crc 8bbef508 md5 413154dd0e2c824c9b18b807fd03ec4e sha1 691e46213d8428befdf568157e670b971ab94e1d )`
`)`

`game (`
`name "gc-dvd-20020823"`
`description "DVD Drive (Version 2002/08/23)"`
`rom ( name gc-dvd-20020823.bin size 131072 crc 5205222b md5 c03f6bbaf644eb9b3ee261dbe199eb42 sha1 2faaf92bcaffe675f54f7249d30f3791507e22ab )`
`)`
