### ISSUE TITLE
Sega - Mega Drive - Genesis: Two BIOS listed with the same hash info

### ISSUE THREAD

**Issue by Whovian9369** [libretro/libretro-database#374]
`missing rom: bios_E.sms [size: 8192] [CRC32: 0072ed54] [MD5: 840481177270d5642a14ca71ee72844c] [SHA1: c315672807d8ddb8d91443729405c766dd95cae7]`
`missing rom: bios_U.sms [size: 8192] [CRC32: 0072ed54] [MD5: 840481177270d5642a14ca71ee72844c] [SHA1: c315672807d8ddb8d91443729405c766dd95cae7]`

**Comment by RobLoach** [comment]
Do you know what the right values are for these?

**Comment by markwkidd** [comment]
I think things are listed correctly as-is. According to No-Intro, version 1.3 of the Master System BIOS was the same file with the same checksum for both Europe and the USA. The No-Intro records match the checksums listed above.

**Comment by Whovian9369** [comment]
> I think things are listed correctly as-is. According to No-Intro, version 1.3 of the Master System BIOS was the same file with the same checksum for both Europe and the USA. The No-Intro records match the checksums listed above.
Hmm, alright. Thanks!

**Comment by lasers** [comment]
Just for confirmation. Both files are indeed same. This was in 1986.

Slightly formatted, but straight from No-Intro database.
```
name "[BIOS] Sega Master System (USA, Europe) (v1.3)"
rom "[BIOS] Sega Master System (USA, Europe) (v1.3).sms" size 8192 crc 0072ED54 \
md5 840481177270D5642A14CA71EE72844C sha1 C315672807D8DDB8D91443729405C766DD95CAE7 )
```
└── _Sega - Master System - Mark III (20161224-070745_CM).dat_
