### ISSUE TITLE
BIOS files for Phillips Videopac+

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#383]
Howdy. I noticed that only BIOS information for the Magnavox Odyssey2 was listed in the .info file for the O2EM core.

I just submitted a PR to add the European Phillips Videopac+ versions of the BIOS to the .info: https://github.com/libretro/libretro-super/pull/416

I don't know if there is anything that needs to happen on the libretro-database end in order to support this addition, so I thought I'd post a message here in case that is the case.

**Comment by RobLoach** [comment]
Good call... Perhaps add a "Phillips Videopac+" in there?

**Comment by lasers** [comment]
If you like, you can update `dat/BIOS - Non-Merged.dat`, `dat/BIOS - Merged.dat` with missing information. https://github.com/libretro/libretro-o2em/blob/master/libretro.c#L145-L165

**Comment by markwkidd** [comment]
Thanks guys. I've started a PR: https://github.com/libretro/libretro-o2em/pull/12

@lasers now that I know that there was already code for these BIOSes in the database checker, can you confirm that the BIOS filenames that I added to the .info are the same ones that the core will be looking for? (direct link: https://github.com/markwkidd/libretro-super/blob/fb33fd36410c3bc7b7fc9ca2536a9f7380007cc6/dist/info/o2em_libretro.info)

**Comment by lasers** [comment]
Just first home video gaming system. Not a fan. :o 

The BIOS hashes looks good. I think the core only looks for `o2rom.bin`. If that's true, then all those bios might be unnecessary. Somebody who understand code should look at this code and confirm it for you before you continue.

https://github.com/libretro/libretro-o2em/blob/master/libretro.c#L478-L503

**Comment by markwkidd** [comment]
From my reading, the European G7400 models had enhanced functionality and presumably different BIOS code. O2EM standalone says it supports the European Videopac+ BIOSes in addition to the Oddessy2 BIOS.

**Comment by markwkidd** [comment]
Ah hah. With all the new search term ideas this conversation has given me, I think I found the answer right here in the libretro repo. I do need to change the BIOS names, but this core ought to support all four: https://github.com/r-type/libretro-o2em/blob/master/O2EM/Docs/O2EM.TXT#L113

**Comment by lasers** [comment]
I think you don't have to change anything as it only checks for CRC32. New name looks good.

This is for libretro-o2em, not o2em standalone so that so that `Quick Setup` documentation may not be relevant here. Tbh, I'm not sure anymore. Best we seek assistance from outside before continuing... or at least test libretro-o2em first with or without various bios.  One at a time. Ah hah. :-)

Merged looks good. Non-Merged, it should go under `Magnavox - Odyssey2` section (See `Nintendo - Nintendo Entertainment System` for example) since this core is capable of playing both systems.

**Comment by markwkidd** [comment]
Thanks @lasers, I pushed an update to the Non-Merged PR to conform with the approached used by the Nintendo Entertainment System.

I see that @r-type was involved in the port to libretro. r-type: if you see this, do you have any idea whether support for the European BIOSes was removed from standalone O2EM during the port process?

**Comment by lasers** [comment]
Add `size 1024` 

http://www.progettoemma.net/mess/system.php?machine=videopac
http://www.progettoemma.net/mess/system.php?machine=g7400

**Comment by markwkidd** [comment]
@lasers I just added the file sizes. (D'oh, I can't believe I overlooked that part of the DAT format.) As often the case, I only meant to fill in a blank spot in the Lakka BIOSes documentation page but instead managed to spend an afternoon learning about this sytem. I hope I have it in order now, but if you do notice anything else please feel free to let me know. I appreciate the help.

**Comment by lasers** [comment]
I looked through them just now. Rage OCD mode on: `rom (name` -> `rom ( name`. Really, everything looks fine. Ready for merge. No problem helping out. If you want, you probably could do PCFX / GameCube next. Will look around.

**Comment by markwkidd** [comment]
I think this effort is complete, so I'll close the issue.

**Comment by estefan3112** [comment]
Hello @markwkidd another G7400 fan here: How do I actually launch the G7400.bin in Retroarch in the absence of any Core Options? I verified with O2EM 1.18 standalone that - by launching O2EM with the option -g7400, a plus game launches correctly into the enhanced mode. But how is this possible in Retroarch? Many thanks - i was so exited to watch Terrahawks in G7400+ :-)
