### ISSUE TITLE
N64 Cheats

### ISSUE THREAD

**Issue by loganmc10** [libretro/libretro-database#388]
Now that mupen64plus-libretro and glupen64 support cheats, it would be worthwhile for them to be added to this database.

This file has all the cheats:
https://raw.githubusercontent.com/mupen64plus/mupen64plus-core/master/data/mupencheat.txt

Hopefully someone with some sed/scripting skills can write something to convert that to .cht files?

**Comment by RobLoach** [comment]
```
crc B6951A94-63C849AF-C:4A
gn Akumajou Dracula Mokushiroku - Real Action Adventure (J)
 cn Infinite\Health
  81389C3E 0064
 cn Infinite\Throwing Weapon
  81389C48 0064
 cn Throwing Weapon Modifier
  81389C42 ???? 0000:"Nothing",0001:"Knives",0002:"Exploding Potions",0003:"Cross",0004:"Axes"
 cn Press L To Levitate
  D0387D7F 0020
  81350810 3FCB
 cn Have\All Items
  50000501 0000
  80389C4A 0001
  50000301 0000
  80389C51 0001
  80389C5A 0001
  80389C5B 0001
  80389C5D 0001
  50000E01 0000
  80389C60 0001
```

- `gn` Game Name
- `cn` Cheat Name

Do you know what the rest of the entries equate to?

**Comment by alondero** [comment]
I'm not able to get this to work on the latest build on Windows? I've tried a number of games and each cheat file variation for those games... nothing seems to change. I'm pressing Apply and waiting for the notification to clear before resuming the game. Anything I can do to help debug?

**Comment by loganmc10** [comment]
What core are you using? and what version of the core?

**Comment by alondero** [comment]
Latest nightly of glupen64 (says 99ddfff but don't think that's the version) with 8th Jan x86_64 nightly of retroarch on Windows 10. I've tested cheats on other cores just as a sanity check and fceumm and genesis plus both worked well

**Comment by loganmc10** [comment]
99ddfff is the version, I think you'll need a more recent version of glupen64, you can either try using the online updater again, or you can grab the latest version from here:

http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

Cheats for Windows on glupen64 was just fixed on Jan 8, but I believe you have an older version

**Comment by alondero** [comment]
Looks like the latest core from the retroarch buildbot wasn't the latest. Whilst I couldn't get mario cheats to work (suspect wrong version) I got goldeneye to work. Thanks!
