### ISSUE TITLE
psx Final Fantasy VIII (Europe, Australia) all discs are not being detected.

### ISSUE THREAD

**Issue by osirase** [libretro/libretro-database#401]
I noticed there is an entry for all four discs in the .rdb file for these discs, yet they don't show up. I've verified my copy 3 times and extracted 3 times yet still no detection. I had the same issue with my copy of Tombi! 2 (Europe) but with that I noticed it wasn't in the rdb file, so I contributed that into the dat file which should be resolved on the next rdb update. 

Final Fantasy VIII is present in the database though and is still not detected. Redump.org is still down so I can't check there to see if my copy is the same unfortunately. Where can I look to see what it's compared against? Maybe the CRC (I think this is the method used with redumps database to check for validity?) is wrong on the database end. 

Either that or all four of my discs that I verified 3 times are bad 3 times in a row. 

Also, could someone point me to the resources on how the images are verified and against what database? I'm assuming it's redump.org. I don't know where to look for the mechanism that libretro uses to do this. I don't like relying on assuming how things work.

Everyone's input would be greatly appreciated!

Thanks

**Comment by RobLoach** [comment]
What CRCs are you loading? The Redump .cue files are indexed at:
https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/redump/Sony%20-%20PlayStation.dat

These might be eaten by the serial scanning, however. Mind posting the CRCs of the files you're attempting to scan?

**Comment by osirase** [comment]
Thank you for replying!

http://i.imgur.com/QLgMRiB.png

I think this screenshot sums up everything without words.
All other games, bar tombi! 2 (Europe) detect fine, which should be fixed later when the rdb is rebuilt I assume. This is a good time to ask, when is one to expect the psx rdb to be rebuilt? Is it when a couple more games are added?

Thanks :)

**Comment by osirase** [comment]
I just wanted to update that as of 1.6.1, Tombi! 2 (Europe) is now successfully detecting and adding itself with it's artwork to the playlist.

However Final Fantasy VIII (Europe, Australia) all four discs still don't get added. I can see it's entry in the database source but it's just not working. I also discovered that this is also happening for Small Soldiers (Europe). I can see the entry for Small Soldiers as well in libretro-database/dat/Sony - PlayStation.dat
 
I'd like to have a go at debugging this myself, if you have any resources that might kick start how to contribute in a more productive way to solve this issues I am all ears. 

Thanks

**Comment by osirase** [comment]
As of 1.7.2, Final Fantasy VIII (Europe, Australia) Disc 1 is now adding!

Same for 1.7.3. 

However, it's artwork is not present, in fact the artwork for Tombi! 2 (Europe) and Tombi! (Europe) has also stopped displaying. 90% of my psx library is fine etc. Crash Bandicoot and Spyro (Europe).

A handful of other games now scan it too but present no artwork even though it's present in the thumbnails.zip such as:

Disney-Pixar Toy Story 2 - Buzz Lightyear to the Rescue! (Europe)
Final Fantasy VIII (Europse, Australia) (Disc 1 of 4)
Future Cop L.A.P.D. (Europe)
In the Hunt (Europe)
Micro Machines V3 (Europe) (En,Fr,De,Es,It) (No EDC)


The title is also omitting the ", Australia" part of the file name, which might be a clue as to the weird behaviour of this game. See the two pictures below for examples:

https://i.imgur.com/JddMkRZ.png
https://i.imgur.com/5Wzi6zT.png

I'm about to test the other 3 Discs to observe their behaviour. 

However, it's great that it's finally scrapping into the library at all! Great stuff.
