### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by CoalaJoe** [libretro/libretro-database#408]
Hey there. 
Got some games that are missing in the database. How about a CONTRIBUTING.md or guide how to add stuff to the repo?

**Comment by RobLoach** [comment]
:+1:

Would be great to have a README.md as well to cover how some of this is set up.

**Comment by CoalaJoe** [comment]
Nice. Thanks for the fast reply.
So I can add a file to `/dat` with the name of the console and it will be read and interpreted, or are only the once that are there supported?

**Comment by RobLoach** [comment]
Yes indeedy!

**Comment by CoalaJoe** [comment]
Ah. Thank you. I'll look into this.

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/pull/410
