### ISSUE TITLE
Would it be possible to have Mame software lists added to the data base?

### ISSUE THREAD

**Issue by ghost** [libretro/libretro-database#411]
Since Mame git now has mess integrated in it. I think we should allow for scanning of the software lists. 
Maybe have two dats: one for Arcade and one for software. Or maybe have multiple for software like one for each of the systems supported by Mame's software list.

**Comment by NihilisticEevee** [comment]
here are the clrmamepro dats if that helps any.
[MAME 0.182 Software List ROMs (datfiles).zip](https://github.com/libretro/libretro-database/files/747056/MAME.0.182.Software.List.ROMs.datfiles.zip)

**Comment by cirelli94** [comment]
@ghost i'm sorry but i can't understand. Are you placing this .dat inside the ones lakka will recognize?

**Comment by RobLoach** [comment]
While the software lists do have good data, I'm not sure that's how MAME launches its files. RA expects one file to launch its game, but some of the above entries have multiple files. I think MAME wants a game name, so that model does not quite match up.
