### ISSUE TITLE
Ape Escape (Europe) boxart thumbnail not displaying

### ISSUE THREAD

**Issue by osirase** [libretro/libretro-database#413]
I see that this boxart png is present in the thumbnail repo.

https://github.com/libretro/libretro-thumbnails/blob/master/Sony%20-%20PlayStation/Named_Boxarts/Ape%20Escape%20(Europe).png

It also displays the previously displayed thumbnail, instead of displaying a blank spot.

Here is an example.
http://i.imgur.com/zRQ2cYA.png
http://i.imgur.com/eGylpbW.jpg

This is the only instance where it displays the previously viewed thumbnail, all other rom's that lack thumbnail data displays a blank space instead.

**Comment by osirase** [comment]
I've just noticed that this also happens with Tekken 2 (Europe) as well.
The thumbnail exists in the repo for that too.

**Comment by RobLoach** [comment]
Steps to reproduce?

**Comment by osirase** [comment]
After your request I attempted to reproduce it on my Fedora installation. The thumbnails no longer do the sticky thing, they correctly show up blank. Still, ideally the boxart thumbnail should show  as it seems to be present after downloading the thumbnails. 

The sticky thing only seems to happen on the ps1 list and on Windows 10. Can confirm for versions 1.4.0 and 1.4.1. 

Steps to reproduce:
1. Download retroarch windows binaries from the buildbot,
2. Unpack and use the online updater tool to update thumbnails, databases, autoconfigc, Core Info Files, Assets, Databases and Overlays. Also update the mednafen core for psx. Not the HW version.
3. Use the scan directory tool to in retroarch. (Would you like a list of my games present in my psx collection?)

Ahhhh, so its now also happening on my Fedora 1.4.1 fresh build. It didn't happen immediately, I had it idling on a game that had a boxart thumb nail (Crash Bandicoot 2 in this instance). After I finished writing step three and went to exit retroarch on fedora and noticed the thumbnail was sticking on when navigating (Using a standard keyboard) to other games (Ape Escape and Tekken 2 in this instance).

It seemed that idling on a game triggered it to happen. Let me know any other bits of information I can give you that may be useful.

**Comment by RobLoach** [comment]
Fixing in https://github.com/libretro/libretro-thumbnails/pull/287

**Comment by osirase** [comment]
Ahhh awesome, I shall check that they're truly PNG next time. Shall I do another merge or will you take care of this one?

Thanks

**Comment by RobLoach** [comment]
Another merge of what?

**Comment by osirase** [comment]
The thumbnails for Ape Escape and Tekken 2

**Comment by RobLoach** [comment]
Just sent a PR over at https://github.com/libretro/libretro-thumbnails/pull/288 ... Feel free to fix future ones yourself, if you're up to it :+1: 

Good find! Thanks.
