### ISSUE TITLE
cheat for nes or megadrive doesn't work for me

### ISSUE THREAD

**Issue by shamokgit** [libretro/libretro-database#426]
hello, 

i'm on retroarch.
the most of the cheats for snes work
but i tried dozen on nes (like: legend of zelda) and Genesis/megadrive (like: shadow dancer)
and those doesn't work at all ... 

any adevice ? or fix ?
thanks

**Comment by RobLoach** [comment]
1. Which game
2. Which cheat
3. What process are you going through to apply the cheat?

Need more information in order to help you debug things.

**Comment by shamokgit** [comment]
hi 

exemple with Legend of zelda on Nes.
from the retroarch menu -> Quick menu -> cheat
I load legendzelda.cht file (one the file from this database)
for exemple: AVVLAUSZ        Don't take damage from anything
I apply cheats
go back to the game ... 
and I'm still losing life.

the same process for "shadow dancer" on Genesis
with the code infinity energy found on this site database.
I'm still losing life.

the same process with Zelda a link to the past on snes
and It works perfectly .... not losing life at all

thanks

**Comment by shamokgit** [comment]
FYI
Legend of zelda and shadow dancer codes are Gamegenie code
Zelda a link to the past code are Action replay

**Comment by demechman** [comment]
Sometimes this is caused by the version of your ROM. Have you tried other games in you NES library?

**Comment by RetroSven** [comment]
FYI there is now a cheat-code-searching/generating system built into RA that makes it very easy to create your own cheats for games - especially for things with specific/known values like the number of bombs you're carrying.  This works on practically every RA core now so you can create your own cheats on systems that don't have any pre-created cheats in RA database (or the db doesn't have what you want).
