### ISSUE TITLE
(Request) The urbz: Sims in the city and Super Mario All-Strs + Super Mario world cheats

### ISSUE THREAD

**Issue by sergioad** [libretro/libretro-database#427]
Hi friends, could you add cheat codes for The urbz: Sims in the city and Super Mario All-Strs + Super Mario world? I know how cheats work and I know how to use them but I do not know how to add them to the database, in addition I have seen that your cheats works in other regions / versions of the games so I am confused about how them works and I do not want to do anything that could crash someone's game(s)

**Comment by RobLoach** [comment]
Link to the cheats? You could probably add them yourself in a PR too.

**Comment by sergioad** [comment]
https://gamehacking.org/game/6387
For the Urbs

https://gamehacking.org/game/44854
For the All stars

**Comment by RobLoach** [comment]
1. Visit https://github.com/libretro/libretro-database/tree/master/cht
2. Add each file through the user interface
3. Submit Pull Requests with the new files

**Comment by sergioad** [comment]
Ok, thank you very much
