### ISSUE TITLE
how-to

### ISSUE THREAD

**Issue by Fisher5K** [libretro/libretro-database#428]
can somebody point me in the direction on how to make one of these cheat files. there are a few for gameboy advanced but are not in there

**Comment by RobLoach** [comment]
1. Visit https://github.com/libretro/libretro-database/tree/master/cht/Nintendo%20-%20Game%20Boy%20Advance
2. Create a new file with the name of the game
3. Follow the format to create a list of cheats https://github.com/libretro/libretro-database/blob/master/cht/Nintendo%20-%20Game%20Boy%20Advance/Advance%20Wars%202%20-%20Black%20Hole%20Rising%20(USA%2C%20Europe)%20(Code%20Breaker).cht
