### ISSUE TITLE
Add RomHacking DAT

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-database#434]
there is just no need to have a whole lot of overdumps, alternates, demos, test roms, betas of the same rom  and 1 million in one carts  etc. move these to separate database. goodnes alone have almost 22k roms compared known dumps which is just about 3k.

have the pure dumps or known roms in separate folder as it was(redump,no-into(ish). with the search engine the way it is now, its hard to find stuffs not to mention the slow-downs this causes when moving between playlists.

**Comment by RobLoach** [comment]
While there is [some documentation about source info](https://github.com/libretro/libretro-database#sources), this is an interesting idea...

1. The [libretro-super info files](https://github.com/libretro/libretro-super/tree/master/dist/info) determine what RDB files are used for each system.
2. [libretro-build-database.sh](https://github.com/libretro/libretro-super/blob/master/libretro-build-database.sh) determines what RDB files are built out.

Given that, we could:
1. Rename the DAT files and prepend/append the source
2. Build out different RDB files with the source prepended/appended
3. Add the RDB file names to each [libretro-super info files](https://github.com/libretro/libretro-super/tree/master/dist/info)

Again, I don't want to make maintaining the DAT files difficult. The less we need to do to update them the better.

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/tree/master/metadat/hacks

Would be cool if we could have a big DAT from [RomHacking.net](http://www.romhacking.net/).

**Comment by i30817** [comment]
A dat from for romhacks would be nice, but it still would need to get sorted into playlists. And it would be incomplete, I, myself only use softpatching when possible, and habitually modify the snes ips to work without headers.

**Comment by RobLoach** [comment]
If you have any hacks you'd like to add, feel free to add them in:
https://github.com/libretro/libretro-database/tree/master/metadat/hacks
