### ISSUE TITLE
Needs to update all rdb

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-database#437]
Pokemon Yellow is appearing in GBC playlist instead GB, seems someone forgot to update both rdb. Aren't they updated automatically with newer dats?

```Pokemon - Yellow Version (UE) [C][!]```

Have no idea from what dat is this from.

**Comment by RobLoach** [comment]
Likely GoodTools... Think we should just deprecate it?

**Comment by sergiobenrocha2** [comment]
Pokemon - Yellow Version - Special Pikachu Edition (USA, Europe) (GBC,SGB Enhanced).gb
CRC: 7d527d62

This game is GB actually, take a look at https://github.com/libretro/libretro-database/blob/master/metadat/no-intro/Nintendo%20-%20Game%20Boy.dat#L6507. We should update both rdb like I said before.

**Comment by sergiobenrocha2** [comment]
Actually they were updated 4 days ago, what's going on? Why is it picking the GoodTools entry instead no-intro?

**Comment by sergiobenrocha2** [comment]
Weird, it's not happening on linux... that happened on windows, with 1.5.0 stable.

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/search?utf8=%E2%9C%93&q=7D527D62

Looks like it's just part of No-Intro. No Color involved. Did you update the databases on Windows?

**Comment by JuanVCS** [comment]
This seems relevant https://github.com/libretro/libretro-database/pull/438

**Comment by NilsBloodaxe** [comment]
Also it seems like some other games have changed.  Banjo-Kazooie (USA) doesn't match the No-Intro sets for either revision.  I would spend time fixing, but I am unsure what to do.

**Comment by RobLoach** [comment]
The metadata names are replaced with No-Intro names during the RDB build process. Having CRCs not match is an issue we should likely address. Certainly does take time.... I think @TaoPlyPly had some sort of build process for the metadata .dat files?

**Comment by NilsBloodaxe** [comment]
It may be a version issue too.  Retroarch 1.6 on Windows seemed to capture the no-intro version of Banjo-Kazooie, but not Retroarch 1.5 on Lakka 2.0 for the Pi.

**Comment by RobLoach** [comment]
Mmmm, Lakka may have had an older DB at the time:
https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-V2.0/packages/libretro/libretro-database/package.mk

**Comment by NilsBloodaxe** [comment]
So after a bit of testing, I found 13 N64 games that did not come up in Lakka 2.0, 11 of these were version 1.1 of the game and version 1.0 worked, 1 was version 1.2 and version 1.0 worked (but not 1.1), and then there was Banjo-Kazooie, neither version in the no-intro list was discovered, but another version of the same rom did work.  However, all came up in Retroarch 1.6 on Windows.

**Comment by RobLoach** [comment]
Should be up and running! Feel free to re-open if RDBs aren't getting updated.
