### ISSUE TITLE
Rom validators problems with Sony - Playstation.dat

### ISSUE THREAD

**Issue by cirelli94** [libretro/libretro-database#440]
I'm tryng to validate some roms with the [playstation .dat file](https://github.com/libretro/libretro-database/blob/master/dat/Sony%20-%20PlayStation.dat) using RomVault but it seems there are some problems parsing the file:
http://i.imgur.com/bmpqOz9.png

I tried even clrmamepro, which have other problems:
http://i.imgur.com/ib1UoaH.png

I don't know what is the problem.
Thanks for your work

**Comment by RobLoach** [comment]
This one?
https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sony%20-%20PlayStation.dat

Usually you would use the ones directly from Redump to validate. These are parsed and adapted for retroarch.

**Comment by RobLoach** [comment]
I think this is fixed now. Feel free to re-open if not.
