### ISSUE TITLE
SEGA Genesis Classics ROM Recognition

### ISSUE THREAD

**Issue by FayneAldan** [libretro/libretro-database#457]
I feel like the database for the Sega Mega Drive / Genesis should include the ROMs provided officially by Sega within Sega Mega Drive and Genesis Classics (which is on Steam).
I have most of the CRC checksums here: https://pastebin.com/CMzHMQa9

Missing from the list (simply because I haven't bought them):
- [Beyond Oasis](http://store.steampowered.com/app/211200/Beyond_Oasis/)
- [Dynamite Headdy](http://store.steampowered.com/app/211201/Dynamite_Headdy/)
- [Golden Axe III](http://store.steampowered.com/app/211202/Golden_Axe_III/)
- [Phantasy Star II](http://store.steampowered.com/app/211203/Phantasy_Star_II/)
- [Phantasy Star III: Generations of Doom](http://store.steampowered.com/app/211204/Phantasy_Star_III_Generations_of_Doom/)
- [Phantasy Star IV: The End of the Millennium](http://store.steampowered.com/app/211205/Phantasy_Star_IV_The_End_of_the_Millennium/)
- [Streets of Rage 3](http://store.steampowered.com/app/211206/Streets_of_Rage_3/)
- [The Revenge of Shinobi](http://store.steampowered.com/app/211207/The_Revenge_of_Shinobi/)
- [VectorMan 2](http://store.steampowered.com/app/211208/VectorMan_2/)
- [Wonder Boy in Monster World](http://store.steampowered.com/app/211209/Wonder_Boy_in_Monster_World/)

If anyone has **bought** any of those games above **on Steam**, it would be really helpful if you could provide the CRC-32 checksums for them. The ROMs can be found in:
`C:\Program Files (x86)\Steam\steamapps\common\Sega Classics\uncompressed ROMs`
Replace `Program Files (x86)` with simply `Program Files` if you have a 32-bit computer.

**Comment by RobLoach** [comment]
We could add them in a DAT over at https://github.com/libretro/libretro-database/tree/master/dat . Feel free to create a DAT for it. [clrmamepro](https://mamedev.emulab.it/clrmamepro/) has a Dir2Dat feature which will do that for you.

**Comment by FayneAldan** [comment]
Well, that clrmamepro program didn't work for me, so I created the dat file manually. I also got the remaining games from a friend. I'm not going to submit a PR yet because there are some things I'm unsure of.
[DAT File](https://pastebin.com/Ygr3eX4s)
All of the ROMs there I scanned with RetroArch with the changed extensions. Sword of Vermilion and Ecco Jr. were not recognized until I converted them to a different format. Alien Storm, Galaxy Force II, Phantasy Star 2, 3, 4, Shadow Dancer, and Sonic 3 & Knuckles (which is included without Sonic 3 or Sonic & Knuckles individually) would not scan at all, even after changing formats, so I took my best guess at the regions and revisions for them. All the rest match what's already in the database.

**Comment by RobLoach** [comment]
@FayneAldan Nice one! Feel free to submit it over at:
https://github.com/libretro/libretro-database/new/master/dat

**Comment by FayneAldan** [comment]
I just said "I'm not going to submit a PR yet because there are some things I'm unsure of." I'm not sure if some of the ROMs are correct.

**Comment by RobLoach** [comment]
I ignored that, sorry... Think what you have is pretty good, worth testing out further.

**Comment by RobLoach** [comment]
Nicely done! I do see some duplicates from No-Intro, but I think we could just ignore those. Let's test this for a bit and see if we could submit any fixes down the line.

**Comment by RobLoach** [comment]
Feel free to re-open if you find anything wrong!
