### ISSUE TITLE
Missing no-intro ROM in scan

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#464]
I noticed this on the wonderswan color scan, which i have a small dir with 3 translated games (just to be clear, these are softpatches, not hardpatches, and their crc exists on the database and the files were not changed in anyway).
Dicing Knight. (Japan)/Dicing Knight. (Japan).wsc
Makai Toushi Sa-Ga (Japan)/Makai Toushi Sa-Ga (Japan).wsc
Mr. Driller (Japan)/Mr. Driller (Japan).wsc

Only Makai Toushi Sa-Ga is shown. I suspect this is because of the extra '.' either in the names, or in the parent dir. The database has the correct name and CRC, of for example Mr. Driller, but it still won't show.

'.' is a valid character both in path and filenames, so if something is going wrong here many other ROMs aren't being picked up.

database mr.driller data:
{"serial": "53574A2D4E4D43433031", "sha1": "209232F1E91C05140529D466C0EF6B7AD3386DE1", "md5": "9D600BFE28196609FBE4FB5B89486CBC", "crc": "5555D95C", "publisher": "Namco", "developer": "Namco", "franchise": "Mr. Driller", "releaseyear": 2001, "releasemonth": 4, "size": 2097152, "rom_name": "Mr. Driller (Japan).wsc", "description": "Mr. Driller (Japan)", "name": "Mr. Driller (Japan)"}

Bandai - WonderSwan Color.lpl contents after scan (only one game so the error is doing scan, not playlist reading):
/media/i30817/backup/Documents/Games/Bandai WonderSwan Color/Makai Toushi Sa-Ga (Japan)/Makai Toushi Sa-Ga (Japan).wsc
Makai Toushi Sa-Ga (Japan)
DETECT
DETECT
1B6F5F30|crc
Bandai - WonderSwan Color.lpl

this is a duplicate of libretro/RetroArch#5111. I was unsure where the bug belongs to. It's not a database problem but a scanner problem, but i was asked to move it here. I'll leave to admins to close the 'wrong' one.

**Comment by RobLoach** [comment]
Yeah, the translations are not currently in the DATs. You'll find a set of manually added hacks over at:
https://github.com/libretro/libretro-database/tree/master/metadat/hacks

Feel free to create a new Wonderswan Color DAT over there for the translations you want to add.

**Comment by i30817** [comment]
@RobLoach Well, the translation not being on the dat is not the problem: the translation is a ips softpatch and was not applied to the original file. I could and did just now test the scan without the ips file and it didn't add. I'm not trying to add to the playlist as 'the translated game' but as if it was the original. This works on other cases btw, namely all SNES games i tried.

I also tested after that the scan by first modifying the parent directory to have no '.' and it worked. *The problem here is the scan aborting when the dir that contains the ROM having a dot '.' in the name*

**Comment by i30817** [comment]
BTW this can be tediously worked around by going into each dir that contains the game before scanning instead of depending on the recursive scan.

**Comment by RobLoach** [comment]
For me....

```
Dicing Knight. (Japan)/Dicing Knight. (Japan).wsc <-- Not scanned
Makai Toushi Sa-Ga (Japan)/Makai Toushi Sa-Ga (Japan).wsc <--- Scanned
Mr. Driller (Japan)/Mr. Driller (Japan).wsc <--- Scanned
``

So I'm not sure what's wrong with having `Diving Knight. (Japan).zip`

Never tested translations or soft-patching. How do you do that?

**Comment by i30817** [comment]
For softpatching is sufficient to have the .ips or .bps named the same as the rom (minus the ROM extension) on the same directory.
game.ips
game.nes

What I *think* is going wrong, without looking at code is the recursive scan. When i try it it doesn't follow until the 'leaves' of the directory tree if the dir has '.' on the name and it would have to go into it to find the games. So if you start scanning for the dir where the game is, everything is fine, but if you try to start scanning from a level above and the containing dir has dots, everything is wrong.

This is pretty annoying because crlmamepro by default moves the games to directories named the same as the ROM file (without extension) during a rebuild if not zipping. I have lots and lots of games that aren't scanned because of this (and many ROM names have 1.1 versions in the name and similar).

**Comment by i30817** [comment]
this is a retroarch problem, see referenced PR for confirmation. Closing here.

**Comment by i30817** [comment]
@RobLoach can you approve my PR for this above? It's a pretty simple mistake of searching for '.' in directory filenames to filter out the symbolic directories '.' and '..' instead of assuring the name is '.' or '..'

i also added a small fix for a harmless bug where directories had a 'extension' that's pretty much no-good behavior.

**Comment by i30817** [comment]
I'm frankly amazed that more people haven't complained of this but that's probably because most people keep games on the same directory in compressed archives so they don't hit this.
