### ISSUE TITLE
Genesis "Beggar Prince (World) (Unl)" has a weird name on the database

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#466]
crc32 : f3af46cd

I noticed this on the rgui, but i verified it on a database dump with 

./libretrodb_tool Sega\ -\ Mega\ Drive\ -\ Genesis.rdb list > md.txt

There are two versions of the game on the database, a 'Rev 1 Unlicensed' version and a original Unlicensed one:

{"sha1": "F481B970756C482D8F408C4BAB8902172837E7D8", "md5": "B5616628E9FF5D6861201388D018B8BC", "crc": "F3AF46CD", "developer": "C&E Inc.", "releaseyear": 2006, "releasemonth": 5, "size": 4194304, "rom_name": "Beggar Prince (World) (Unl).md", "description": "Beggar Prince (World) (Unl) (The hash data is from the first printing of this game)", "name": "Beggar Prince (World) (Unl) (The hash data is from the first printing of this game)"}

Is it really a good idea to have comments like this in the name?

**Comment by RobLoach** [comment]
Good catch...

http://datomatic.no-intro.org/?page=show_record&s=32&n=1729

```
game (
	name "Beggar Prince (World) (Unl) (The hash data is from the first printing of this game)"
	description "Beggar Prince (World) (Unl) (The hash data is from the first printing of this game)"
	rom ( name "Beggar Prince (World) (Unl).md" size 4194304 crc F3AF46CD md5 B5616628E9FF5D6861201388D018B8BC sha1 F481B970756C482D8F408C4BAB8902172837E7D8 )
)
```

**Comment by i30817** [comment]
No-intro DS encrypted also changed some of the checksums because some games were redumped. I know of "Luminous Arc 2 (USA)" and "Last Window - The Secret of Cape West (Europe) (En,Fr,De,Es,It)" but probably there are more.
