### ISSUE TITLE
Setting Up DS Cheats On RetroArch (Not Retropie)

### ISSUE THREAD

**Issue by GizmoChapa** [libretro/libretro-database#467]
Ok so I am not too good at this scene but I am trying to add the USRcheat.dat file to a new folder I made in retroarch. Basically, I just want to have a file full of .CHT files for the NDS. I have tried online updater but it does not add an NDS cheat file folder

**Comment by RobLoach** [comment]
There currently arn't any Nintendo DS cheats. Feel free to try adding some and submit a PR.

**Comment by RobLoach** [comment]
Whoooooooooaaaaaaaaaaa https://github.com/libretro/libretro-database/pull/470
