### ISSUE TITLE
Dreamcast database is terrible at ID-ing games.

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#468]
The reason for this is the format of .GDI files and the dumping standards of tosec. While 'equivalent' to cue files, their contents are usually much like this:

3
1 0 4 2352 track01.bin 0
2 450 0 2352 track02.raw 0
3 45000 4 2352 track03.bin 0

That is, standardized track names without any other info, no references to the name of the game, and other positional information, that is quite likely to repeat. Indeed a game i have has a repeated crc/md5 

{"sha1": "9D50B816D3F69AD192F5986AB487769965C2E082", "md5": "B3ECDF113FD42344DD84142679E4CB36", "crc": "D7AB4C6B", "size": 87, "rom_name": "Zombie Revenge v1.001 (1999)(Sega)(NTSC)(US)[!].gdi", "description": "Zombie Revenge v1.001 (1999)(Sega)(NTSC)(US)[!]", "name": "Zombie Revenge v1.001 (1999)(Sega)(NTSC)(US)[!]"}

and the repeat

{"sha1": "9D50B816D3F69AD192F5986AB487769965C2E082", "md5": "B3ECDF113FD42344DD84142679E4CB36", "crc": "D7AB4C6B", "size": 87, "rom_name": "Super Magnetic NiuNiu (Japan).gdi", "description": "Super Magnetic NiuNiu (Japan) - supamagunetitukuniyuuniyuu", "name": "Super Magnetic NiuNiu (Japan) - supamagunetitukuniyuuniyuu"}

This causes the name to appear wrong on the scanner btw, and would maybe screw up netplay or other RA features that depend on crc uniqueness? Maybe? Not sure if the features depend only on cue crc.

**Comment by i30817** [comment]
Not the only case either:
{"sha1": "980036E44AD9D694EA1699CD05C86CCD0C894C47", "md5": "346FEA58AB1A55C577138C5B04319157", "crc": "468C1495", "size": 87, "rom_name": "Treasure Strike (Japan).gdi", "description": "Treasure Strike (Japan)", "name": "Treasure Strike (Japan)"}
{"sha1": "980036E44AD9D694EA1699CD05C86CCD0C894C47", "md5": "346FEA58AB1A55C577138C5B04319157", "crc": "468C1495", "size": 87, "rom_name": "Zombie Revenge v1.000 (2000)(Sega)(PAL)(M4)[!].gdi", "description": "Zombie Revenge v1.000 (2000)(Sega)(PAL)(M4)[!]", "name": "Zombie Revenge v1.000 (2000)(Sega)(PAL)(M4)[!]"}

The repeated .gdi files (or maybe all of them) could really use a comment with the game serial or the name or *something* to remove duplicate crcs. I guess it's a upstream problem. I have to ask, is True-rip any different? I know they take up dumps from TOSEC too, but if their gdi files are saner it could be worth rebuilding to use them (not so worth using redump, that has the problems everyone knows with the dreamcast set).

**Comment by RobLoach** [comment]
[metadat/redump/Sega - Dreamcast.dat](https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sega%20-%20Dreamcast.dat) is from [libretro-dats](https://github.com/robloach/libretro-dats).

We unfortunately don't have any serials available for Dreamcast.

**Comment by i30817** [comment]
Redump was noted as dumping dreamcast games wrong and never wanting to change it. It's the whole reason i'm using TOSEC.

**Comment by i30817** [comment]
BTW, almost all games on the Dreamcast tosec-iso database are bitten by the dot bug on the other bug report. TOSEC includes version numbers and they all are of the form 1.XXX even the 1.000 you see.

I find it amazing that no one complained of this bug before, it's very simple to trigger from not compressing games and letting cmpro 'rebuild' a set without compressing.

**Comment by bparker06** [comment]
The last time I looked into scanner support for Dreamcast serials, it appeared that the magic numbers were the same as PSX, and I never went any further than that.

**Comment by i30817** [comment]
So it *is* possible to id based on a header on Track 1 of the game like Saturn games? That's cool and a viable workaround for a 'id'. 

One thing to note is that Saturn games have problems with *that* when different formats exist form the "track 1". Another bug report i opened noted how most Saturn translations all failed at being identified as a saturn game. The reason is simple, the SEGA header (that i recall reading existed on all sega consoles) is at the start on a iso, but not on a bin.

**Comment by i30817** [comment]
Yeah, good call, i just opened a gd-rom dump 'track 1' from TOSEC and a header exists and includes name and version number.

track01.bin                                                                     
0000 0000: 00 FF FF FF FF FF FF FF  FF FF FF 00 00 02 00 01  ........ ........
0000 0010: 53 45 47 41 20 53 45 47  41 4B 41 54 41 4E 41 20  SEGA SEG AKATANA
0000 0020: 53 45 47 41 20 45 4E 54  45 52 50 52 49 53 45 53  SEGA ENT ERPRISES
0000 0030: 44 31 44 38 20 47 44 2D  52 4F 4D 31 2F 31 20 20  D1D8 GD- ROM1/1
0000 0040: 20 55 20 20 20 20 20 20  30 37 39 39 38 31 31 20   U       0799811
0000 0050: 54 33 36 38 31 32 4E 20  20 20 56 31 2E 30 30 30  T36812N    V1.000
0000 0060: 32 30 30 30 31 31 32 35  20 20 20 20 20 20 20 20  20001125
0000 0070: 30 57 49 4E 43 45 4F 53  2E 42 49 4E 20 20 20 20  0WINCEOS .BIN
0000 0080: 20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20
0000 0090: 54 4F 4D 42 20 52 41 49  44 45 52 20 43 48 52 4F  TOMB RAI DER CHRO
0000 00A0: 4E 49 43 4C 45 53 20 20  20 20 20 20 20 20 20 20  NICLES

**Comment by i30817** [comment]
I've been wondering about this.

Can this problem be 'worked around' by treating the dreamcast TOSEC dat especially during scanning?

`struct info = find(crc)` you'd do `struct info = find(crc, filename)` and only return a match if both arguments match? I know it's not ideal, with all of the other machinery of the frontend using the crc as primary key but by treating it especially, you could maybe even replace the DAT crc by something saner after this match, like the crc of the filename string?

**Comment by RobLoach** [comment]
Optimally, it would scan serials first, and then fall back to CRCs. The filename is not a reliable detection method.

**Comment by i30817** [comment]
Why not crc first? Because this (TOSEC Dreamcast) is the only case i've found where the database had duplicate crcs.

Speaking of scanning serials, there is a problem with that on redump sega saturn. As far as i can tell from looking at the code, it only 'finds' the SEGA header if it's a cue/bin. ISO, which doesn't have bit of trash bits before the SEGA header isn't in the search (some translations often require conversion to iso first to minimize download size).

**Comment by RobLoach** [comment]
> Why not crc first?

Getting the CRC of large files takes a long time.

> Seems like this problem is unique to the dreamcast TOSEC set.

RetroArch doesn't implement serial scanning for Dreamcast currently, nor does it have the Dreamcast serial information.

**Comment by RobLoach** [comment]
Going to close this. @bkoropoff has revamped it quite a bit. Test it out, and post new issues accordingly.

**Comment by bkoropoff** [comment]
Note that gdi parsing isn't implemented in RetroArch yet, so you might need to hold off for a few days.  Once that's done the new databases should hopefully do a better job.
