### ISSUE TITLE
new MAME RDBs are not available via online updater

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#472]
Hi @RobLoach - do you know a reason why the new MAME RDBs aren't being pulled into the RA online updater?

Here's what I do:
1. Download the latest RA nightly
2. I start RA then select Update Core Info Files
3. I then select Update Databases

After both downloads/extractions complete, the result is an `info` folder which has all of the new .info files, but the `database` folder does not have the new RDB files.

**Comment by RobLoach** [comment]
https://buildbot.libretro.com/assets/frontend/bundle/database/rdb/

Looks like they arn't being published.

**Comment by markwkidd** [comment]
The buildbot is a new and unknown part of the libretro landscape for me. Do you know what would affect an RDB database being published like this?

**Comment by RobLoach** [comment]
@fr500 found a force push at some point that broke the `git pull`. He replaced git pull with a git fetch && git reset --hard origin . Keep watch!
https://buildbot.libretro.com/assets/frontend/bundle/database/rdb/

**Comment by RobLoach** [comment]
That fixed it! Thanks a lot Radius!
