### ISSUE TITLE
No-Intro NDS Database Is Outdated

### ISSUE THREAD

**Issue by TheKoopaKingdom** [libretro/libretro-database#478]
I have a ROM with a checksum of `23A00DDF` ([NDSTS Screenshot](https://i.imgur.com/BpvDhEq.png)) which matches the checksum for SM64DS USA Rev 1 [here](http://datomatic.no-intro.org/index.php?page=show_record&s=28&n=0056), but RetroArch refuses to scan it. More details about what I've tried to solve this thus far are [here](https://www.reddit.com/r/RetroArch/comments/6lhbpg/cant_scan_in_nds_roms/).

**Comment by RobLoach** [comment]
Looks like it's in there:
```
game (
	name "Super Mario 64 DS (USA) (Rev 1)"
	description "Super Mario 64 DS (USA) (Rev 1)"
	rom ( name "Super Mario 64 DS (USA) (Rev 1).nds" size 16777216 crc 23A00DDF md5 4CED5213F558E297541CB7314C909401 sha1 7BF8A92B259E303899851034D85C531CCDC532E2 )
)
```

Update databases and try again?

**Comment by RobLoach** [comment]
Going to close this. Feel free to re-open if it's still not there after updating the databases.
