### ISSUE TITLE
Scanner doesn't recognize content from Online Updater/Download Content

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#484]
Via RA's Online Updater, I've downloaded a couple of Vectrex ROMs as well as Super Boss Gaiden (Japan) for the SNES and Rick Dangerous.

None of these ROMs is recognized by the playlist scanner.

Also, is the content from the Download Content managed in one of the github repos? I can't figure out where these downloads are coming from.

**Comment by hizzlekizzle** [comment]
They're just sitting on our webserver.

It doesn't surprise me that the SNES ROMs aren't in the databases, since they're ROMhacks, but the Vectrex games are the official public domain set, so they should be legit...

**Comment by RobLoach** [comment]
Rick Dangerous matches the zip:
https://github.com/libretro/libretro-database/blob/master/dat/Rick%20Dangerous.dat

Do we need block_extract? https://github.com/libretro/xrick-libretro/blob/master/libretro/core/libretro-core.c#L146-L155

The `*|zip` also confuses me.

Vectrex - We could add that to the hacks dir:
https://github.com/libretro/libretro-database/tree/master/metadat/hacks

**Comment by markwkidd** [comment]
Since Vectrex is in the public domain, and there is a No-Intro DAT, I've put together a complete set that validates with the latest No-Intro Vectrex DAT (20170417-075732). 

@hizzlekizzle would you consider sliding these into place instead of the current titles?

[GCE - Vectrex (No-Intro 20170417-075732).zip](https://github.com/libretro/libretro-database/files/1155090/GCE.-.Vectrex.No-Intro.20170417-075732.zip)

**Comment by RobLoach** [comment]
1. Upped Vectrex
1. Added Super Boss to the Hacks DAT in a PR
1. Built Rick Dangerous RDB

**Comment by markwkidd** [comment]
Nice! Thanks @RobLoach
