### ISSUE TITLE
Request .dat for chd dreamcast tosec games

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#494]
The reicast upstream supports the format, and it's a natural fit for dreamcast.

This would work around the issues that TOSEC dreamcast set has with duplicates. It would work like this:

While different compression levels give different files, checksums chd format when compressed with chdman, has a stable 'sum' checksum that is the checksum of all the data (all the compressed files). This is stable, as long as the files don't change. Because it is of *all* the data, the .gdi duplicate issue no longer happens. Because it is precalculated, it would be fast to check.

The value is 'data sha1'. It can be got with chdman -info + some regex. I don't know if there is a more granular way, the man page isn't very clear.

```
$ /usr/share/sdlmame/chdman info -i hotel\ mario\ \(1994\)\(philips\)\(eu\)\[\!\].chd 
chdman - MAME Compressed Hunks of Data (CHD) manager 0.187 (unknown)
Input file:   hotel mario (1994)(philips)(eu)[!].chd
File Version: 5
Logical size: 381,770,496 bytes
Hunk Size:    19,584 bytes
Total Hunks:  19,494
Unit Size:    2,448 bytes
Total Units:  155,952
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     119,766,916 bytes
Ratio:        31.4%
SHA1:         f24e118b807bc2479794eaa6cc35526e70be5bf0
Data SHA1:    1b8ab6c535ea39cef5d665a82c83748dfe8c9630
Metadata:     Tag='CHT2'  Index=0  Length=91 bytes
              TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:155950 PREGAP:0 P
```

The hard part, that needs to be done is to create a dat file for the TOSEC dreamcast set, so first we need to find someone that has all of it already compressed to chd, then give them a script to execute that creates the dat with the right 'Data SHA1' value on a field, add it to the dreamcast database, linking the game metadata and then finally modify retroarch to treat 'chd' files specially and not extract a file to get the crc but parse and use the header value to match.

One thing: retroarch should first try to find 'data sha1' on the .chd files; but if it can't find it and just finds 'sha1' it should use it as a fallback. This is because MAME dats use that value as checksum, not the internal one (probably because most external apps don't parse out the internal value and just use sha1 on the whole file). Though i don't really know what the retroarch is doing with the MAME dat. For all i know they're all crcs and the fallback should be crc etc.

**Comment by RobLoach** [comment]
TOSEC doesn't have any CHD information in the Dreamcast DAT. Here's what one of  the Dreamcast entries from TOSEC looks like:

```
	<game name="Crazy Taxi 2 v1.004 (2001)(Sega)(US)[!]">
		<description>Crazy Taxi 2 v1.004 (2001)(Sega)(US)[!]</description>
		<rom name="Crazy Taxi 2 v1.004 (2001)(Sega)(US)[!].gdi" size="87" crc="d7ab4c6b" sha1="9d50b816d3f69ad192f5986ab487769965c2e082" md5="b3ecdf113fd42344dd84142679e4cb36"/>
		<rom name="track01.bin" size="705600" crc="5d97c071" sha1="15de448964d684e0bc51dbed8470eb15b811a687" md5="f4f94c39c2929535f6e72d460262ba72"/>
		<rom name="track02.raw" size="1237152" crc="3ca9db58" sha1="70cdd669be8d70ec6f00f344e7d5e0f9fe0cf7cb" md5="07c2cab45f3f2e701272a68b3521e0f0"/>
		<rom name="track03.bin" size="1185760800" crc="410531db" sha1="858ab545521727433d9e15cb44eb677f1afcfdb4" md5="ec97748719824b8ec45ea42a7692737d"/>
	</game>
```

What you're looking at looks like something from TOSEC's Philips CD-i - Games DAT, or MAME.

**Comment by i30817** [comment]
Yes i know. That's why i opened the issue. It needs some proactiveness to happen and i don't have the full set or anything near it. I'd guess if you built a script that could extract the Data SHA1 (and any other fields that might be useful) and asked around on reddit for someone that has the Dreamcast TOSEC set on chd, you could find someone to help build this.

**Comment by i30817** [comment]
Thinking some more about this, just reproducing whatever calculation chdman is doing to produce Data SHA1 is enough. All the information you need is (likely, not sure) already contained on the .dat as the sha1 of the individual files and could be produced without the set with a bit of luck.

**Comment by RobLoach** [comment]
The scanning of this information has been changed a lot, thanks to @bkoropoff. Requesting some testing of it.

**Comment by i30817** [comment]
You mean you changed the rdb to have bin checksums instead of gdi? At least that seems to be what changed from the rdb file in the repo. 

I can't check that now, because i converted the TOSEC set to chd (compressed really).

**Comment by bkoropoff** [comment]
CHD scanning should now work on nightly builds of retroarch.

**Comment by i30817** [comment]
Maybe it's because i'm using the ppa, but not yet here. The rdb file has no additions, and scanning dreamscast tosec chd files doesn't give any results (in case you're using the SEGA header instead of the DATA SHA1 - which i emphatically suggest because chd has compression levels and can't index 'single files' like the original gdi, which have the already mentioned duplicate problem anyway).

**Comment by RobLoach** [comment]
Going to close this for now. If you find a third-party Dreamcast CHD database, then feel free to post and we can have a look. A bunch of updates have gone in since 2017.
