### ISSUE TITLE
Files with question mark break zip extraction on Windows

### ISSUE THREAD

**Issue by bparker06** [libretro/libretro-database#501]
`cht/Nintendo - Nintendo DS/Are You Smarter Than A 5th Grader? Game Time (U).cht` and similar files with a question mark or other forbidden characters in Windows, are causing the zip extraction within RA to fail halfway through.

**Comment by RobLoach** [comment]
Ah, thought we replaced all those. Thanks for finding. Will be able to fix on Monday if no one else fixes it by then.
