### ISSUE TITLE
Trurip dumps for PC Engine CD unrecognised

### ISSUE THREAD

**Issue by ensra** [libretro/libretro-database#503]
Redump cue files are recognised once they're zipped, but Redump is missing some important titles for the system.

[NEC - TurboGrafx-CD - Games (trurip_XML).txt](https://github.com/libretro/libretro-database/files/1219629/NEC.-.TurboGrafx-CD.-.Games.trurip_XML.txt)

**Comment by RobLoach** [comment]
When RetroArch sees an ISO file, it ignores the CRC and tries to do a Serial check. We'll have to either:

1. Add the Serial numbers to libretro-data and add the TurboGrafx serial detection to RA

or

2. Add the CRC fallback in RA when the serials don't work

**Comment by RobLoach** [comment]
While you're investigating, the compiler for these DATs is over at:
https://github.com/RobLoach/libretro-dats/blob/master/dats.json

Feel free to look through to see if there's any adjustments we could make.

**Comment by retro-wertz** [comment]
zipping the cue-sheet so "import content" can detect it has been a long standing issue. i've posted this a while ago not sure if it was in git or forums.

**Comment by ensra** [comment]
@RobLoach Are the TruRip dats you used to generate the database the latest available (2017-04-15-ish)?

I can't find dats on the official TruRip website which seems to be broken, but they're available on pleasuredome.

From what I can tell the script does not download anything, so the source dats need to be required and placed in the right directory manually, correct?

**Comment by RobLoach** [comment]
Correct, they need to be manually downloaded and set up. To have it download all the DATs automatically, we'd have to write some PhantomJS script or something.

**Comment by ensra** [comment]
RobLoach/libretro-dats#18
