### ISSUE TITLE
rdb, cheats, cursor - makefile needs updating?

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-database#506]
i think the makefile for the related folder needs to be updated since the defaults are now integrated into retroarch which is the following(at least for linux)

cheats - $(HOME)/.config/retroarch/cheats
cursors, rdb - $(HOME)/.config/retroarch/database

**Comment by RobLoach** [comment]
The `make install` process is different than RetroArch's dowload folder. `make install` will do a global install of the files. Useful for something like LibreELEC, where there isn't really a HOME folder.

**Comment by RobLoach** [comment]
When installing, you can also specify where to install.....

```
INSTALLDIR=$(HOME)/.config/retroarch make install
```
