### ISSUE TITLE
Database: invalid names for GoodNES romsets, others might be affected as well...

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-database#517]
... since there seems to be a pattern.

Current DAT/RDB for GoodNES has incomplete names or descriptions. Sample list from link:
https://hastebin.com/ahefogicig.sm

It seems that the names are "cut" from the 1st "." found from the filename and not from the "." right before "nes" or "unf" extension.

**Comment by xTMODx** [comment]
Should be fixed here [https://github.com/libretro/libretro-database/pull/524]

**Comment by xTMODx** [comment]
Can be closed? Or do you still have issues? I have tested it and it works for me.

**Comment by RobLoach** [comment]
Thanks for pushing these up! :+1:
