### ISSUE TITLE
Database FBAlpha: Incomplete merged sets detected...

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-database#531]
another database issue: FB Alpha. from my understanding, current .dat for FBAlpha includes merged and split sets. This worked fine when scanning split sets(not sure if everything was there though), but scanning merged sets, only about 678 is detected out of 1,736.

i recreated split and merge .dat files with dir2dat, merged the files and used libretro-build-database.sh to create the .rdb files and it acted the same. scanning split sets all were detected, scanning merged sets only a few are detected. So, i tried recreating the rdb with just the merge.dat and this time it worked.

So my suggestion is probably do the same thing on FB Alpha the same way mame is organized, meaning to have them on separate folders, separate split and merge set.(this should probably work better than combining them into one .DAT file-although not tested).

Included are merge and split dat files, all verified 0.2.97.42, and torrentzipped. i dont have the bandwidth to fetch the repo so ill just link here .dat files:

Merged DAT:
[FB Alpha - Arcade Games_merged.dat.tar.gz](https://github.com/libretro/libretro-database/files/1358833/FB.Alpha.-.Arcade.Games_merged.dat.tar.gz)

Split DAT:
[FB Alpha - Arcade Games_split.dat.tar.gz](https://github.com/libretro/libretro-database/files/1358836/FB.Alpha.-.Arcade.Games_split.dat.tar.gz)

**Comment by RobLoach** [comment]
I can up them.... We'll completely delete this one, right?
https://github.com/libretro/libretro-database/blob/master/dat/FB%20Alpha%20-%20Arcade%20Games.dat

**Comment by RobLoach** [comment]
It scanned the same because it's using "rom.name":
https://github.com/libretro/libretro-super/blob/master/libretro-build-database.sh#L314

You'll want to update it to use "rom.crc"

**Comment by retro-wertz** [comment]
who did that? joke...

anyways it should be cleaner now if they have separate folders.

**Comment by retro-wertz** [comment]
libretro-super has been updated with using the separated fba folders. tested it works so we can probably move separate .DAT files now into the folders and delete old dat and rdb

thanks.

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/pull/532
