### ISSUE TITLE
Sega 32X games now in Sega Mega Drive / Genesis playlist

### ISSUE THREAD

**Issue by metchebe** [libretro/libretro-database#548]
After updating to RetroArch 1.6.9 and re-scanning roms, my Sega 32X roms appear in the Mega Drive / Genesis playlist. Also, they appear with GoodTools rom tags, which is inconsistent with the normal Genesis entries.

As a side effect, this breaks the thumbnail feature.

**Comment by RobLoach** [comment]
Time to remove GoodTools Genesis?

**Comment by metchebe** [comment]
As a follow up, I now also notice that some SNES translations I have that should appear in 'Nintendo - Super Nintendo Entertainment System Hacks' (verified CRCs) now appear in the regular non-hacks playlist, and with GoodTools rom names and tags (not the ones from libretro-dats, which were used before).

**Comment by RobLoach** [comment]
THink we should just move all GoodTools to *Hacks?

**Comment by RobLoach** [comment]
Which entries appear in the wrong playlists? hat do you expect? Provide some CRC values?

**Comment by metchebe** [comment]
Today with the latest database I generated a 'Sega - Mega Drive - Genesis' playlist which contains the following entries, which I understand should be in a separate 'Sega - 32X' playlist which was not generated:

- Blackthorne (U) (32X) [!] - D1A60A47|crc
- Knuckles' Chaotix (JU) (32X) [!] - D0B0B842|crc

Also, the names I expect are:

- Blackthorne (USA)
- Chaotix ~ Knuckles' Chaotix (Japan, USA)

Hope that helps if this is indeed an issue.

The SNES issue I had mentioned has been solved.

**Comment by kivutar** [comment]
@metchebe can you check again after the update of today please?

**Comment by metchebe** [comment]
Sure, everything looks OK...

**Comment by RobLoach** [comment]
Thanks a lot!
