### ISSUE TITLE
Add PS3 database

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-database#549]
Hi @RobLoach and others, can we start looking into adding PS3 database DATs?

**Comment by RobLoach** [comment]
That would be pretty cool. Do you know of a PS3 database out there that we could source from?

**Comment by RobLoach** [comment]
Can do it with GameTDB through [libretro-database-gametdb](https://github.com/robloach/libretro-database-gametdb). Here's an example of [Ratchet & Clank: QForce on GameTDB](http://www.gametdb.com/PS3/BCAS01594).

Question is.... Does RetroArch scan the serials from these games correctly?
