### ISSUE TITLE
Handheld Electronic Game.dat contains wrong hashes

### ISSUE THREAD

**Issue by ArnoutVerbeken** [libretro/libretro-database#550]
Hello,

I am setting up my Lakka/RetroArch and have downloaded all gameAndWatch zips from the official http://bot.libretro.com/assets/cores/Handheld%20Electronic%20Game/ site.
After unzipping, I noticed that only 1 game is recognized during scan of my folder.

I check the MD5's of the .mgw files and it seems that none of them matches what is in the "Handheld Electronic Game.dat" file.

I don't know where it is coming from, but it might be related with the move of the bot.libretro.com site (as I have read somewhere....).  I also noticed that all files on the bot have changed on 5 december 2017....

**Comment by RobLoach** [comment]
From https://buildbot.libretro.com/assets/cores/Handheld%20Electronic%20Game/ ? Perhaps they're the MD5s of the .zip instead of the file itself?

Mind submitting a new one? clrmamepro's Dir2Dat may do it.

**Comment by ArnoutVerbeken** [comment]
I checked the .dat file.  It contains the extracted .mgw-names.  So I downloaded once more one by hand, extracted the zip and checked the md5 of extracted mgw file which was in the zip.
No match....

You want me to do that submitting thing?  Teach me how (or give me some usefull link to start from and I'll give it a go.....)

**Comment by ArnoutVerbeken** [comment]
I think I have created a new good .datfile with the Dir2Dat.

Now teach me how to submit...

And how I can test this on my own system....

**Comment by RobLoach** [comment]
Haha, we both did it at the same time :smile: Mind checking https://github.com/libretro/libretro-database/pull/551

**Comment by ArnoutVerbeken** [comment]
OK, perfect.  I compared your new file with my new file.  We both have same hashes, so looks OK.

Now how do I get this new dat on my system? Or do I have to wait for a new Lakka release?

**Comment by RobLoach** [comment]
You'd have to pull the branch in, re-build the databases, and then put them on your system. Alternatively, we just merge, and update the RDBs here.

**Comment by ArnoutVerbeken** [comment]
Can't I just copy the dat over to some local directory?  I see that I need RDB's apparently in /tmp/database/rdb.
Well, would love such a new RDB in that case to drop in tempdir.

**Comment by geekycow** [comment]
Hi

Sorry to be a pain, but  this probably needs opening again.

Nintendo Game & Watch  Donkey Kong and Donkey Kong II have both since been updated (at least twice) at the official site, but the .dat remains out of date.  These two systems seem to be getting rebuilt every few months and the official archive not having copies of the older ones.

**Comment by geekycow** [comment]
If it helps, I think this change should do it-

`-	rom ( name "Donkey Kong (Multi Screen).mgw" size 594686 crc 74cb502d md5 d6abdb020e3e157ec84a1671e122f1f4 sha1 8c812ca6e0a243919303751bcaeb7cf1ce03bb6f )
+	rom ( name "Donkey Kong (Multi Screen).mgw" size 593813 crc 1861ccb5 md5 4e9ad170823d48d9125a3165043fa246 sha1 fa2a82a4e0a3c64a8ef7543a2500e405ce003853 )

-	rom ( name "Donkey Kong II (Multi Screen).mgw" size 724108 crc 3f106a11 md5 4932e7169bd84fe8584701777ebc1697 sha1 81311c9b9c54022f073691f4a9574f1277de9fc8 )
+	rom ( name "Donkey Kong II (Multi Screen).mgw" size 723205 crc fcf3e1c3 md5 82a6e21b12179caf1cfdc6f1767a1c28 sha1 526a22e719b004f2a3b6d428683995e5dd961dce )
`

**Comment by geekycow** [comment]
Sorry, do know how to submit a change, but this should do it-

[changes.txt](https://github.com/libretro/libretro-database/files/3329284/changes.txt)

**Comment by geekycow** [comment]
Not done this before: I think I've submitted a pull request to update the database with the latest changes?

#897
