### ISSUE TITLE
scanner doesn't recognize ColecoVision ROMs (No-Intro)

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#560]
The scanner and database aren't recognizing a set of ColecoVision ROMs that I have successfully scanned with the official no-intro DAT dated 2014-08-03 05:59:13.

I also successfully scanned these ROMs with the ColecoVision No-Intro DAT that is mirrored in this repository. 

I've tried scanning them zipped and unzipped on two different systems.

**Comment by RobLoach** [comment]
Looks like no info file references the `Coleco - ColecoVision` database. When I run the following:

**Comment by RobLoach** [comment]
Found it... You need to copy the contents of https://github.com/libretro/blueMSX-libretro/tree/master/system/bluemsx to your BIOS directory.

**Comment by markwkidd** [comment]
Thanks for taking a look at this and submitting the PR @RobLoach!
