### ISSUE TITLE
adding Matell Intellivision to the database

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#563]
A new libretro core for Mattel's Intellivision is now available: https://forums.libretro.com/t/any-cores-for-colecovision-and-intellivision-consoles/13040/10

No-Intro does not provide a DAT for Intellivision, but TOSEC does. @RobLoach what do you think about adding Intellivision to the database, sourced from the latest TOSEC DAT release? https://www.tosecdev.org/downloads/category/41-2017-11-01

**Comment by RobLoach** [comment]
@markwkidd Great idea! Need to do a few things...

- [ ] Add the info file to https://github.com/libretro/libretro-super/tree/master/dist/info
- [ ] Add the TOSEC source to https://github.com/robloach/libretro-dats
- [ ] Add the built DAT to https://github.com/libretro/libretro-database
- [ ] Add the RDB building to https://github.com/libretro/libretro-super/blob/master/libretro-build-database.sh
- [ ] Compile and add the RDB to https://github.com/libretro/libretro-database
