### ISSUE TITLE
no RDB for Mattel - Intellivison

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#569]
It doesn't seem that an RDB for the new Intellivision DAT is generated here: https://github.com/libretro/libretro-database/tree/master/rdb

Aside: I feel that there is about 10% of this database system that I just can't wrap my head around, or else I would fix this myself.

**Comment by RobLoach** [comment]
I think we just need to re-build the RDBs. Would love to automate that on Travis one day...

Made a PR to add some RDB build docs:
https://github.com/libretro/libretro-database/pull/570

**Comment by markwkidd** [comment]
@RobLoach is there perhaps one more step in the process?

When I invoke the script to generate the RDB files I receive an error message in this format, seemingly for every error:
```
=== Building RPG Maker ===
./libretro-build-database.sh: line 218: /home/mark/libretro-super/retroarch/libretro-db/c_converter: No such file or directory
```

**Comment by RobLoach** [comment]
@markwkidd Check the build logs for c_converter. Should be able to figure out what went wrong there.
