### ISSUE TITLE
Content Downloader: Mattel - Intellivision

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#571]
As Intellivision support continues to move forward, could I propose adding selection of freeware Intellivison ROMs to the content downloader?

Some candidates:

- 4-Tris (GPL) http://spatula-city.org/~im14u2c/intv/4-tris/
- Doom (DSL) http://spatula-city.org/~im14u2c/intv/doom/
- Space Patrol (CC-NC) http://spacepatrol.info/
- Pong (GPL - mistakenly listed PD by archive.org) https://archive.org/details/intv_Pong_1999__PD
- Crazy Clones (GPL - mistakenly listed as PD) https://archive.org/details/intv_Crazy_Clones_1981__PD

**Comment by RobLoach** [comment]
My vote is in for 4-Tris. As it's GPL, with the source available, and the author has said we can share it.

**Comment by markwkidd** [comment]
Agreed about 4-Tris!

I've found one more title that is pretty sophisticated and is offered with essentially a public domain license:

Christmas Carol vs. The Ghost of Christmas Presents: http://www.carolvsghost.com/pg_game.html#download-rom

 "...we are offering the Christmas Carol game ROM **absolutely free**—with no strings attached! 
There is **nothing to purchase, no registration, and no copy protectio**n. This is every bit the game available for sale, with all levels, characters, and animation sequences; just without the physical media and collectible box. **Download the game, play it, enjoy it, share it**—and over all, have a great time."

**Comment by RobLoach** [comment]
Added one of them. We could consider others, but this is a good start.
