### ISSUE TITLE
Sony - PlayStation.lpl conflicts 

### ISSUE THREAD

**Issue by Noiseko** [libretro/libretro-database#572]
The redump dat set has hashes for the bin and cue files however these aren't used by retroarch to match the roms?

```
<game name="Threads of Fate (USA)">
     <category>Games</category>
     <description>Threads of Fate (USA)</description>
     <rom name="Threads of Fate (USA).cue" size="87" crc="009cfc2e" md5="33dfd831427e04229f0d307f4f51a39c" sha1="c055fc0410717a3615c3566b057a729c94215369"/>
     <rom name="Threads of Fate (USA).bin" size="357454608" crc="59b2f8a3" md5="bf49e5e7a09acc46625b5ced33dd45f5" sha1="375e4a344c4feef969bef6042ff1f90e350fa5d5"/>
  </game>
 <game name="Urban Chaos (USA)">
     <category>Games</category>
     <description>Urban Chaos (USA)</description>
     <rom name="Urban Chaos (USA).cue" size="83" crc="7632573f" md5="a9fa97c60f774d9b90aae4aaa04b17fd" sha1="6effedb519572cd1bf55380c4aeebbd8c1b5a3e1"/>
     <rom name="Urban Chaos (USA).bin" size="616096992" crc="239c0746" md5="c9b4e03de8dd5c1fb799fc56e5cf031a" sha1="f6608f6ec4128366161f1aa99c6a8b69d76150fe"/>
</game>
```

retroarch seems only to index the cue files and doesn't hash them, this has a conflicts e.g. Urban  Chaos
```
./Threads of Fate (USA).cue
Threads of Fate (USA)
DETECT
DETECT
00000000|crc
Sony - PlayStation.lpl

./Urban Chaos (USA).cue
Threads of Fate (USA)
DETECT
DETECT
00000000|crc
Sony - PlayStation.lpl
```
Is this due to 'Threads of Fate' and 'Urban Chaos' having the same serial in the dat?
https://github.com/libretro/libretro-database/blob/29ecb40c637bb0b646f4c9275a62880ef44dac04/dat/Sony%20-%20PlayStation.dat#L49792  

This is my output from attempting to read the serials, I'm unsure of an intended method but this seems to show that the serials are close enough to conflict?

```
strings ./Threads\ of\ Fate\ \(USA\).bin | grep -i slus-01019
BASLUS-01019-DP
strings ./Urban\ Chaos\ \(USA\).bin | grep -i slus-01019 
PLAYSTATION                     SLUS-01019                      
BASLUS-01019URBANSV
```

Sorry if this is intended functionality of the database

**Comment by RobLoach** [comment]
Redump has the correct values, and they seem okay in our dat:

Threads of Fate SLUS-01019
http://redump.org/disc/158/

Urban Chaos SLUS-01091
http://redump.org/disc/2329/

With serial/media data, RetroArch doesn't write the CRC data to the playlist, which is unfortunate. The serial scanning is always kind of weird, but needed, as getting CRC data from large files is VERY SLOW.

**Comment by Noiseko** [comment]
Do you know why my copy of Urban Chaos which maches redumps hashes, however the serial is still matched to be  'SLUS-01019' and not 'SLUS-01091' making it colide with Threads of Fate?

sha1sum ./Urban\ Chaos\ \(USA\).* 
> f6608f6ec4128366161f1aa99c6a8b69d76150fe  ./Urban Chaos (USA).bin
6effedb519572cd1bf55380c4aeebbd8c1b5a3e1  ./Urban Chaos (USA).cue

from redump
>f6608f6ec4128366161f1aa99c6a8b69d76150fe *Urban Chaos (USA).bin
6effedb519572cd1bf55380c4aeebbd8c1b5a3e1 *Urban Chaos (USA).cue

**Comment by Noiseko** [comment]
setting the title in my playlist to 'Urban Chaos (USA)' make retroarch display the correct serial, However scanning the cue file is incorrect

**Comment by i30817** [comment]
serials are (nearly) always the name of the executable with dots replaced by '-' or emptyspace. You can just mount the games to find out the serial your game is supposed to have.

My guess is that your dat is just wrong.

**Comment by i30817** [comment]
Edit: i dowloaded it and you're right. Apparently there was a misprint on one of these games and the serial is the same. I think this will need to be differentiated differently.

**Comment by kivutar** [comment]
So the official CD of the game had a wrong serial in it?

**Comment by i30817** [comment]
Yes, there was a misprint in urban chaos where the last 91 was switched to 19.

**Comment by RobLoach** [comment]
When running, RetroArch should report the serial that was found. Mind posting that? Another thing you could do is create a post on the Redump forums. We roll with what they provide.

In the mean time, I'm going to close this one.
