### ISSUE TITLE
no-intro roms no longer scanned

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#574]
I hesitate to post this because it's been going on for me for months, and because no one else seems to experience it. Can it really just be me?

However, I can not scan No-Intro validated console ROMs for any system on my new (as of late 2017) Windows 7 system.

I have access to No-Intro ROMs validated in January 2016 as well as a set validated in December 2017. 

I can successfully scan Mattel Intellivision ROMs and MAME 2003 ROMs with this setup. Coincidentally those DATs were created in part by me. More significantly, maybe, they aren't No-Intro. 

I'm using Windows 7 x64 and I've tried stable, nightly, and self-compiled RetroArch executables.

**Comment by RobLoach** [comment]
Could you share one of the CRC values from one of the No-Intro roms that doesn't scan? Is it in a zip file? I could test here with similar values.

**Comment by markwkidd** [comment]
Great, that's perfect.

To pick one arbitrarily, Sega - 32X/Blackthorne (USA)

I've tried scanning a torrentzipped copy as well as an unzipped copy.

    File: Blackthorne (USA).32x
    CRC-32: d1a60a47
    MD4: 614ecbe46a41278289bc62f89df29601
    MD5: c238b112113b0297b2b9f4f618d56598
    SHA-1: 4bf120cf056fe1417ca5b02fa0372ef33cb8ec11

**Comment by RobLoach** [comment]
Serial media if iffy. I'm not sure RetroArch has implemented serial detection for 32X discs.

**Comment by markwkidd** [comment]
I've positive I've successfully scanned this set before -- Sega 32X is cartridges btw. Although there were 32X-enabled Sega CD titles as well. 

Anyway, if you're still willing @RobLoach  would you try a common SNES title instead?

    File: Aladdin (USA).sfc
    CRC-32: 124d8e4d
    MD4: 46c4f17c30ae08fe695385c2260adcf3
    MD5: 8e00910312b30663768d907114d301c2
    SHA-1: bd5fea18ce7456cc0231a39473927d8ea9c6589b

**Comment by RobLoach** [comment]
SNES Worked here....

![screenshot at 2018-02-17 17-13-37](https://user-images.githubusercontent.com/25086/36346111-f3e9de68-1405-11e8-89a5-6251b2ad0e3a.png)

The DBs could do with a full update. Perhaps I'll get to that tonight.
