### ISSUE TITLE
Final Burn Alpha Playlist Mislabeling Issues

### ISSUE THREAD

**Issue by mojohand88** [libretro/libretro-database#582]
I’m having some issues when scanning directories in Retroarch and creating a playlist for Final Burn Alpha. I've posted over on the libretro forums asking for  help and was advised to post my issue here.

Several archives are being mislabeled in the playlist and show up with the wrong titles. I’ve tried manually deleting the playlists, updating database files, re-scanning, etc, and still the problem persists.

Checking inside my playlist file it seems that there are issues with the following archives: thegladpcb.zip, svgpcb.zip, nspirit.zip, goldnaxe2.zip, which are all being mislabeled as Zupapa!

**Comment by mojohand88** [comment]
Another user has posted on the Libretro forums having the same issue but his archives were being mislabeled as _Zero Wings_. So I tried experimenting by removing the _Zupapa_ archive and re-scanning and received the same results only this time the very same archives were mislabeled as _Zed Blade_. So, it seems to be some kind of bug which mislabels certain archives as with whatever the title of the last archive in the directory.

It may also be relevant to note that I only encountered this issue after updating to the latest stable release of Retroarch v171 and re-scanning my directories. Perhaps it's a bug with Retroarch's scanning feature and not an issue with the database files?

**Comment by retro-wertz** [comment]
i can only scan 1 game now from my merged sets, and i was the one who updated this database to be compatible with latest fba. dunno what is happening to this now.
(running linux)

**Comment by RobLoach** [comment]
Could do with an update. Do you know what the source is?

**Comment by retro-wertz** [comment]
i have just tested using windows and linux and i dont see this problem during scanning with latest commits of retroarch and database(though fbalpha fba hasn't updated since 4 months ago)...

**Comment by RobLoach** [comment]
Feel free to re-open if this is still an issue. The DB has been updated a few times since last year.
