### ISSUE TITLE
Hacks

### ISSUE THREAD

**Issue by kivutar** [libretro/libretro-database#590]
This file https://github.com/libretro/libretro-database/blob/db65621603847df1dc0e27b0f5d98c61a6be49cf/metadat/hacks/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System%20Hacks.dat

should be renamed without the `Hacks` in the end.

If not, a separate playlist will be created

**Comment by RobLoach** [comment]
Good find... I think it was adopted because GoodSNES was clogging up the SNES database, so we split everything out into hacks. But it makes sense to bring this file back in.

Thanks!

**Comment by twinaphex** [comment]
Sorry but I fundamentally disagree. Let it be in a different playlist then with Hacks at the end, I don't care. I don't want all this stuff in the main list for SNES.

Maybe split up the GoodSNES entries to a separate database if you must, or rename Hacks to something else like GoodSNES, I don't really care. All I know is that I don't want all these cluttered, messy entries to appear in the same list as the No-Intro entries.

**Comment by kivutar** [comment]
OK then we will need icons for these new playlists.

IMO we should keep RDBs consistent: SNES stuff goes with SNES stuff, whenever it's a hack or not. Then on the presentation layer, or at scan time, we let people build lists or filter entries based on criteria like region, hack, demo.

But for now it's OK to separate them at the database level because we don't have the logic to do it on the menu side.
