### ISSUE TITLE
WonderSwan & WonderSwan Color got merged

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-database#608]
WonderSwan & WonderSwan Color got merged, is it on purpose? Game Boy & Game Boy Color are separated for example

![screenshot_20180409-012208](https://user-images.githubusercontent.com/5431285/38479301-8d982eba-3b94-11e8-8132-9df9f6a91d2d.png)

Btw, what's that [M] [!] ? Is it from no-intro?

**Comment by RobLoach** [comment]
This is an example where GoodTools don't match what we expect. You can see it here:
https://github.com/libretro/libretro-database/blob/e075854a5d07673f16cb0a2763300747424a6add/metadat/goodtools/Bandai%20-%20WonderSwan%20Color.dat

Made a PR to remove it: https://github.com/libretro/libretro-database/pull/609

**Comment by RobLoach** [comment]
Split them into two, and cleaned the titles. Should be up fro the next DB update.

**Comment by RobLoach** [comment]
If you do a database update, you should see the GoodWSx files are now sorted, and look cleaner.
