### ISSUE TITLE
Nintendo - Wii Hacks

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#612]
I'm mostly thinking of undubs and the two translations, but it could also be used to collect scrubbed redump metadata.

Trouble is, that metadata is no-where. There is in fact nNASOS scrubbed redump '.iso.dec' DAT files, and super recent too, but this is a bit useless because '.dec' is not supported by dolphin (unlike a 'normal' scrubbed iso). 

edit: removed misleading paragraph here about viability of .dec as a native dolphin format.

I'm willing to provide md5sums scrubbed and not for the 'Fatal Frame 4 - Mask of the Lunar Eclipse' which is the main Wii translation (besides opoma re-localization) that unfortunately used a runtime patcher and thus had to be hacked into the disc manually (so there isn't a 'official' translation md5sum) and 'Arc Rise Fantasy (USA) (Undub)' and 'Pandora's Tower (USA) (Undub)' too.

**Comment by RobLoach** [comment]
Feel free to add them to a [https://github.com/libretro/libretro-database/tree/master/metadat/hacks](`metadat/hacks/Nintendo - Wii.dat`). If the sources are built elsewhere, it makes it easier to re-construct them.
