### ISSUE TITLE
Scheme for more efficient database lookups of hacks.

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#633]
Now that several consoles are using serial to associate metadata, checksums are falling a bit by the wayside.

This is a problem for hacks, because they tend to have the same serial (attention, this is *tend* to have, some smartass hackers modify these ids), which causes them to naturally be confused by the original game on retroarch.¹

This is prevalent mostly on cd consoles, both because the companies tended to have their act together about serials by then and because for retroarch the very worst case is having to calculate a crc of a iso (if not a zip, which stores that information).

So how can we have the cake and eat it with minimal performance impact when possible? I was envisioning a two phase search for RA on the main path.

1. first search for found serial on a secondary 'serial' hack database.
    a. if there is one or more entries with that serial, this means they have to be distinguished, you can make several filters, but the one that matches uniquely (CRC) applied to the (probably very small) collection returned on 1.a should be enough. CRC has to be calculated on these circumstances if not available from a zip or if *every* single hack modified the size (which is unlikely to say the least).
2. if not found on either of the above branches, this means that a hack doesn't exist for this game, you can search it on the main serial database and proceed as normal now.

For platforms that use checksums still, nothing important changes except the hack database is also searched (first or later, at will since a checksum is unique).

What does this require? The hack database to be separate from the main database, RA scanner to be slightly modified to perform that two phase search, and the hack entries on it to have a 'serial' field like the normal games have. 

This last is not so bad, because of the way i'm currently creating the hack entries with [rhdndat](https://github.com/i30817/rhdndat) already has the option of checking the source rom with redump/no-intro xml databases (when the original rom is available) so this is possible on the vast majority of cases automatically. 

Or i can simply extract it [with another script i did a while ago.](https://gist.github.com/i30817/f58c7f904fe44c4599a6c9d48a60bce0) (warning, this script is currently not working for nintendo cd, psps (unimplemented) or most sega cd consoles (because the serial there appears to be very inconsistent. I was instead trying to checksum the whole SEGA header (not just the serial) because that seems consistently placed, but if you prefer your method you could help programming it there). 

I'd prefer the second method because it wouldn't require a revert patch for the hack, which i often don't have for the recent consoles because their use of cryptography and compression makes these patches huge.

What do you think, should we try something like this? Another advantage of a scheme like this, is that it makes it very easy to disable the hack database if the user 'doesn't want to pay for it'.

¹This kind of parallels the situation with softpatching, where the hack is picked up as the original game, but in my 'idealized' solution that would have a slightly different orthogonal solution (a softpatching VFS that presented both files as a single rom).

**Comment by RobLoach** [comment]
It's not the database that's slow, it's the file scanning. See this go experiment that kivutar put together:
https://github.com/kivutar/go-libretro-scan

It runs much faster than RetroArch's. It is missing some features, but it is a good experiment to test performance.

**Comment by i30817** [comment]
If you need to create a CRC (not reuse one from a zip) of course that's the slowest part. The complaints about database size on the PRs for the snes and nes hacks lead me to this scheme, where it's completely optional to have the hacks affecting the database search. 

Because if the complaints are about the CRC, and *only* hacks need crc (on at least some platforms that use serial currently) making it opt-in removes the 'it's too expensive' idea.

**Comment by RobLoach** [comment]
Nice work on adding a bunch of these. Going to close this for now.
