### ISSUE TITLE
sfiii3n not detected for fbalpha playlist

### ISSUE THREAD

**Issue by schrock** [libretro/libretro-database#636]
I have what looks to be a proper zip file (`sfiii3n.zip`) containing the rom files for `Street Fighter III 3rd Strike: Fight for the Future (Japan 990608, NO CD)`. It is an unmerged romset. It is detected properly by FB Alpha v0.2.97.42, and clrmamepro detects it properly using the DAT file generated by FB Alpha v0.2.97.42 (`FB Alpha v0.2.97.42 (ClrMame Pro XML).dat`). The game plays fine when loaded manually in Retroarch v1.7.2, but the playlist scan does not detect it. In fact, it's the only game in my handful of arcade games that is not detected properly by the Retroarch scan.

I'm not familiar with how the final fbalpha dat is built, but it looks like you use a script to generate it from some meta files. The only reference I found to sfiii3n for fbalpha in this repositority was in `metadat/fba-split/FB Alpha - Arcade Games.dat`:
```
game (
	name "Street Fighter III 3rd Strike: Fight for the Future (Japan 990608, NO CD)"
	year 1999
	publisher Capcom
	rom ( name sfiii3n.zip size 132348 crc 43a14657 md5 06f49ed213b523eb6d7bb4b7adc84cc3 sha1 e7fb9551e425af16e56a05fcd46ac9d1a99c9d3e )
)
```

From within Retroarch, it looks like there is an entry in the rdb for `Street Fighter III 3rd Strike: Fight for the Future (Japan 990608, NO CD)`, so I'm wondering if the checksums are wrong in this entry.

**Comment by retro-wertz** [comment]
dat files are still not updated to 0.2.97.43

**Comment by schrock** [comment]
I'm finding some additional problems with my other arcade games. They are detected, but as the wrong region. Again, I think the files themselves are correct given how FB Alpha and clrmamepro detect them, so there must be an issue with the fbalpha database in Retroarch. I'm going to compile the dat files and attempt to figure out what's going on.

**Comment by RobLoach** [comment]
@retro-wertz mentioned he could go through and update the DATs. Would be good to clean these ones up :+1:

**Comment by schrock** [comment]
It looks like I made some bad assumptions. I was attempting to use non-merged roms with FB Alpha in Retroarch, but it looks like a non-merged database is not currently implemented, only split and merged, even though non-merged roms are supported by the FB Alpha core itself. I will investigate some more...

**Comment by schrock** [comment]
OK. I made some more progress, and I still think something is wrong. This time I used sfiii3n.zip from a MAME 0.185 split romset, double-checked it was properly torrent-zipped, and used FB Alpha v0.2.97.42 and clrmamepro to verify it as correct. This rom was still not properly detected by the FB Alpha core in Retroarch. 

However, if I have the MAME core installed in Retroarch, sfiii3n.zip is properly detected by a scan - but as a MAME game, rather than an FB Alpha game. I took a look at [MAME.dat](https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/mame/MAME.dat), and it appears it has two entries for sfiii3n.zip. I'm not sure what the first one is, but the second one corresponds to my copy of sfiii3n.zip, based on the size and sha1sum.

```
game (
	name "Street Fighter III 3rd Strike: Fight for the Future (Japan, 990608, NO CD)"
	year "1999"
	developer "Capcom"
	rom ( name sfiii3n.zip size 66187177 crc 561be14a md5 b2e427a4550bd8e9103767225933ee07 sha1 6f591c8f210b7eaa7e52a9174862164ceb64bec7 )
)

game (
	name "Street Fighter III 3rd Strike: Fight for the Future (Japan 990608, NO CD)"
	year "1999"
	developer "Capcom"
	rom ( name sfiii3n.zip size 70592168 crc 37f0b2f0 md5 96f3b60ef840ef5569ba2f5ace32aea0 sha1 3b7a50d7bcd6eea8645497e73a6a311afc5fe0af )
)
```

If you compare that to the entry in the [fba-split metadat](https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/fba-split/FB%20Alpha%20-%20Arcade%20Games.dat) (see my first comment in this thread), you'll notice that it doesn't match. In fact, the size for sfiii3n.zip in the fba-split metadat is way too small.

I can only assume, at this point, that the fba-split metadata was generated from an incorrect romset or that there is a bug in the [FBA_dat_gen.py](https://github.com/libretro/libretro-database/blob/master/scripts/FBA_dat_gen.py) script. I am going to try to use that script to generate a new dat for FB Alpha. If I can get something proper, I will open a pull request for it. However, I still don't understand how the FBA metadats in this repository were generated, as FBA_dat_gen.py only seems to only generate a single dat file for what I assume to be the fba-split romset. Is there another tool used to generate the separate fba-member and fba-merged dats?

**Comment by schrock** [comment]
Argh. I think I realize what I'm doing wrong. The FB Alpha romset seems to have some serious differences in structure compared to MAME. I thought clrmamepro was detecting the romset as correct, but I didn't scan it correctly, and now it's finding problems. I guess it's too much to ask the devs of FB Alpha and MAME to use the same romset conventions.

**Comment by schrock** [comment]
I'm closing this issue, as there seems to be no problem. Once I got a proper romset in the format expected by FB Alpha and torrent-zipped it, Retroarch detects it properly. I'm sorry for the confusion.
