### ISSUE TITLE
Famicom disc system roms wont scan

### ISSUE THREAD

**Issue by kcin2001** [libretro/libretro-database#638]
despite the rom's crc matching up with the database files (which i made sure to update) and the content wont scan both unzipped and zipped roms wont work

**Comment by kcin2001** [comment]
ok they all start scanning if i change my folder's name from "Nintendo - Famicom Disk System" to "Nintendo - Family Computer Disk System"

**Comment by markwkidd** [comment]
That is useful information but the new bug is just as strange as what the old bug seemed to be

**Comment by kcin2001** [comment]
There is 2 databases with one being named the same a s the old folder but some of my roms even matched that db

**Comment by RobLoach** [comment]
Delete your rdb folder, and re-download it... Just removed the duplicate from the source db.

**Comment by kcin2001** [comment]
Ok

**Comment by RobLoach** [comment]
Get it working? Feel free to re-open the issue the problem persists. Three things you need...

1. Core downloaded
2. .info files downloaded
3. Scan the files
