### ISSUE TITLE
(Sufami Turbo) Remove entries from Nintendo - Super Nintendo Entertainment System

### ISSUE THREAD

**Issue by Rocklima2** [libretro/libretro-database#668]
Please could remove the Sufami Turbo roms from this ( Nintendo - Super Nintendo Entertainment System.rdb ) database, to solve the problem when scanning Sufami roms.

**Comment by RobLoach** [comment]
Hmmm, know where/how these are being added? What's an example of a Sufami Turbo rom that's doing this?

**Comment by Rocklima2** [comment]
example of a sufami roms.

Bisyoujyo Senshi Sailor Moon S - Fuwa Fuwa Panic 2 (J) (ST)
Crayon Shin Chan - Nagagutsu Dobon (J) (ST)
Gekisou_Sentai_Car_Rangers_(J)_(ST)
Gegege no Kitarou - Youkai Donjara (J) (ST)
Poi Poi Ninja World (J) (ST)
SD Gundam Generations (A) 1 Nen Sensouki (J) (ST)
SD Gundam Generations (B) Guripus Senki (J) (ST)
SD Ultra Battle - Seven & Ultraman (J) (ST)
SD Ultra Battle - Seven Densetsu (J) (ST)
SD Ultra Battle - Ultraman & Seven (J) (ST)
SD Ultra Battle - Ultraman Densetsu (J) (ST)

**Comment by Wacko22** [comment]
Should SatellaView (BS) games also be removed from GoodSNES?
