### ISSUE TITLE
nes roms set for MAME are not scanned

### ISSUE THREAD

**Issue by legluondunet** [libretro/libretro-database#669]
Hello,

I tried to scan NES Roms set for Mame with retroarch without success. It only recognized less than 10 roms.
Could you update the database please? i can help you and give you necessary data.

Regards.

**Comment by RobLoach** [comment]
NES set for MAME? Is this part of the MAME database?

**Comment by legluondunet** [comment]
In fact the MAME Nes roms set is include in a global set named "Software List ROMs (split)"

**Comment by legluondunet** [comment]
I added the Mame “hash” folder in the “.config/retroarch/system/mame” folder and Retroarch now scan correctly the MAME Nes roms set. I didn't know Retrarch uses now Mame softlist to scan Mame Nes roms set.
