### ISSUE TITLE
Open emu doesn't read sega saturn games (.cue .bin)

### ISSUE THREAD

**Issue by xavabalos** [libretro/libretro-database#687]
Hello everybody,

Problem: my open emu doesn't read Sega Saturn games (.cue .bin). I drop them as I saw on a few tutorial on-line (like I do with other platform such as Genesis, SNES, GBA...) but it doesn't work. 
On the left corner appears (but not always) a loading bar but nothing happens at the end. I've already downloaded the BIO.

I appreciate any suggestions.

Regards,
Xavier

**Comment by hizzlekizzle** [comment]
OpenEmu? This repo is for libretro.

**Comment by RobLoach** [comment]
On a related note, did some investigation into how RetroArch reads the CRCs from GDI files:
https://github.com/RobLoach/libretro-dats/issues/26

Unclear how it decides which file to index.

**Comment by xavabalos** [comment]
Sorry guys for the inconvenient and thank you all
