### ISSUE TITLE
Spectrum Cheat Files

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#695]
Create a script to download and convert all the .pok files to RA format over at:
https://github.com/eklipse2009/all-tipshop-pokes

1. Go through each file
2. Scan the cheats.... 
3. Follow the following output...

### Input
https://github.com/eklipse2009/all-tipshop-pokes/blob/master/c/CORE%20(1986)(A'n'F).pok
```
NInfinite battery
Z 8 40408 0 0
NFreeze Enemies
Z 8 40974 201 0
NNo Enemies
Z 8 41151 201 0
Y
```

### Output
```
cht/Sinclair - ZX Spectrum +3/CORE (1986)(A'n'F).cht
```
```
cheats = 3 

cheat0_desc = "Infinite battery"
cheat0_code = "Z 8 40408 0 0"
cheat0_enable = false 

cheat1_desc = "Freeze Enemies"
cheat1_code = "Z 8 40974 201 0"
cheat1_enable = false 

cheat2_desc = "No Enemies"
cheat2_code = "Z 8 41151 201 0"
cheat2_enable = false 
```

@leiradel Is that right?

There are cases where the cheat could have multiple codes:
https://github.com/eklipse2009/all-tipshop-pokes/blob/master/c/Castle%20Master%20II%20-%20The%20Crypt%20(1990)(Incentive).pok

**Comment by leiradel** [comment]
Some cheats have multiple codes, i.e.

```
NLives
M 8 36168 175 0
Z 8 45954 104 0
```

So maybe output this:

```
cheat0_desc = "Lives"
cheat0_code = "M 8 36168 175 0\nZ 8 45954 104 0"
cheat0_enable = false 
```

**Comment by leiradel** [comment]
The POK format is described [here](http://www.worldofspectrum.org/POKformat.txt).

**Comment by RobLoach** [comment]
Thanks! Going to close this for now. Feel free to ping if you'd like a tester!
