### ISSUE TITLE
(MAME) Missing database for Mame2016 / romset 0.174

### ISSUE THREAD

**Issue by 5schatten** [libretro/libretro-database#703]
The core of [mame2016](https://github.com/libretro/mame2016-libretro) relies on romset 0.174 but the database for this core is still missing and so it's not possible to scan and generate a playlist for this core.

**Comment by hong620** [comment]
i've manually make temporal playlist from [this tool](https://forums.libretro.com/t/retroarch-playlist-buddy-playlist-and-thumbnail-generation-app/8417/46).

but honestly 5shatten's says right. we need a mame 2016.rdb base on 0.174 romset for nearest frozen mame core.

**Comment by RobLoach** [comment]
If you create a DAT of the 0.174 set that's torrentzipped, I'd really appreciate it! Don't have those files on me myself.

**Comment by 5schatten** [comment]
unfortunately I wasn't able to obtain a 0.174 romset. I've got a "patched" up 0.161+ romset as hong620 but it does not really work well.

**Comment by hong620** [comment]
i've wipe out former ones and then ready on Proper(i guess) 0.174 set now.
how should we do to proceed to make rdb for it? any specific manual or specific DAT file for make it? not just a rom set?

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database#building

Will need this diff https://github.com/libretro/libretro-super/pull/903

**Comment by hong620** [comment]
dang.. i'm much noob in linux and sw.. would be hard on just my own knowledges.
i'll send back up strategy on email, i hope somebody can hold it by himself. 😿

**Comment by 5schatten** [comment]
https://github.com/libretro/libretro-database/pull/799
