### ISSUE TITLE
Dat file specs

### ISSUE THREAD

**Issue by undeadindustries** [libretro/libretro-database#705]
Sorry, wasn't sure where else to ask this and get a correct answer.

What is the specific schema of these dat files?

I'm currently writing a ROM organizer and I have the XML part complete. But I can't find the "type" of dat files that Libretro uses. ie: using parenthesis 
```
game (
	name "005"
	year "1981"
	developer "Sega"
	rom ( name 005.zip size 29769 crc d123fe67 md5 64ba2c1869a491bdae1384d3a95c2027 sha1 aeebfd4a3a6214e6efed19dd4d5716215e253b13 )
)
```

I'm specifically looking for a lib that would help me parse these so I don't need to re-create the wheel.

Thanks!

**Comment by undeadindustries** [comment]
NM. I sorted it out.

**Comment by RobLoach** [comment]
That's correct. It's an informal format that has been used for years. Unsure if it's been officially documented or specced out. The best documentation that I've seen is...
https://github.com/SabreTools/SabreTools/wiki/DAT-File-Formats#clrmamepro-format

I put together a parser for Node.js over at:
https://github.com/robloach/datfile
