### ISSUE TITLE
Remove Illegal Characters in Dreamcast Cheats

### ISSUE THREAD

**Issue by ofry** [libretro/libretro-database#715]
`Failed to deflate cheats\Sega - Dreamcast/Crazy Taxi 2::Crazy Taxi 2 (Japanese) (Retroarch Cheats).cht`

This is same bug as #592

Please fix it, otherwise I can't update cheats from Online Updater.

**Comment by RobLoach** [comment]
Feel free to submit a Pull Request with the fix :+1: 

You can do it directly in the GitHub UI over at:
https://github.com/libretro/libretro-database/edit/master/cht/Sega%20-%20Dreamcast/Sonic%20Adventure%202::Sonic%20Adventure%202%20(European)::Sonic%20Adventure%202%20(Japanese)%20(RetroArch%20Cheats).cht

and

https://github.com/libretro/libretro-database/edit/master/cht/Sega%20-%20Dreamcast/Crazy%20Taxi%202::Crazy%20Taxi%202%20(Japanese)%20(RetroArch%20Cheats).cht

**Comment by twinaphex** [comment]
Ugh, not this again.

This happened in the past too.

Guys, when you scrape this stuff, please be careful that you actually test for these characters to be legal. Don't halfass this stuff since it causes numerous issues for every platform build.

**Comment by RobLoach** [comment]
@twinaphex We don't have automated tests, so there is room for human error. In light of this, I've created this issue which could help avoid these issues in the future: https://github.com/libretro/libretro-database/issues/716 . Thanks!
