### ISSUE TITLE
Proposal: change the dat format to better support long descriptions and hacks.

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#727]
This would depend on two large changes. 

First change the frontend 'help' (when you press the right shift on a menu entry) to support dynamic utf-8 multiline text for the 'rom entries' on a playlist. Also this label should support some sort of 'sliding window' (up and down) controlled by directional buttons if the text doesn't all fit (unlike the label text going right to left on too long text, this wouldn't be automatic).

These features would need to be coded in the main RA repository.

Second replace the current way we're stuffing romhacks metadata on the 'description' field to allow 'untrusted' text strings (from romhacking.net).

My previous 'contribution' was just to repurpose the (ignored) 'comment' field to keep a url to the hack. It's current not being used in the frontend.

My idea of a alternative is to allow both the base rom 'description' and hacks 'descriptions' to show on the new 'help' rshift label to hold a much larger string, that is build from rhdndat.

This requires that string to be utf-8 'escaped' on writing and 'unescaped' when reading (because of possible unmatched string delimiters in romhacking text). The description fields would look much uglier in the dat (much longer lines) but much more useful when figuring out what the hack(s) do.

However, utf-8 text is a multi-byte encoding (ascii characters still show ofc), untrusted content can't be treated a 'c-string' without errors, even if it's escaped first. Since Retroarch wants pure c89, and if i understand the pitfalls correct (i probably don't) you should be using 

https://www.gnu.org/software/libunistring/manual/libunistring.html#Introduction

to read and print the string then escaping it (to prevent 'unmatched delimiter' problems). 

I don't know if it would be sufficient to automatically 'escape' a utf-8 string with \ for ", \n and (literal) \ *only*  when rhdndat writes the concatenated description; and read as a utf-8 string with libunistring then 'unescape' it at runtime in RA , but i'd hope so, since that wouldn't require complicated regular expressions, which again, RA doesn't support because of its C89 requirement.

I don't know C that well, so this analysis is likely to be inaccurate.

Reminder, current the format is like this:
```
game (
    name "ascii only main rom/hack name"
    description "ascii only some description and/or metadata (versions, authors) of the main rom hacks without unbalanced delimiters"
    rom ( name "original filename" size INT crc HEX md5 HEX sha1 HEX )
    comment "http://www.romhacking.net/...."
)
```
I'd prefer to change it to look like this:
```
game (
    name "utf-8 escaped main rom/hack name"
    description "utf-8 multi-line escaped *original source rom description only* (can be found on rhdndat, but other source is probably better)"
    rom ( name "original filename" size INT crc HEX md5 HEX sha1 HEX )
    hack ( url "http://...." version "string" authors "authors list (delimiter?)" description "utf-8 multi-line escaped string" )
)
```
and it would display like so on right shift on a playlist entry:
"Original rom game name and long description"
"\t Hack or Translation 1 name, version"
"\t Hack or Translation 1 long description"
"\t Hack or Translation 2 name, version"
"\t Hack or Translation 2 long description"
etc.

This would allow simpler parsing in rhdndat when merging to output dats and not mis-attribute a 'comment' tag.

But i'm not sure if this new tag would be supported by the libretro-database 'dat pipeline'

For good measure, after this is all done, RA devs could make a 'overlay' icon for the 'system rom icons' in the playlists that would show if the rom has a translation or a hack (or both) applied, as was mentioned use rshift 'help' to show the much larger description and finally to have a 'open hack page' button that opens (all, if more than one) 'hack' tags url in the browser, if any (could be on the 'info field' of the rom in the playlist or a new button just for hacks on the main submenu).

**Comment by i30817** [comment]
Also if this happens it would probably good to update the dat format to support serials at the same time to support only calculating hashes when there is a hack of the same serial on the scanner.

**Comment by i30817** [comment]
Does the RDB builder normalize the strings it finds? IE: if the rdb is building 'descriptions' for genesis romhacks for instance, and multiple hacks have the same base rom, is the string that appears multiple times only stored once in the file/memory?

**Comment by twinaphex** [comment]
> I really wish the RA frontend was coded in rust rather than C...

This is never going to happen, so there is no point in bringing it up.

**Comment by RobLoach** [comment]
Only one `rom` entry per `game`. It ignores multiple roms. You could try escaping the " within the descriptions, and switching `comment` to `url`, I think RetroArch will just ignore entries it doesn't have fields for.

**Comment by i30817** [comment]
> You could try escaping the " within the descriptions
But does RA _un_escape it? Also replacing linefeeds by \n is kinda necessary for long descriptions from the net.

On second thought, I'm not going to push using the 'description' field for the 'main game', because:
1. there is no publicly accessible database for short game descriptions i know and can access reliably.
2. romhacking only has, very not professional info only about the games that have hacks (this game was great/this game sucked is not unusual).

Similarly for the hacks descriptions, they're just too damn long and presume capabilities that RA doesn't have in the scrapped text, like hyperlinking.


What i do for the title now is:

'main' hack is the last translation if it exists (some are addendums) or first hack (if there is no translation)

This is used on the title and gives the 'main info'. _Usually_ the hack name is good enough to figure out what it does, and a translation is just the original game. The corner case is when there is a translation and a hack on top.

So maybe it should be:
'main' hack is the last translation if _only translations exist_ (some are addendums) or first hack.

Then we get rid of the 'description field' for translations only (it doesn't say anything important), keep it as it is currently for hacks (concatenation of hack titles + authors + version), and make a button that simply opens the url(s) for each 'hack' subsection.

For a real life example with two hacks (though one is mixture of translation and hack):
```
game (
    name "Castlevania 3: Improved Controls [Hack by NaOH + 1 hacks]"
    description "Castlevania 3: Improved Controls ~~hack~~ by NaOH version (1.4) + Akumajou Densetsu - Localization / Title Screen Redone ~~hack~~ by ShadowOne333 version (7.1)"
    rom ( name "Akumajou Densetsu (Japan).nes" size 393232 crc eac99920 md5 baa6dd0ea728043653222ebb2029ebaf sha1 88f7ff4c928894743eec3f4e43783b7c358c8b1e )
    hack ( url "http://www.romhacking.net/hacks/3596/" version "1.4" authors "NaOH" )
    hack ( url "http://www.romhacking.net/hacks/1983/" version "7.1" authors "ShadowOne333" )
)
```
To open the urls, there should be a button
Playlist item -> information -> 'show hack sources' 

if you don't want to pull that to next to 'information'
Playlist item -> 'show hack sources'

And retroarch would decide to overlay a custom icon on the 'cartridge icon' for 'this is a hack' or similar (depending if it has at least one game.hack field). It can even see if it's a 'pure translation' by checking if there isn't a 'description' in addition to that - or check if one of the urls for the romhacking 'translations' path).

What do you think, getting rid of the description for 'translations only' and as a bonus get rid of the 'hack suffix' for those
