### ISSUE TITLE
BIOS files without size in dat

### ISSUE THREAD

**Issue by tomgar** [libretro/libretro-database#737]
These files doesn't have the size of the rom in the BIOS - (Non) Merged dats, preventing Clrmame Pro from parsing them when loading the .dat file:
	rom ( name dc/naomi_boot.bin md5 3bffafac42a7767d8dcecf771f5552ba )
	rom ( name 3do_arcade_saot.bin md5 8970fc987ab89a7f64da9f8a8c4333ff )
	rom ( name panafz10-patched.bin md5 1477bda80dc33731a65468c1f5bcbee9 )
	rom ( name panafz10e-anvil.bin md5 a48e6746bd7edec0f40cff078f0bb19f )
	rom ( name panafz10e-anvil-patched.bin md5 cf11bbb5a16d7af9875cca9de9a15e09 )
	rom ( name panafz1-kanji.bin md5 b8dc97f778a6245c58e064b0312e8281 )
	rom ( name panafz10ja-anvil-kanji.bin md5 428577250f43edc902ea239c50d2240d )

Besides that dc/naomi_boot.bin file doesn't look right with that slash in the filename.

**Comment by RobLoach** [comment]
- dc/naomi_boot.bin -- We could likely remove the `dc`
- Sizes: Feel free to add the sizes in if others don't get to it first

**Comment by RobLoach** [comment]
Fixed naomi_boot.bin... I don't have the others.
