### ISSUE TITLE
Update DAT files to 2016-01-03_Fixed

### ISSUE THREAD

**Issue by Kivutar** [libretro/libretro-database#74]
Reasons to update our DAT files:

 * Being up do date
 * Easier scrapping for tgdb
 * Looks like they added back NES headers!!! I've been able to scan and launch NES roms with nestopia.
 * A complete ROM pack is available on archive.org for that version
 * We're building boxart packs, and we would prefer to build it on up-to-date DATs

@sergiobenrocha2 and @lollo78, let discuss about this :)
 
Ah yes, forgot to mention, I talked to @twinaphex on IRC about updating the DATs and he seamed OK with the idea.

**Comment by lollo78** [comment]
Mea culpa?
:wink:

**Comment by RobLoach** [comment]
Headers that still exist in No-Intro:
- Atari - 7800
- Atari - Lynx

**Comment by Kivutar** [comment]
@RobLoach are you sure? You've tried to compile them, and the 2016-01-03_Fixed roms doesn't scan?

**Comment by RobLoach** [comment]
@Kivutar Submitted a bunch of pull requests with the standard Dat-O-Matic DAT files. The ones listed above are the dat files that still have header skips in them from the standard distributed No-Intro sets....

In other news, submitted a PR here to make compiling the database files easier: https://github.com/libretro/RetroArch/pull/2856

**Comment by Kivutar** [comment]
Well, I ask you that, because we were already using official no-intro DATs, and the headerless roms from 2016-01-03_Fixed on archive.org were scanning and running properly.

**Comment by RobLoach** [comment]
Got it... I'll built DAT files from the Archive set for each of those listed above.

**Comment by Kivutar** [comment]
You don't think that the official ones would just work?

**Comment by RobLoach** [comment]
All .dats have been updated to the latest from No-Intro's Dat-o-matic, aside from Nintendo - Famicom Disk System and Nintendo - Nintendo Entertainment System, which are updated to 2016-01-03_Fixed from Archive.org.

**Comment by Kivutar** [comment]
Thanks a lot @RobLoach 

I compiled the new DATs to RDB, and pushed it.
