### ISSUE TITLE
libretrodb_tool header info?

### ISSUE THREAD

**Issue by undeadindustries** [libretro/libretro-database#746]
Is it possible to get header info from rdb files via libretrodb_tool?
Stuff like system name, description, category, version, comment, homepage, etc..

**Comment by RobLoach** [comment]
To my knowledge, the RDB just packs rom information. What are you trying to do with it?

**Comment by undeadindustries** [comment]
I was just wondering because I didn't see the data in the rdb, but did see it in the .dats...
