### ISSUE TITLE
add Teletime (NES Homebrew / RetroArch Content Downloader)

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#758]
Teletime, the NES ROM that is a Creative Commons chiptune album, is now available in the RetroArch content downloader.

Where would an appropriate place be to add this to the database for content scanning purposes? Here is an entry for Teletime.

```
game (
	name "Teletime (Homebrew)"
	description "NES cartridge album / Creative Commons - CC BY-NC-ND 3.0 license"
	year "2010"
	developer "Animal Style and NO CARRIER"
	rom ( name "Teletime (Homebrew).nes" size 40976 crc 921ba26c md5 b412194b21aa4bbad4d039fda075effd sha1 faed721d2e3e4b3077a246b469920acec019ca25 )
)
```

**Comment by RobLoach** [comment]
Perhaps in the hacks dir?
https://github.com/libretro/libretro-database/blob/master/metadat/hacks/Nintendo%20-%20Nintendo%20Entertainment%20System.dat

**Comment by markwkidd** [comment]
submitted a PR https://github.com/libretro/libretro-database/pull/759
