### ISSUE TITLE
[BIOS] Blastem 0.6.1(latest-stable) rom.db  

### ISSUE THREAD

**Issue by LodanZark** [libretro/libretro-database#768]
The current blastem 0.6.1 rom.db has a different hash than the one found in the dat's:

Name:	rom.db
Date:	04/01/2019
Size:	17 KB (17,742 bytes)
--------
SHA-1:	02C287D10DA6DE579AF7A4CE73B134BBDF23C970
MD5:	FF4A3572475236E859E3E9AC5C87D1F1
CRC32:	C94E8C8B

Source: https://www.retrodev.com/repos/blastem/archive/357b4951d9b2.tar.gz
Official Page: https://www.retrodev.com/blastem/

**Comment by RobLoach** [comment]
Thanks so much! I'm so glad the BIOS DAT gets this kind of attention.
