### ISSUE TITLE
Update No-Intro and Redump DATs

### ISSUE THREAD

**Issue by tjanas** [libretro/libretro-database#793]
Entry not found in libretro-database/metadat/no-intro/Nintendo - Nintendo Wii (DLC).dat

**Comment by RobLoach** [comment]
Looks like Art of Fighting 3 was updated in December. The No-Intro dats were updated last September. they need updating.... Thanks! Hope to run an update this weekend soemtime.

http://datomatic.no-intro.org/?page=show_record&s=52&n=2415

**Comment by RobLoach** [comment]
Once https://github.com/libretro/libretro-super/pull/954 goes through, this should be available.
