### ISSUE TITLE
Can we set up subfolders for large directories? Difficult to Navigate in app/everywhere else

### ISSUE THREAD

**Issue by TheMozillaChrome** [libretro/libretro-database#806]
NDS at least has this issue, where well over half the .chts aren't accessible due to github truncating them

there's a hard limit of 1k, if we just had subfolders (#-A-Z) within each console directory, should be easily fixed, for the ones that have over 1k entries

**Comment by i30817** [comment]
What for? Just for opening PRs directly from the github interface?

**Comment by TheMozillaChrome** [comment]
1) Usability, right now there is content not accessible directly through github, and its because a lack of organization, when you import it, you could and do have to scroll through potentially over a thousand entries depending on the system, but the point of this is that we don't have one whatsoever and there it has visible consequences/shortcomings, and adding literally any form of organization would help immensely.

By adding just a basic set of folders from #-A-Z within each console it:

A) Allows room for expansion

B) Will make literally any change in formatting or organization easier later on, (E:G Region-based) 

C)  Again, usability, its functional right now, but not much more than that.,  I would do it myself but this is quite literally by 2nd time using github in two years and I doubt i have permission

**Comment by i30817** [comment]
Interface limitations of github have nothing to do with the user filesystem. Neither git itself or the native operating systems care about the number of files in a folder.

That's why i mentioned PRs opened from the site: it's the only thing i can think of that is relevant. And has at least 2 workarounds (search for the filename or use git/another git GUI normally).

**Comment by TheMozillaChrome** [comment]
I just put this out there because when I did download through retroarch, there was no organization in the list, long time spent scrolling, sorry if i came across as bringing up a github issue, i was just surprised when I went here and looked, that there were folders 1,000+ files with no real organization with ease of access in mind

Yeah the kind of leaves a mess of things, but I guess the problem I wanted to bring up is there's a lot that can be done that could eliminate a lot of clutter and have it be more usable and cleaner in general, right now there is all but nothing, and anything at all should improve it nicely

Maybe just a couple folders with specific series within them? as far as searching goes just console > series > game, a catch all definitely isn't possible of course so like you said not feasible, but I guess I just wanted to open up an issue for just some tidying up as far as navigation goes within the app

Cheers, appreciate everything ya'll do, emulation has gone pretty damn far

**Comment by RobLoach** [comment]
Clone the repository locally and submit PRs through there. There's a Desktop UI if you're not keen on the command line:
https://desktop.github.com/
