### ISSUE TITLE
NDS Roms are not being added to playlists

### ISSUE THREAD

**Issue by ThrillaGames** [libretro/libretro-database#808]
On my Retroarch (v 1.7.6) the NDS roms will not scan in. I have got the DeSmuME core and have also tried with the DeSmuME 2015 core but to no avail. If I load the games manually via 
"Load Content" they run fine but they wont add to my playlists via the "Scan Directory" option. The files end in ".nds".

**Comment by RobLoach** [comment]
Thanks! Could you provide the CRC of a file does not scan?

We only provide the decrypted files in the database, but we could add the encrypted ones too, if they work.

**Comment by ThrillaGames** [comment]
The CRC for one of the games "5585 - Pokemon - Black Version (DSi Enhanced)(USA) (E)(SweeTnDs).nds" is e2bee619

If you need me to get the CRC for all of them I can

**Comment by RobLoach** [comment]
[5585 - Pokemon - Black Version (USA, Europe) (NDSi Enhanced)](http://datomatic.no-intro.org/?page=show_record&s=28&n=5585)

Looks like that's an old dump:

```
5585 - Pokemon - Black Version (USA, Europe) (NDSi Enhanced) [b].nds
```

You will want to.....

1. Redump it properly to match `4F6E5580`
2. Apply a patch to reach `4F6E5580`
3. Use the Qt interface to make a custom playlist for it in RetroArch

**Comment by i30817** [comment]
> The CRC for one of the games "5585 - Pokemon - Black Version (DSi Enhanced)(USA) (E)(SweeTnDs).nds" is e2bee619
https://archive.org/details/5585-E2BEE619To4F6E5580
