### ISSUE TITLE
Duplicate NES and Mega Drive dats

### ISSUE THREAD

**Issue by kivutar** [libretro/libretro-database#819]
Why do we have

`dat/Nintendo - Nintendo Entertainment System.dat`
and `metadat/no-intro/Nintendo - Nintendo Entertainment System.dat` ?

Same question about `Sega - Mega Drive - Genesis.dat` that is also present in these two folders.

Is `dat/Nintendo - Nintendo Entertainment System.dat` about ROMs with headers?
`Sega - Mega Drive - Genesis.dat` looks like a mix of different sources.

**Comment by RobLoach** [comment]
> Is dat/Nintendo - Nintendo Entertainment System.dat about ROMs with headers?

Yes, that's the headers DAT. I'll add a note in the description over at https://github.com/libretro/libretro-database/pull/820

> Sega - Mega Drive - Genesis.dat looks like a mix of different sources.

Majority of these are dumps from Sega Classics from https://github.com/libretro/libretro-database/issues/457

**Comment by RobLoach** [comment]
The NES headered DAT could do with an update.

**Comment by kivutar** [comment]
Thanks for the info
