### ISSUE TITLE
Remove old metadat files

### ISSUE THREAD

**Issue by kivutar** [libretro/libretro-database#822]
I propose that we take some action to prevent the game names overrides or/and duplicate entries that are happening when a metadat has an outdated name.

Entries like

```
game (
        name "1943 Kai (Japan)"
        genre "Shooter"
        rom (
                crc FDE08D6D
        )
)
```

Could have the `name` line commented.

This would preserve the information for manual edition, while avoiding bugs where the No-Intro name was updated and we still end up with the old name from the metadata.

Also, we should have a clear distinction between which .dat are allowed to created new entries in an rdb, and those who can only add fields to a matching entry.

We should give priority to no-intro, redump, fba and our own dats. These 4 sources should be allowed to create game entries.

Then all the stuff like metadat/developer should only be allowed to change the developer field.

**Comment by RobLoach** [comment]
A lot of the old data is deprecated from the [`metadat`](https://github.com/libretro/libretro-database/tree/master/metadat) folder...

- analog
- bbfc
- developer
- elspa
- esrb
- etc

A lot of them have conflicting names, or old CRC data. We might be able to just delete some of them.
