### ISSUE TITLE
BIOS.dat: PSX scph1001.bin incorrect?

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#826]
From https://github.com/libretro/docs/issues/134 

scph1001.bin
ps-20a - Version 2.0 05/07/95 A
DC2B9BF8DA62EC93E868CFD29F0D067D

https://github.com/libretro/libretro-database/blob/master/dat/BIOS.dat

**Comment by Corbin602** [comment]
This one was hard to find at first. I found it by searching the md5 you listed. The file name for it was DTL-H1001.BIN Simply rename it to scph1001.bin and all is good. 
The two sites I used:

To find it: https://wahki.mameau.com/index.php?title=Emulator:Mednafen-PSX&mobileaction=toggle_view_desktop

To DL it: http://www.psxdev.net/forum/viewtopic.php?t=56

**Comment by devnoot** [comment]
Someone should update the docs to note this. It threw me for a loop.

**Comment by xexubonete** [comment]
Yes Thanks guys! scph1001.bin MD5:DC2B9BF8DA62EC93E868CFD29F0D067D
its now DTL-H1001.BIN !
You can download it here with name  DTL-H1001.BIN: https://www.psxdev.net/forum/viewtopic.php?t=56
Just rename it!

**Comment by RobLoach** [comment]
Are you able to fix the System.dat file? Does it need to be updated? Thanks.
