### ISSUE TITLE
Scanning for PC Engine CD does not work when data track is not Track 01

### ISSUE THREAD

**Issue by metchebe** [libretro/libretro-database#831]
This comment refers to the database for NEC - PC Engine CD - TurboGrafx-CD, for which the database currently contains information for **Track 01** for each game.

The Retroarch scanner calculates the checksum for the first **data** track. In the game I tested this corresponds to **Track 02** (Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)). I assume that there could be many others.

Therefore, for PCE CD scanning to work, the database has to contain the crc for the first data track, which is not necessarily Track 01.

Note: tested with CUE + multi-BIN (source), CUE + BIN and CHD all created from the same source. The CRC that is calculated is always for **Track 02**.

Some relevant logs:

```
# CHD
[INFO] Comparing with known magic numbers...
[INFO] Could not find compatible system.
[INFO] CHD 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).chd' crc: c681f9da

# CUE + Single BIN
[INFO] Parsing CUE file 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rond o (Japan) (FABT, FACT).cue'...
[INFO] Reading first data track...
[INFO] Comparing with known magic numbers...
[INFO] Could not find compatible system.
[INFO] Parsing CUE file 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue'...
[INFO] CUE 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue' primary track: D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).bin (8620080, 24399648)
[INFO] Reading first data track...
[INFO] CUE 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue' crc: c681f9da

# CUE + Multiple BINs
[INFO] Parsing CUE file 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue'...
[INFO] Reading first data track...
[INFO] Comparing with known magic numbers...
[INFO] Could not find compatible system.
[INFO] Parsing CUE file 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue'...
[INFO] CUE 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue' primary track: D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 02).bin  (0, 24399648)
[INFO] Reading first data track...
[INFO] CUE 'D:\RetroArch\downloads\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)\Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT).cue' crc: c681f9da
```
*Sorry if it is inappropriate to create a new report for this, but other relevant bug reports seemed too old...*

**Comment by leskenazi** [comment]
I think I have the same issue. Has this been investigated ?

**Comment by flako-dd** [comment]
`lrdbtool NEC\ -\ PC\ Engine\ CD\ -\ TurboGrafx-CD.rdb list | jq` lists it as:

```json
{
  "serial": "4B4D434433303035",
  "sha1": "DB237C0EFED295E8C2B92707DE56C30D3C765047",
  "md5": "2D0A0010D6F56BE991D6FFE1A7E6E5DF",
  "crc": "EDF3D17E",
  "size": 8620080,
  "rom_name": "Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 01).bin",
  "description": "Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)",
  "name": "Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT)"
}
```
all digests match Track 01 for my files, 
the calculated digest by retroarch is the second track as @metchebe already said.
```
EDF3D17E       8620080  Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 01).bin
C681F9DA      24399648  Akumajou Dracula X - Chi no Rondo (Japan) (FABT, FACT) (Track 02).bin
```

**Comment by lucasmr** [comment]
Yes, I noticed that as well. I was trying to add PCE-CD serial number scanning support, but I could not find the serial of the game anywhere in the disc. This technique is being used on many other CD based systems in RA, but on those it's always possible to find the game serial number on the disc.

What you can do, however, is make your cue/bin files into chd with chdman, then perform a manual scan. The game works normally, the thumbnails and database match, and the file is compressed.

**Comment by lucasmr** [comment]
Databases are updated now, try scanning the files again.

**Comment by RobLoach** [comment]
Thanks so much for the push here, @lucasmr ... Really love the help on indexing disc media correctly!
