### ISSUE TITLE
Missing Games in ZX Spectrum Database

### ISSUE THREAD

**Issue by predator002** [libretro/libretro-database#837]
Hi I’ve only recently started using RetroArch and encountered an issue with the ZX Spectrum database. I’ve been unable to scan my whole set of games because the database is missing games from G-S. As it doesn’t look to have been reported I thought I’d message

**Comment by RobLoach** [comment]
Have any examples of games that are not scanned? The CRC, and the game name?

**Comment by predator002** [comment]
Any game that starts with H all the way to R. I’ve opened the rdb in notepad and entire alphabet of games isn’t in there.

**Comment by predator002** [comment]
E.g, all games that start with H. None of these are in the rdb. http://www.worldofspectrum.org/games/h.html

**Comment by RobLoach** [comment]
Are you using Sinclair - ZX Spectrum +3 ?

Perhaps libretro-dats needs to be fixed https://github.com/robloach/libretro-dats

**Comment by predator002** [comment]
I’m using Sinclair - Zx Spectrum database. I don’t know about libretro-dats

**Comment by predator002** [comment]
I've just used the prior database version from 29 Sep 2018 and all the games are in that database. My playlist now builds correctly.

**Comment by RobLoach** [comment]
Does it work with the +3 games?

What is an example of a game that's missing? I know you said a group, but I need specifics.

1. The CRC of one file that you have that didn't scan
2. The game name
3. What you expect it to match in the database

**Comment by predator002** [comment]
No the +3 doesn't contain the games however the +3 database may be correct as the +3 is diskbased computer and the games could be the right batch. The game doesn't appear in the no-intro +3 database either.

An example of one of the games I am trying to scan is Robocop, the filename of the file is Robocop.tzx. Apologies for my dumbness I do not know what to do with identifying CRC. The game itself can be viewed here: http://www.worldofspectrum.org/infoseekid.cgi?id=0004179

In terms of your link, Robocop is not in the database and from searching the metadat page, none of the files here that are spectrum related appear to have it either: https://github.com/libretro/libretro-database/tree/master/metadat

This is the database which i have been able to scan my games with successfully: https://github.com/libretro/libretro-database/blob/ca9478320f81dd7ba2a52b91afcee01420608de4/rdb/Sinclair%20-%20ZX%20Spectrum.rdb

**Comment by RobLoach** [comment]
I think I found why Spectrum wasn't coming through from TOSEC:
https://github.com/RobLoach/libretro-dats/commit/f8798ff2f2d3d0343fb1418218e14dce0b4b5ec9#diff-bfa45c1744bbd68fca49ecc4d2a79b6fL154

Not sure why I had removed them :confused:
