### ISSUE TITLE
Use Redump Serials DAT

### ISSUE THREAD

**Issue by blackstade** [libretro/libretro-database#879]
"Phantasy Star Portable 2 (Europe)" serial "ULES-01439" is recognized as "Prince of Persia - The Forgotten Sands (Europe)"

"Kingdom Hearts - Birth by Sleep (Europe)" serial "ULES-01441" is recognized as "PlayEnglish (Europe)"

**Comment by RobLoach** [comment]
Brought up by @pkos, reworking this isuse to index the Redump serials....
http://redump.org/datfile/psp/serial,version
