### ISSUE TITLE
Different characters causing thumbnails not to match database

### ISSUE THREAD

**Issue by Wildman48** [libretro/libretro-database#899]
After messing with this for many hours I've come to the conclusion different characters and symbols cause the database not to match with showing a thumbnail. Anything that has a & or ~ will not match even if I have the correct matching crc file. I think some files that end in a number or dash causes an issue to.
 I'll give an example for snes:
Adventures of Batman & Robin, The (USA)
CRC tag matches with B3EF81F5

I've tried renaming the file and changing the & to and.
I went through my whole list of games and anything with a & or ~ will 100% not match and not show the boxart thumbnail.

**Comment by RobLoach** [comment]
The following characters are replaced with `_`

`&*/:`\"<>?\\|`

**Comment by Wildman48** [comment]
Thanks for the info but It's not seeming to work for me unless i'm doing it wrong somehow. Here's a clip of the .lpl file when it scanned in.

```
"path": "/media/RetroArch/games/snes/Adventures of Batman _ Robin, The(USA).smc",
      "label": "Adventures of Batman and Robin, The (USA)",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "B3EF81F5|crc",
      "db_name": "Nintendo - Super Nintendo Entertainment System.lpl"
```

I made sure the thumbnail artwork was named the same as the file. I tried scanning it zipped up. I tried removing the spaces around the _.  Seems like a simple mistake on my end if all I have to do is take out the & and replace it with a _.

**Comment by RobLoach** [comment]
https://github.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/blob/master/Named_Boxarts/Adventures%20of%20Batman%20_%20Robin%2C%20The%20(USA).png
