### ISSUE TITLE
Bad file names resulting in failed compilation

### ISSUE THREAD

**Issue by funky327** [libretro/libretro-database#9]
The following names are resulting in a failed Android compilation for RetroArch, probably causing some other issues as well:

cht/PSX/GameShark/Einh¤nder.cht
cht/PSX/GameShark/Einheee¤nder.cht
cht/PSX/GameShark/Star Wars Masters of Ter¤s K¤si.cht
cht/PSX/GameShark/Star Wars Masters of Tereee¤s Keee¤si.cht

cht/PSX/Xploder/Koudelka Franz¶sisch.cht
cht/PSX/Xploder/Koudelka Franzeee¶sisch.cht
cht/PSX/Xploder/Star Wars - Episode 1 - Jedi Power Battles Franz¶sisch.cht
cht/PSX/Xploder/Star Wars - Episode 1 - Jedi Power Battles Franzeee¶sisch.cht

cht/Super Nintendo Entertainment System/ProActionReplay/Ganbare Goemon 2 - Kiteretsu Sh´gun Magginesu!.cht
cht/Super Nintendo Entertainment System/ProActionReplay/Ganbare Goemon 2 - Kiteretsu Sheee´gun Magginesu!.cht
cht/Super Nintendo Entertainment System/ProActionReplay/Ranma ½ Part 1.cht
cht/Super Nintendo Entertainment System/ProActionReplay/Ranma ½ Part 2.cht
cht/Super Nintendo Entertainment System/ProActionReplay/Ranma ½.cht
cht/Super Nintendo Entertainment System/ProActionReplay/Ranma ee½ Part 1.cht
cht/Super Nintendo Entertainment System/ProActionReplay/Ranma ee½ Part 2.cht
cht/Super Nintendo Entertainment System/ProActionReplay/Ranma ee½.cht

**Comment by fr500** [comment]
Are you on the latest git? just wondering.
@OffensiveUser  please take a look. I thought this was fixed already?

**Comment by funky327** [comment]
I am, if you browse the current repo (online) you'll see these.

**Comment by twinaphex** [comment]
Yeah those characters are still in there.

Hoping this gets fixed ASAP, this should have been fixed from Day One.

**Comment by OffensiveUser** [comment]
I'll get everything sorted as soon as i get to my computer, had a busy couple of days,

**Comment by skx7** [comment]
@twinaphex this issue can be closed. all names were fixed long time ago.
