### ISSUE TITLE
FBNeo importing content only works when Scan Without Core Match: ON

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#925]
From @rsn8887  

## Description

When scanning any FBNEo rom via `Import Content`, e.g. my crc32-verified rom 1941.zip, it doesn't show up in the FBNeo playlist. I have the core installed, everything updated etc.

When I turn ON `Settings->Playlists->Scan without core match`, then it works.

### Expected behavior

The rom should appear in the FBNeo playlist also with `Settings->Playlists->Scan without core match` OFF as long as I have the core installed.

### Actual behavior

See above

### Steps to reproduce the bug

1. Import Content
2. Import Single File
3. Select a FBNeo rom, e.g. 1941.zip
4. Observe it is not added to playlist
5. Repeat after Settings->Playlists->Scan without core match:ON
6. Observe working

### Bisect Results

Never worked.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Latest Nightly 08/30/2019

### Environment information

- OS: Switch

**Comment by RobLoach** [comment]
@rsn8887 .... What's the CRC of the file? What playlist does the file get added to? More info would be helpful. Thanks!

**Comment by rsn8887** [comment]
The file I tested was 1941.zip and I checked all crc32 matched the fbneo dat file entry from the current libretro-databases repo here.

I think my issue might be the same issue as https://github.com/libretro/libretro-super/issues/1107

According to @metchebe the fix is to remove the line database_match_archive_member = "true" from the core info file.

**Comment by rsn8887** [comment]
After setting Settings->Playlists->Scan without core match:ON and re-scanning, all the games appear. However, when I now go to Online Updater->Playlist Thumbnail Updater, the playlist is still listed as "FB Alpha - Arcade Games", not "FB Neo - Arcade Games"

**Comment by metchebe** [comment]
@rsn8887 do you still have the old FB Alpha rdb in the database folder? It should be deleted. My playlist shows up correctly as FB Neo.

**Comment by rsn8887** [comment]
You are right I still had the old database. I also have the new FBNeo database.

I deleted the old FB Alpha database and Playlist. When I now scan my FBNeo rom folder, no playlist appears even though the roms are correct.

So the only reason it worked before was because it was using the old database.

**Comment by RobLoach** [comment]
I'm assuming you've done the same with the cores, and downloaded the Neo one too?

**Comment by rsn8887** [comment]
Yes. Still the problem. Crc is correct, but nothing shows up in fb neo playlist, not even a playlist is created.

**Comment by mgmalheiros** [comment]
I've been examining the Libretro databases lately to understand specific scanning problems for Ludo (which may also apply to RetroArch). I noticed a change between older and newer RDB files for Final Burn. I guess this explains the problem reported here.

Few months ago, "FB Alpha - Arcade Games.rdb" contained two entries for "1941":

```
3cfc31d0      131072                41em_36.12h  1941 - Counter Attack (900227 World)
64e58dc3     1420289                   1941.zip  1941 - Counter Attack (900227 World)
```

I believe a single match of the "41em_36.12h" inside some zip archive would suffice to add it to the FB playlist.

Right now, the "FBNeo - Arcade Games.rdb" file contains only one entry:

```
64e58dc3     1420289                   1941.zip  1941 - Counter Attack (900227 World)
```

So only this exact CRC would be matched. This holds true for all romsets now: only ZIP files are listed.

That particular TorrentZipped file should have the following content:

```
Archive:  1941.zip
TORRENTZIPPED-B8D7DA26
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
  524288  Defl:X   269308  49% 1996-12-24 23:32 ff77985a  41-1m.3a
  524288  Defl:X    87410  83% 1996-12-24 23:32 4e9648ca  41-32m.8h
  524288  Defl:X   186206  65% 1996-12-24 23:32 983be58f  41-3m.5a
  524288  Defl:X   270331  48% 1996-12-24 23:32 01d1cb11  41-5m.7a
  524288  Defl:X   187229  64% 1996-12-24 23:32 aeaa3509  41-7m.9a
  131072  Defl:X   117804  10% 1996-12-24 23:32 d1f15aeb  41_18.11c
  131072  Defl:X    82385  37% 1996-12-24 23:32 15aec3a6  41_19.12c
   65536  Defl:X    18355  72% 1996-12-24 23:32 0f9d8527  41_9.12b
  131072  Defl:X    37768  71% 1996-12-24 23:32 4249ec61  41em_30.11f
  131072  Defl:X    30671  77% 1996-12-24 23:32 584e88e5  41em_31.12f
  131072  Defl:X    65436  50% 1996-12-24 23:32 ddbee5eb  41em_35.11h
  131072  Defl:X    65224  50% 1996-12-24 23:32 3cfc31d0  41em_36.12h
     279  Defl:X       47  83% 1996-12-24 23:32 eb122de7  buf1
     279  Defl:X       53  81% 1996-12-24 23:32 59c7ee3b  ioa1
     279  Defl:X       53  81% 1996-12-24 23:32 3abc0700  iob1.11e
     279  Defl:X       71  75% 1996-12-24 23:32 f1129744  prg1
     279  Defl:X       47  83% 1996-12-24 23:32 41dc73b9  rom1
     279  Defl:X       58  79% 1996-12-24 23:32 84f4b2fe  sou1
     279  Defl:X       51  82% 1996-12-24 23:32 3004dcdf  yi24b.1a
--------          -------  ---                            -------
 3475361          1418507  59%                            19 files
```

Besides, I've found some problems with the current FBNeo database, like not having an entry for `xevious.zip` or asking for a `invaders.zip` with unusual samples (I have tried to rebuild it with all known ones, with no success).

**Comment by RobLoach** [comment]
I see the DAT over at:
https://github.com/libretro/FBNeo/blob/master/dats/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Arcade%20only).dat

Does FBNeo work when running the following?

```
retroarch -L fbneo games/88games.zip#861m01.k18
```

If so, I could put together a parser to build a libretro-database DAT based on this one.

**Comment by metchebe** [comment]
Sorry to bother. My un-merged torrentzipped roms no longer scan correctly by CRC since last month's metadat update (FBNeo - Arcade Games.dat) by @alfrix . I checked my roms with RomCenter and they match today's FBNeo database.

The byte difference is small (22 bytes for three files I checked), and I cannot find the explanation. Has the process to generate the metadat file changed?

An example:

| File | Size | CRC |
| --- | --- | --- |
| megaman.zip (my set) | 3301557 | 779C1CE7 |
| megaman.zip (metadat) | 3301535 | A69BEB38 |
| mslug.zip (my set) | 13165412 | AC6E93EA |
| mslug.zip (metadat) | 13165390 | 01507BF2 |

My set used to match the old FB Alpha database, which as far as I can tell has the same roms as the latest FB Neo for my set:

```
game (
	name "Mega Man - the power battle (951006 USA)"
	year 1995
	publisher "Capcom"
	rom ( name megaman.zip size 3301557 crc 779C1CE7 md5 d20bef310802e7f1d79ca90789295627 sha1 7c6da41133332e60176f8719dc9a2080c1b5a5a1 )
)

game (
	name "Metal Slug - Super Vehicle-001"
	year 1996
	publisher "Nazca"
	rom ( name mslug.zip size 13165412 crc AC6E93EA md5 e378b15e0e287bb484454e489181c71d sha1 cc3c8f501ecb0365e5fe20080da2e908da404c17 )
)
```

**Comment by metchebe** [comment]
So the torrentzip comment is 22 bytes: `TORRENTZIPPED-XXXXXXXX`. This could be the explanation.

**Comment by RobLoach** [comment]
@alfrix Have you run into this in your latest update in #966 ?

**Comment by alfrix** [comment]
the rdb needs to be generated by an special dat, i create it based on a known romset using the dat in the fbneo repo and romcenter, in the next update i'll leave both dats here, and a mini guide on the settings needed for romcenter.

**Comment by metchebe** [comment]
I also use Romcenter with the latest DAT, and then process through torrentzip (trrntzip.exe) as indicated by the specification: [RetroArch Playlist Scanner Support](https://docs.libretro.com/guides/arcade-getting-started/#retroarch-playlist-scanner-support).

@alfrix Did you use trrntzip.exe? You didn't mention it.
