### ISSUE TITLE
Database/Thumbnail Mismatches

### ISSUE THREAD

**Issue by cloudywings2** [libretro/libretro-database#940]
Some games have wrong names in the .dat or in the Thumbnails database, which makes the game incompatible with the thumbnails database. For example

http://redump.org/disc/791/
This game is identified as "Gex 3: Deep Cover Gecko." It is also identified as that in the Libretro Thumbnails database. In the database rdb/Sony - PlayStation.rdb though, it is identified as "Gex 3 - Deep cover Gecko," so the thumbnails will never be downloaded.

https://datomatic.no-intro.org/?page=show_record&s=25&n=0011
This game is identified as "Alien Syndrome (Europe)" in the No-Intro database, and is actually correct in the database, but in the Thumbnails database is identified as "libretro-thumbnails/Sega_-_Game_Gear/Named_Boxarts/Alien Syndrome (USA, Europe).png" 

https://datomatic.no-intro.org/index.php?page=show_record&s=25&n=0063
Another Game Gear game, Columns, is now identified as "Columns (USA, Europe, Brazil)," but in the thumbnails database is still just called "Columns (USA, Europe.)"

https://datomatic.no-intro.org/index.php?page=show_record&s=47&n=0156
This game is called " Bugs Bunny in - Crazy Castle 4 (USA)." but in the Thumbnails database is called "Bugs Bunny in Crazy Castle 4 (USA)," with no hyphen.

https://datomatic.no-intro.org/index.php?page=show_record&s=47&n=0606
Oracle of Ages (and Seasons) are identified as " Legend of Zelda, The - Oracle of Ages (USA, Australia)." In the databases they're labeled as "Legend of Zelda, The - Oracle of Ages (USA)."\

These are just the ones I've seen offhand, but I know there are others. There are individually fixable but the fact that there are so many seems to indicate that there's a broader problem with the databases not matching up with the official No-Intro/ReDump databases.

**Comment by RobLoach** [comment]
Thanks for finding those ones. The thumbnails are over at:
https://github.com/libretro-thumbnails

Could do with some fixes.

**Comment by ebzero** [comment]
How do we get the fixes implemented?  I am willing to change some thumbnail image names to match the database file, and duplicate thumbs for variants, etc... but I don't know how to get the authority to do it?

**Comment by RobLoach** [comment]
1. Find the repo at https://github.com/libretro-thumbnails
2. Fork the repo
3. Rename the thumbnail files
4. You can use https://desktop.github.com/ to help you out with that

**Comment by ebzero** [comment]
Sorry for my ignorance.  I can fork and clone the repo and rename the files, but can I just push them back when done?  Will they automatically be accepted?  Will they be instantly added to the project, so that if someone were to download the thumbnails right after my push they would get the new names?  I'm just not sure how this project works.

**Comment by ebzero** [comment]
Almost all of the Sega thumbnails are now broken, because the retroarch databse names were changed, mostly due to Brazil being taken out of the name for the region listing, for example.  The NES ones seem to all be updated already though.

**Comment by RobLoach** [comment]
You'll submit a Pull Request to have it go upstream:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by ebzero** [comment]
Great.  Sorry, I am new to this.  I have done 1 set of files for Ace of Aces in Sega Master system as a test run... renaming the file to match what the database now expects as seen at https://raw.githubusercontent.com/libretro/libretro-database/master/metadat/no-intro/Sega%20-%20Master%20System%20-%20Mark%20III.dat

If this works, I will try to update all of the Master System, Game Gear, and Genesis games

**Comment by RobLoach** [comment]
Updated the thumbnail checker:
https://github.com/RobLoach/libretro-thumbnails-check

It'll show you where the mismatches are.
