### ISSUE TITLE
Atari Lynx: Lynx-headered .dat file submission

### ISSUE THREAD

**Issue by negativeExponent** [libretro/libretro-database#968]
While i was working on updating Beetle Lynx (https://github.com/libretro/beetle-lynx-libretro/commit/8254289c359c2ea2c1bd5f4e3831fe1404acf0e9), i notice that the scanner only shows non-headered or the so called no-intro dats.

Here is 86 out of (9x something) that is based on Lynx-headered roms hopefully to be added on existing database.
[Atari - Lynx (headered).dat.zip](https://github.com/libretro/libretro-database/files/4004160/Atari.-.Lynx.headered.dat.zip)

**Comment by RobLoach** [comment]
Thanks! Added it in the `dat` folder without the BIOS, and an added comment.
