### ISSUE TITLE
MAME Genre

### ISSUE THREAD

**Issue by undeadindustries** [libretro/libretro-database#975]
Any chance of having a MAME Genre file added to the DB?

**Comment by RobLoach** [comment]
@bkoropoff and @markwkidd are pretty much owning the arcade DATs lately. How do you envision it looking like?

**Comment by undeadindustries** [comment]
Part 2 of this question: Why not put all data in the dat for each system? That is, instead of breaking it out into  genre, origin, etc files?

I'm willing to help in any way. I have xml genre and category files for MAME that can be used for an initial data dump if needed.

THANK YOU!

**Comment by markwkidd** [comment]
There are catver.ini files in each MAME repo that correspond to each
specific MAME version. (They need to match due to changes in romset names
over time)

**Comment by undeadindustries** [comment]
Sorry, here are the more specific versions of my questions:

Is the MAME catver.ini information contained in the MAME RDB file?
Is genre info from other systems (NES, Playstation etc) contained within the RDB file?
How can I access it?
If not, any chance of getting that info added?

Thanks again!

**Comment by undeadindustries** [comment]
I did find that in libretro-build-database.sh this was missing and should be added:
```
	#Check if meta genre DAT is there
		if [ -f "${LIBRETRODATABASE_META_DAT_DIR}/genre/${1}.dat" ]; then
			COMMAND+=' "${LIBRETRODATABASE_META_DAT_DIR}/genre/${1}.dat"'
		fi
```

**Comment by undeadindustries** [comment]
@RobLoach or @markwkidd ,
I created a MAME genre file from the mame ini genre file.

It's formatted like this:

clrmamepro (
	name "MAME - Consolidated ROM Sets"
	description "MAME - Consolidated ROM Sets"
)

game (
	name "Xybots (rev 0)"
	genre "Maze"
	rom (
		crc 8912445f
	)
)

game (
	name "X-Men Vs. Street Fighter (US 961004)"
	genre "Fighter"
	rom (
		crc 4bdf28fa
	)
)

However, when I put this in 
libretro-super/retroarch/media/libretrodb/metadat/genre/MAME.dat, I see libretro-build-database.sh crunch through it, with no errors, but when I use libretrodb_tool on it, I still don't see genres for MAME. I do see them for all other platforms because of the "fix" in my previous comment.

Any ideas what I could be doing wrong?

THANK YOU!!!!!!!!!!

**Comment by RobLoach** [comment]
Awesome! Added the genre in the build. Should be in there next build :+1: 

Good find!
