### ISSUE TITLE
Retroplay amiga dats

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#976]
Now that p-uae (supposedly) has support for the Retroplay set of whdload lha's (i'm assuming 'support' here means that the retroplay filenaming is [consistent enough to use their naming scheme](https://github.com/libretro/libretro-uae#games-that-need-a-specific-model)), using the retroplay dat sets for a whdload database (and maybe the hd database and unreleased too) would be nice.

They're in the root of the retroplay ftp.

Lack of standard naming to link the filename/checksums to game metadata is painful but could maybe be avoided by using the openretro game database https://openretro.org/ because it has most of the WHDLoads as game entries (many outdated though). 

Not sure it can be downloaded though.

That database also has more stuff that can be super useful for the core, though i don't know if cores can take up database info. For instance, [they recently added this.](https://openretro.org/2019/05/04/whdload-quit-key-can-be-registered)

Which is a major usability problem with whdload in emulators (where people just kill the emulator instead of shutting down, and then are surprised their saves are never written). If RA/the core could recognize this and send that keycode for a more or less graceful shutdown before the core is terminated, it would help a lot.

**Comment by RobLoach** [comment]
What's RetroPlay? No-Intro provides Commodore - Amiga DAT.

**Comment by i30817** [comment]
Retroplay is a collection of amiga whdloads, which aren't covered by no intro because they're hacks (to make the games playable from hd without disk changes, to broaden the admissible amiga hardware, to add controller support, etc).

**Comment by i30817** [comment]
BTW, the manual scan with those dat files can make a playlist without images, thankfully.

**Comment by i30817** [comment]
FYI i found a way to update/filter out the non-english lha's of these myself so i'm not that interested in this anymore (i suppose images are nice).

I use xmlstarlet + some shell code to filter out some prohibited patterns from the dats after a ftp update and then it's a question of making RA make another 'manual' scan for different playlists (hds, whdload betas, whdloads).

If lr-database was the one updating i'd have to delete or never download the other language games and that is a bit less atractive than having versions just in case (and it's only 4gb, since amiga games tend to be tiny).

**Comment by i30817** [comment]
Ok i have a script working to transform retroplay dats to a format 'like' what is usually used by MAME.

I think there is a clear path of using the 'x_name' to get the 'real name' and images of the game in openretro-database (i opened this issue for it: https://github.com/FrodeSolheim/fs-uae-launcher/issues/79 )

Anyway here's the script, requires  xmlstarlet, gunzip, mktemp, lftp, (to download the dats):
https://gist.github.com/4efd24973810458507929c55aeca2721

It should be relatively easy to adapt to python or node, especially considering the actual xml transformation is in the form of a embedded xsl file. 

Sadly the retroplay 'hd' subset is not on the database - yet -, and that one has some real gems that work on puae and aren't anywhere else, like heart of the alien redux or darkmere. 

The script will create dat files for the 2 subdirs i consider most important (games and hds - even if this is not on the database); you can ofc, also add the remaining others (older jst stuff a whdload competitor, and whdload betas, magazines and demos) by following the pattern and looking up the name of the zip files with the dats on the ftp.

**Comment by sonninnos** [comment]
> Which is a major usability problem with whdload in emulators (where people just kill the emulator instead of shutting down, and then are surprised their saves are never written). If RA/the core could recognize this and send that keycode for a more or less graceful shutdown before the core is terminated, it would help a lot.

This is not a problem with the PUAE core, since the write cache is disabled by default. The user can of course revert to default WHDLoad behavior and enable the cache by manually editing the automatically generated `WHDLoad.prefs` in `system`.
