### ISSUE TITLE
how to cheats Manually from txt?

### ISSUE THREAD

**Issue by candrapersada** [libretro/libretro-database#977]
how to cheats Manually from
[Cheats Fire Emblem Fates - Special Edition (USA).txt](https://github.com/libretro/RetroArch/files/4088672/Cheats.Fire.Emblem.Fates.-.Special.Edition.USA.txt)
and
[Final.Fantasy.IV.Complete.Collection.psp.txt](https://github.com/libretro/RetroArch/files/4088728/Final.Fantasy.IV.Complete.Collection.psp.txt)

**Comment by RobLoach** [comment]
You'll have to port it to the RA cheats format https://github.com/libretro/libretro-database/tree/master/cht

**Comment by i30817** [comment]
Some cores also don't support the RA system of cheats and have (sometimes) inbuilt alternatives, PPSSPP being the one I know about.

Not sure if citra is like that.
