### ISSUE TITLE
(Cheats) Dragon Quest IX(U) - Nintendo DS

### ISSUE THREAD

**Issue by warriorblade** [libretro/libretro-database#978]
For some reason I couldn't find dragon quest ix(u)(which is for ds) cheats for retro arch anywhere except here, but I can't download the cheat file. Please give download link.

**Comment by RobLoach** [comment]
If it isn't in there, then it doesn't exist. Feel free to add it.

**Comment by RobLoach** [comment]
Found these ones while searching around...
https://gist.github.com/RobLoach/f5fabf9e1b97898b95ee16420bcd8471

They'd just need to be ported to a .cht file in the RetroArch format.

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-database/blob/816bd50049c7afcf6f2f22bcddbc3998ac8867b0/cht/Nintendo%20-%20Nintendo%20DS/Dragon%20Quest%20IX%20-%20Sentinels%20of%20the%20Starry%20Skies%20(USA)%20(En%2CFr%2CEs).cht
