### ISSUE TITLE
Updated outdated NES/Famicom and PC Engine/TurboGrafx-16 Cheats.

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#981]
PC Engine/ TurboGrafx-16 cheats were not working in their previous incarnation.  I've downloaded cheats from gamehacking.org and updated them via the instructions at https://www.bountysource.com/issues/58270012-bounty-add-cheat-support-to-beetle-pce-fast-core-in-retroarch.  They now work for the Beetle PCE Fast and Accurate cores.

NES/Famicom cheats were also a few years out of date, so I downloaded an entire new set from gamehacking.org.  Tested a handful in FCEUmm, Nestopia, and Mesen, so they should work fine.

Issues:  PC Engine/TurboGrafx-16 cheats only work for registers in the F82 range.  There are more cheats logged in the F80, F81, and F83 range, but so far they are not translatable over to RetroArch's cheat engine.  I will gladly update this pack if a way is figured out.  More info here: https://www.bountysource.com/issues/58270012-bounty-add-cheat-support-to-beetle-pce-fast-core-in-retroarch

[NEC - TurboGrafx16 - PC Engine - New Cheats.zip](https://github.com/libretro/libretro-database/files/4154954/NEC.-.TurboGrafx16.-.PC.Engine.-.New.Cheats.zip)

[Nintendo Entertainment System - Famicom - New Cheats.zip](https://github.com/libretro/libretro-database/files/4154956/Nintendo.Entertainment.System.-.Famicom.-.New.Cheats.zip)

I'll work on updating the rest of the cheat library and post them here if these are accepted.

**Comment by RobLoach** [comment]
Thanks so much for pushing those forwards!

**Comment by summonthethunder** [comment]
RobLoach, you're welcome!  However, the NES/Famicom cheats got merged into Family Computer Disk System by mistake.  They should go with/replace the existing NES/Famicom roms.  The FDS Roms are located in Issue #982.  Please fix when you can!

**Comment by summonthethunder** [comment]
Solved by #985
