### ISSUE TITLE
Super Nintendo Entertainment System cheats update.

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#988]
Cheat update for the Super Nintendo Entertainment System.  Multiple cheats tested on SNES9X and bsnes.  Codes generated from gamehacking.org.

SNES9X: Game Genie (AAAA-BBBB) and Action Replay (AAAAAABB) work.

bsnes: I can't get bsnes to accept Action Replay codes (the ones in AAAAAABB format).  I contacted byuu (bsnes creator) and he does not know why they don't work either.  Perhaps someone more knowledgeable with code than myself can look into that eventually.  I've tried the following alternate formats, but to no avail: AAAAAA:BB, AAAAAA/BB, and AAAAAA=BB.  Game Genie codes, however, work fine.

[Super Nintendo Entertainment System - Super Famicom - New Cheats.zip](https://github.com/libretro/libretro-database/files/4161460/Super.Nintendo.Entertainment.System.-.Super.Famicom.-.New.Cheats.zip)

**Comment by RobLoach** [comment]
YOUVE BEEN BUSY!
