### ISSUE TITLE
Add TurboGrafx-16 CD/PC Engine CD Cheats

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#989]
TG16 CD/PCE CD Cheats converted from gamehacking.org via the process discovered by users at https://www.bountysource.com/issues/58270012-bounty-add-cheat-support-to-beetle-pce-fast-core-in-retroarch.

Recommend they be put into a separate folder, keeping in line with FDS separate from NES, Sega CD separate from Genesis, etc.

Issue:  Like the TG16/PCE ROM cheats, these cheats only work on registers in the F82 range.  More cheats exist in the F80, F81, and F83 ranges, but I do not know how to add them via Libretro's cheat engine.  I will gladly update this list if someone can figure it out.

[NEC - TurboGrafx-16  CD - PC Engine CD - New Cheats.zip](https://github.com/libretro/libretro-database/files/4168525/NEC.-.TurboGrafx-16.CD.-.PC.Engine.CD.-.New.Cheats.zip)

**Comment by RobLoach** [comment]
Thanks a lot! Added in.

**Comment by negativeExponent** [comment]
im confused. im trying to add native cheats using mempatcher so as not to deal with memory conversions and easier support for multilines here:
https://github.com/libretro/beetle-pce-fast-libretro/issues/93#issuecomment-698547309

 but im confused as to what these are for example:

**cheat2_code = "AF3-DEE-7F1+3C3-DFE-916+7D3-E1E-197"**

i know + is multiline, but in what format is "AF3-DEE-7F1" ? i know cheats are being displayed as memory-pages (F82xxx) or raw memory (1Fxxxx). For CD ram games, raw formats from D0000 to 110000 or those suppose to be 68xxxx to 88xxxx's, but dont know what that one above is.

**Comment by RobLoach** [comment]
Re-opening. I'm unsure of the proper format for the cheats.

**Comment by negativeExponent** [comment]
disregard my previous comment. it turns out that a recent update has added and remove the unknown AF3-DEE-7F1 format for example (which were codes for a difference system, GB in this case)

**Comment by RobLoach** [comment]
Excellent! Thanks a lot :+1:

**Comment by Metro-City** [comment]
Like what program or how can I put it to the iso and then use it on the original machine? thank you
