### ISSUE TITLE
Index the Redump Serials... For all disc-media, including Dreamcast

### ISSUE THREAD

**Issue by iroc-1** [libretro/libretro-database#990]
Hi

I was investigating why Retroarch (1.8.4 on Windows) was refusing to scan Dreamcast games. (cue + bin, uncompressed, matching redump size and crcs)
If I understand the logs properly, Retroarch tries to locate the biggest track, assumes it's the main data track, calculates the crc for it, and try to match it with a known crc in the rdb.
But when the .dat file for retroarch is built, the same logic is not followed (or maybe there's a bug).
In the Dat located here [https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sega%20-%20Dreamcast.dat](https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sega%20-%20Dreamcast.dat) we can see the entry for "Crazy Taxi 2 (USA)" contains only the first data track (and not the largest one), meaning Retroarch will never find its crc.
(for reference, the entry in redump is [here](http://redump.org/disc/51575/))

Shouldn't the rdb contain all the tracks or at leat the biggest one instead of always using the first one ?
Is it a bug or a feature ?

**Comment by RobLoach** [comment]
RetroArch's database is build by one game -> one rom... Having multiple roms in the DAT will not accomplish anything.

**Comment by iroc-1** [comment]
Yes indeed, it seems this model doesn't hold too well with CD-Based games which at typically made of a .cue + .bin files. Having all the tracks present in the database would have allowed retroarch to match the crc of whtever track it chooses, but if this is not an option, then so be it :)
How do you propose to fix the issue ?
Is it possible to change the way the track is selected when building the database to match with retroarch logic ?

**Comment by RobLoach** [comment]
RetroArch has some support for scanning the serial code in disc images. gdi files, chd, iso, etc... 

https://github.com/libretro/RetroArch/blob/8627d638e1d05c64152475d4aba7ecc7a57f09b1/tasks/task_database.c

It takes this approach for larger disc images because getting the CRC of large files is very slow. I'm not sure if the support is there for discovering the serial code for Dreamcast games, but would love some testing on it.

We also don't have the serial numbers in the DB for those right now either.

**Comment by RobLoach** [comment]
We could do some testing with it by...

1. Grabbing the serial number from redump.org
2. Building a DAT file with the serials defined
3. Rebuild the dreamcast RDB with a key index on the serial
4. Stick the new dreamcast rdb in the rdb folder
5. Scan a redumped disc in RetroArch to see if it shows up properly

**Comment by iroc-1** [comment]
Thanks you for the followup.
Indeed Dreamcast games seem to have a serial (51136 in the case of Crazy Taxi 2 (USA))
That would be an interesting test to do.
But unfortunately, I don't see any trace of it in the Redump official DAT. The info is just not there.
Maybe that's the reason why retroarch is using crc to try to match Dreamcast games.

Just looking quickly at the code, I didn't see any Dreamcast specific code to extract the serial.
I am also not the sure on what track the serial is actually located.

How do we decide what goes into https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sega%20-%20Dreamcast.dat ?
Is it the tool located here http://github.com/robloach/libretro-dats ?
If it's the case, then maybe there is an issue in index.js where the largest track is selected.

**Comment by iroc-1** [comment]
Ok, I think I found something.
The download.js file is not downloading the cuesheets, only the DATs.
There is a silent error [here](https://github.com/RobLoach/libretro-dats/blob/68c5c1e994c7c149ea78ef2eb4f36e6c36201d60/index.js#L396) if the cuesheet cannot be found.
When this happens, the logic checking for the largest track is not used (because datatracks is empty), resulting in the wrong track being selected.
I suspect regenerating the dats with the cuesheets downloaded will fix many issues related to scanning.
Or maybe reworking the logic to not use the cuesheets at all since we already have all the info need about the various tracks.
Please correct me if I'm wrong

**Comment by RobLoach** [comment]
You're correct.

libretro-dats tries to convert the XML-format DATs into Retroarch-format DATs. Curious if we could make a scrapper for the serials in redump over at http://redump.org/discs/system/dc/

**Comment by iroc-1** [comment]
I guess a scraper should be be doable, or maybe asking nicely to redump if they could add it to their official DAT will work as well.
I am not familiar with the serial recognition. How does it work for multi disk games that have the same serial on all disks ? 
Some entries also seem to have multiple serials associated with them.
Shenmue seems to have all this at the same time (mutliple disks, normal / limited edition)

If we get back to the data track selection to help crc based recognition (so not just dreamcast), what is the process to regenerate the official Retroarch dat files ?
Is there a CI/CD somewhere that can be triggered for that, or is it the work of a individual on his computer ?
Also are there any automated tests that can verify the we are not introducing any regression ?

I tried to create an rdb file from the new dat, but I am only getting a very small file and get a segfault when trying to list the games inside. I must have something wrong with my setup :) (wsl on windows)

**Comment by RobLoach** [comment]
> How does it work for multi disk games that have the same serial on all disks ?

I'm unsure. Could be worth checking how redump labels them.

> If we get back to the data track selection to help crc based recognition (so not just dreamcast), what is the process to regenerate the official Retroarch dat files ?

The Makefile can build the RDBs for you... https://github.com/libretro/libretro-database#building

More info here: https://github.com/libretro/RetroArch/blob/master/libretro-db/README.md

> Is there a CI/CD somewhere that can be triggered for that, or is it the work of a individual on his computer ?

It's run manually. I usually rebuild and tag it every stable RetroArch release.

> Also are there any automated tests that can verify the we are not introducing any regression ?

Not currently. When you build the RDBs, it'll shoot warnings when data is missing. It'll also error out if there is a syntax error.

> I tried to create an rdb file from the new dat, but I am only getting a very small file and get a segfault when trying to list the games inside. I must have something wrong with my setup :) (wsl on windows

Hmm, never tried on Windows. If you find something, feel free to post your experiences. Would be good to update the docs where needed.

**Comment by iroc-1** [comment]
Ok, I restarted from scratch, cloned the libretro-super, and re-ran the make command from wsl, and it's working properly now.
I was able to generate the rdb file using the new Dat I created using your tool with the cue sheets downloaded.
And magic, all the Dreamcast games are now scanning :)
I re-did the same thing for PC Engine, and same result, everything is scanning fine now

**Comment by RobLoach** [comment]
Did you change anythihng in the DAT files? Or just leave as is?

**Comment by iroc-1** [comment]
I did not manually change the dat files, as I just let the tool do the work for me.
I will do an End2End test later today: Scan all PC-Engine CDs and compare the generated playlist with the DAT to make sure every thing is there.

As far as I understand, the next steps to permanently fix the issue of crc scanning of .cue + bins would be to:
- Update the .js code to fix the track selection issue. (stop relying on reading .cues, or automate their downloads and make the tool fail if they are not present)
- Regenerate the DATs 
- Regenerate the RDBs

This will fix all scanning issues for CD based crc detection when the main Data track is not the first one.
Would you be kind enough to help with the code ? :)

**Comment by iroc-1** [comment]
Ok ran my test and after scanning the whole set of PCEngine Games, only 12 of them are not being scanned.
A huge improvement !

**Comment by RobLoach** [comment]
Once we bring in the redump serials correctly, we can index them right... Hopefully. I'm unsure if Retroarch detects dreamcast serials correctly when they're in the DB, so we should retest this when it's in place....
http://redump.org/datfile/psp/serial,version

**Comment by iroc-1** [comment]
Good news if Dreamcast can support serials in the future, it will make scanning faster.
But right now, the .dat present in libretrodatabase for crc-based detection system are broken. ( I used PC Engine as an example since the set is small)
It's really just a matter of regenerating them with your tool with the .cue sheets being downloaded.
The code in charge of downloading the redump dats is commented out, so I'm not even sure how you can run your tool successfully.

**Comment by RobLoach** [comment]
Serials added.... We'll need to do some work in RetroArch to add serial scanning for each system, but there we go...
https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sega%20-%20Dreamcast.dat
https://github.com/libretro/libretro-database/blob/master/metadat/redump/NEC%20-%20PC%20Engine%20CD%20-%20TurboGrafx-CD.dat

**Comment by iroc-1** [comment]
That's a good thing we now have the serials in the dat files.
But until retroarch adds the support for serial on those platforms, scanning of (crc-based) PCEngine for example is still failing.
The dat you linked for PC Engine is still having the wrong data tracks selected.
Any specific reason why you refuse to fix the current issue by just regenerating the dats properly ?

**Comment by RobLoach** [comment]
What? I'm not refusing anything. Could you detail a better way to select the track?

**Comment by iroc-1** [comment]
As I explained earlier in this thread, the tool that is generating the .Dats is not selecting the largest data track properly. (and this is what retroach is going to look for)
The logic [here](https://github.com/RobLoach/libretro-dats/blob/089106bbef1e2fb78e1a96f04c7d348cef933a6e/index.js#L340) that iterates through all the tracks to select the largest one is only working if the cue files are downloaded, or else always select the first track
I suspect you don't have all the cue files downloaded on the machine you are running you tool on.
As mentioned, I was able to regenerate a working PCEngine rdb just by running your tool with the cue files downloaded :)

**Comment by pkos** [comment]
> As I explained earlier in this thread, the tool that is generating the .Dats is not selecting the largest data track properly. (and this is what retroach is going to look for)
> The logic [here](https://github.com/RobLoach/libretro-dats/blob/089106bbef1e2fb78e1a96f04c7d348cef933a6e/index.js#L340) that iterates through all the tracks to select the largest one is only working if the cue files are downloaded, or else always select the first track
> I suspect you don't have all the cue files downloaded on the machine you are running your tool on.
> As mentioned, I was able to regenerate a working PCEngine dats and rdb just by running your tool with the cue files downloaded :)

This PR updates the scanner to include DreamCast games, and Rob has updated the serials in the database.  If you wish, please clone and test this PR and run your scan again.

**Comment by RobLoach** [comment]
Suffixes provided by @pkos https://gist.github.com/RobLoach/c2051e64a742849fcc485d4b59948056

**Comment by Rstation4** [comment]
What about the odd case of Sega Naomi, From what I have looked up, The first version had rom cartridges and the later revision was converting it to support GD-ROM. I was wondering if a dat and playlist for Sega - Naomi would be accepted. Unless they would Rather keep it under MAME with MAME's versions of Sega Naomi roms.

Sega Naomi info https://segaretro.org/Sega_NAOMI
Redump Disc info   http://redump.org/discs/system/naomi/
