### ISSUE TITLE
Nintendo N64 Cheat List Update

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#992]
Updated list for Nintendo N64.  Codes generated from gamehacking.org.

Issue: I can't seem to get Mupen64Plus Next or Parallel 64 to accept cheat codes.  I tried with both the existing codes and these new codes and I can't get any to stick.  If I'm doing something wrong let me know and I'll do a more indepth test.  They do work on standalone emulators like PJ64 and M64P.

Also, some of these cheat lists are thousands of codes long.  Perhaps it would behoove the team to remind everyone of the search function for RetroArch and how to use it in an upcoming blog or update post.

[Nintendo - N64 - New Cheats.zip](https://github.com/libretro/libretro-database/files/4177983/Nintendo.-.N64.-.New.Cheats.zip)

**Comment by RobLoach** [comment]
These look great! I do see some duplicates now, but we could fix that later on.

**Comment by summonthethunder** [comment]
Duplicates in my entries or with the already existing codes?

**Comment by RobLoach** [comment]
Like.......

- 	007 - The World Is Not Enough (Europe) (En,Fr,De).cht
-	007 - The World Is Not Enough (USA) (Beta).cht
-	007 - The World Is Not Enough (USA).cht
-	007 The World is Not Enough (E).cht

**Comment by summonthethunder** [comment]
Ah, I see.  The first three are actually separate carts, hence why they are separate cheat formats.  The last one [(007 The World is Not Enough (E)] can probably go since [(007 - The World is Not Enough (Europe)] exists.  I'll keep an out for these in the future and adjust accordingly.
