### ISSUE TITLE
Update for SEGA Genesis - Mega Drive Cheats

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#999]
Updated SEGA Genesis - Mega Drive Cheats.  Codes from gamehacking.org.  Tested in Genesis Plus GX and Picodrive cores.

[SEGA - Genesis - Mega Drive - New Cheats.zip](https://github.com/libretro/libretro-database/files/4217808/SEGA.-.Genesis.-.Mega.Drive.-.New.Cheats.zip)

**Comment by RobLoach** [comment]
Thanks a lot! How are you exporting these???

**Comment by summonthethunder** [comment]
> Thanks a lot! How are you exporting these???

Each individual game has options at the top of the screen on how you want to see the cheat codes and also gives you the option to download them if you wish.

For example, if you want cheats for the Sonic the Hedgehog (USA, Europe) cart, go to the Format pull-down menu and select libretro.  From there, you can download the cheats and it's automatically put into the .cht format that libretro uses.  See attached pic.

![gamehacking org](https://user-images.githubusercontent.com/16481916/74762942-aef01200-5233-11ea-8c76-0e25c55b1d2b.jpg)


Once I have the codes, I test about 10 of them randomly to ensure the codes work, and I note what works and what doesn't if applicable. For example, SEGA Genesis took so long because it exported all PAR codes as AAAAAABBBB, and libretro expects AAAAAA:BBBB format, so I had to go in and manually change each one of those for every game.

It takes a while because you have to go into each individual game and download the codes.  I haven't found a way to download an entire systems worth of codes yet.  It works correctly for the most part.

**Comment by RobLoach** [comment]
Would be awesome to put together a scrapper for it. Would probably end up taking more time though :woman_shrugging: 

In any case, these are great!
